// Generated by Human compiler — do not edit

import { useState } from 'react';
import { useNavigate } from 'react-router-dom';

function GlobeIcon() {
  return (
    <svg width="20" height="20" viewBox="0 0 20 20" fill="none" stroke="#3A3D4D" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
      <circle cx="10" cy="10" r="8.25"/>
      <path d="M1.75 10h16.5"/>
      <path d="M10 1.75c2.21 2.56 3.46 5.82 3.5 9.25-.04 3.43-1.29 6.69-3.5 9.25-2.21-2.56-3.46-5.82-3.5-9.25.04-3.43 1.29-6.69 3.5-9.25z"/>
    </svg>
  );
}

const font = "'Plus Jakarta Sans', sans-serif";

export default function ForgotPasswordPage() {
  const navigate = useNavigate();
  const [email, setEmail] = useState('');
  const [sent, setSent] = useState(false);
  const [loading, setLoading] = useState(false);

  const handleSubmit = async () => {
    if (!email) return;
    setLoading(true);
    try {
      await fetch('/api/forgot-password', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ email }),
      });
    } catch {
      // Still show success to prevent email enumeration
    } finally {
      setSent(true);
      setLoading(false);
    }
  };

  return (
    <div style={{ minHeight: '100vh', background: '#FDFDFF', fontFamily: font }}>
      {/* ── Navigation Bar ── */}
      <nav style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '33px 60px', background: '#FFFFFF' }}>
        <span style={{ fontWeight: 700, fontSize: '36px', lineHeight: 1.5, color: '#252833', fontFamily: font }}>Time Keeper</span>
        <div style={{ display: 'flex', gap: '40px', alignItems: 'center' }}>
          <span style={{ display: 'flex', gap: '8px', alignItems: 'center', fontWeight: 500, fontSize: '18px', color: '#3A3D4D', fontFamily: font }}>
            <GlobeIcon /> EN
          </span>
          <button style={{ border: '1px solid #515466', borderRadius: '8px', padding: '10px 30px', background: 'transparent', fontWeight: 500, fontSize: '22px', color: '#515466', cursor: 'pointer', fontFamily: font, lineHeight: 1.5 }}>Sign Up</button>
        </div>
      </nav>

      {/* ── Form ── */}
      <div style={{ width: '581px', margin: '0 auto', paddingTop: '40px' }}>
        <h1 style={{ fontWeight: 800, fontSize: '54px', lineHeight: 1.5, color: '#252833', margin: '0', fontFamily: font }}>
          Password recovery
        </h1>
        <p style={{ fontWeight: 400, fontSize: '16px', lineHeight: 1.5, color: '#696C80', margin: '0 0 48px 0', fontFamily: font }}>
          {sent
            ? `If an account exists for ${email}, we'll send instructions for resetting your password. Didn't get them? Check the email address or ask to resend the instructions.`
            : 'Enter the email address associated with your account to get a code'
          }
        </p>

        {!sent && (
          <>
            <div style={{ marginBottom: '48px' }}>
              <label style={{ display: 'block', fontWeight: 500, fontSize: '18px', lineHeight: 1.5, color: '#696C80', marginBottom: '12px', fontFamily: font }}>
                Work Email
              </label>
              <input
                type="email"
                placeholder="Add email"
                value={email}
                onChange={e => setEmail(e.target.value)}
                onKeyDown={e => { if (e.key === 'Enter' && email) handleSubmit(); }}
                style={{ width: '100%', height: '60px', padding: '0 20px', border: '1px solid #D8DAE5', borderRadius: '10px', background: '#FFFFFF', fontSize: '14px', lineHeight: 1.5, color: '#252833', fontFamily: font, outline: 'none', boxSizing: 'border-box' as const }}
              />
            </div>

            <button
              onClick={handleSubmit}
              disabled={loading || !email}
              style={{ width: '100%', height: '67px', borderRadius: '10px', border: 'none', background: '#3C1E5E', color: '#FFFFFF', fontWeight: 700, fontSize: '22px', lineHeight: 1.5, cursor: email ? 'pointer' : 'default', fontFamily: font, marginBottom: '24px', opacity: email ? 1 : 0.7 }}
            >
              {loading ? 'Sending...' : 'Continue'}
            </button>
          </>
        )}

        {sent && (
          <button
            onClick={() => window.open('https://mail.google.com', '_blank')}
            style={{ width: '100%', height: '67px', borderRadius: '10px', border: 'none', background: '#3C1E5E', color: '#FFFFFF', fontWeight: 700, fontSize: '22px', lineHeight: 1.5, cursor: 'pointer', fontFamily: font, marginBottom: '24px' }}
          >
            Go to Email
          </button>
        )}

        <button
          onClick={() => navigate('/sign-in')}
          style={{ fontWeight: 400, fontSize: '20px', lineHeight: 1.5, color: '#2D4A98', textDecoration: 'underline', display: 'block', textAlign: 'center' as const, fontFamily: font, cursor: 'pointer', background: 'none', border: 'none', padding: 0, width: '100%' }}
        >
          Back to Login
        </button>
      </div>
    </div>
  );
}
