// Generated by Human compiler — do not edit

import { useState } from 'react';
import { useNavigate } from 'react-router-dom';

/* ── Inline SVG Icons ───────────────────────────────────── */

function GoogleIcon() {
  return (
    <svg width="24" height="24" viewBox="0 0 24 24" fill="none">
      <path d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92a5.06 5.06 0 0 1-2.2 3.32v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.1z" fill="#4285F4"/>
      <path d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z" fill="#34A853"/>
      <path d="M5.84 14.09A6.68 6.68 0 0 1 5.5 12c0-.72.12-1.42.35-2.09V7.07H2.18A11.96 11.96 0 0 0 1 12c0 1.94.46 3.77 1.18 5.43l3.66-2.84z" fill="#FBBC05"/>
      <path d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z" fill="#EA4335"/>
    </svg>
  );
}

function SlackIcon() {
  return (
    <svg width="24" height="24" viewBox="0 0 24 24" fill="none">
      <path d="M5.042 15.165a2.528 2.528 0 0 1-2.52 2.523A2.528 2.528 0 0 1 0 15.165a2.527 2.527 0 0 1 2.522-2.52h2.52v2.52zm1.271 0a2.527 2.527 0 0 1 2.521-2.52 2.527 2.527 0 0 1 2.521 2.52v6.313A2.528 2.528 0 0 1 8.834 24a2.528 2.528 0 0 1-2.521-2.522v-6.313z" fill="#E01E5A"/>
      <path d="M8.834 5.042a2.528 2.528 0 0 1-2.521-2.52A2.528 2.528 0 0 1 8.834 0a2.528 2.528 0 0 1 2.521 2.522v2.52H8.834zm0 1.271a2.528 2.528 0 0 1 2.521 2.521 2.528 2.528 0 0 1-2.521 2.521H2.522A2.528 2.528 0 0 1 0 8.834a2.528 2.528 0 0 1 2.522-2.521h6.312z" fill="#36C5F0"/>
      <path d="M18.956 8.834a2.528 2.528 0 0 1 2.522-2.521A2.528 2.528 0 0 1 24 8.834a2.528 2.528 0 0 1-2.522 2.521h-2.522V8.834zm-1.27 0a2.528 2.528 0 0 1-2.523 2.521 2.527 2.527 0 0 1-2.52-2.521V2.522A2.527 2.527 0 0 1 15.163 0a2.528 2.528 0 0 1 2.523 2.522v6.312z" fill="#2EB67D"/>
      <path d="M15.163 18.956a2.528 2.528 0 0 1 2.523 2.522A2.528 2.528 0 0 1 15.163 24a2.527 2.527 0 0 1-2.52-2.522v-2.522h2.52zm0-1.27a2.527 2.527 0 0 1-2.52-2.523 2.527 2.527 0 0 1 2.52-2.52h6.315A2.528 2.528 0 0 1 24 15.163a2.528 2.528 0 0 1-2.522 2.523h-6.315z" fill="#ECB22E"/>
    </svg>
  );
}

function TeamsIcon() {
  return (
    <svg width="24" height="24" viewBox="0 0 24 24" fill="none">
      <path d="M20.625 6.547h-5.578v8.672a1.406 1.406 0 0 1-1.406 1.406H8.203a6.094 6.094 0 0 0 6.094 6.094h.234a6.094 6.094 0 0 0 6.094-6.094V6.547z" fill="#5059C9"/>
      <circle cx="19.125" cy="3.375" r="2.625" fill="#5059C9"/>
      <circle cx="11.25" cy="3.75" r="3.75" fill="#7B83EB"/>
      <path d="M14.953 7.5H5.297A1.297 1.297 0 0 0 4 8.797v7.453A7.5 7.5 0 0 0 11.25 23.5h.75a7.5 7.5 0 0 0 4.25-8.25V8.797A1.297 1.297 0 0 0 14.953 7.5z" fill="#7B83EB"/>
    </svg>
  );
}

function AppleIcon() {
  return (
    <svg width="24" height="24" viewBox="0 0 24 24" fill="none">
      <path d="M17.05 20.28c-.98.95-2.05.8-3.08.35-1.09-.46-2.09-.48-3.24 0-1.44.62-2.2.44-3.06-.35C2.79 15.25 3.51 7.59 9.05 7.31c1.35.07 2.29.74 3.08.8 1.18-.24 2.31-.93 3.57-.84 1.51.12 2.65.72 3.4 1.8-3.12 1.87-2.38 5.98.48 7.13-.57 1.5-1.31 2.99-2.54 4.09zM12.03 7.25c-.15-2.23 1.66-4.07 3.74-4.25.29 2.58-2.34 4.5-3.74 4.25z" fill="#000"/>
    </svg>
  );
}

function FacebookIcon() {
  return (
    <svg width="24" height="24" viewBox="0 0 24 24" fill="none">
      <path d="M24 12.073C24 5.405 18.627 0 12 0S0 5.405 0 12.073C0 18.1 4.388 23.094 10.125 24v-8.437H7.078v-3.49h3.047v-2.66c0-3.025 1.792-4.697 4.533-4.697 1.312 0 2.686.236 2.686.236v2.971H15.83c-1.491 0-1.956.93-1.956 1.886v2.264h3.328l-.532 3.49h-2.796V24C19.612 23.094 24 18.1 24 12.073z" fill="#1877F2"/>
    </svg>
  );
}

function GlobeIcon() {
  return (
    <svg width="20" height="20" viewBox="0 0 20 20" fill="none" stroke="#3A3D4D" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
      <circle cx="10" cy="10" r="8.25"/>
      <path d="M1.75 10h16.5"/>
      <path d="M10 1.75c2.21 2.56 3.46 5.82 3.5 9.25-.04 3.43-1.29 6.69-3.5 9.25-2.21-2.56-3.46-5.82-3.5-9.25.04-3.43 1.29-6.69 3.5-9.25z"/>
    </svg>
  );
}

function EyeIcon({ open }: { open: boolean }) {
  if (open) {
    return (
      <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="#696C80" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
        <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"/>
        <circle cx="12" cy="12" r="3"/>
      </svg>
    );
  }
  return (
    <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="#696C80" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
      <path d="M17.94 17.94A10.07 10.07 0 0 1 12 20c-7 0-11-8-11-8a18.45 18.45 0 0 1 5.06-5.94M9.9 4.24A9.12 9.12 0 0 1 12 4c7 0 11 8 11 8a18.5 18.5 0 0 1-2.16 3.19m-6.72-1.07a3 3 0 1 1-4.24-4.24"/>
      <line x1="1" y1="1" x2="23" y2="23"/>
    </svg>
  );
}

/* ── Styles ───────────────────────────────────────────── */

const font = "'Plus Jakarta Sans', sans-serif";

const styles = {
  page: {
    minHeight: '100vh',
    background: '#FDFDFF',
    fontFamily: font,
  } as React.CSSProperties,

  nav: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '33px 60px',
    background: '#FFFFFF',
  } as React.CSSProperties,

  brand: {
    fontWeight: 700,
    fontSize: '36px',
    lineHeight: 1.5,
    color: '#252833',
    fontFamily: font,
  } as React.CSSProperties,

  navRight: {
    display: 'flex',
    gap: '40px',
    alignItems: 'center',
  } as React.CSSProperties,

  langSelector: {
    display: 'flex',
    gap: '8px',
    alignItems: 'center',
    fontWeight: 500,
    fontSize: '18px',
    color: '#3A3D4D',
    fontFamily: font,
  } as React.CSSProperties,

  signUpBtn: {
    border: '1px solid #515466',
    borderRadius: '8px',
    padding: '10px 30px',
    background: 'transparent',
    fontWeight: 500,
    fontSize: '22px',
    color: '#515466',
    cursor: 'pointer',
    fontFamily: font,
    lineHeight: 1.5,
  } as React.CSSProperties,

  formContainer: {
    width: '592px',
    margin: '0 auto',
    paddingTop: '40px',
  } as React.CSSProperties,

  heading: {
    fontWeight: 800,
    fontSize: '54px',
    lineHeight: 1.5,
    color: '#252833',
    margin: '0 0 32px 0',
    fontFamily: font,
  } as React.CSSProperties,

  socialRow: {
    display: 'flex',
    gap: '48px',
    alignItems: 'center',
    marginBottom: '48px',
  } as React.CSSProperties,

  googleBtn: {
    display: 'flex',
    gap: '16px',
    alignItems: 'center',
    padding: '12px 15px',
    border: '2px solid #BABDCC',
    borderRadius: '10px',
    background: '#FFFFFF',
    cursor: 'pointer',
    fontWeight: 500,
    fontSize: '22px',
    color: '#3A3D4D',
    fontFamily: font,
    lineHeight: 1.5,
  } as React.CSSProperties,

  socialIcons: {
    display: 'flex',
    gap: '16px',
    alignItems: 'center',
  } as React.CSSProperties,

  socialIconBtn: {
    width: '48px',
    height: '48px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    borderRadius: '8px',
    padding: 0,
  } as React.CSSProperties,

  emailLabel: {
    fontWeight: 500,
    fontSize: '22px',
    lineHeight: 1.5,
    color: '#252833',
    margin: '0 0 16px 0',
    fontFamily: font,
  } as React.CSSProperties,

  fieldGroup: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '24px',
    marginBottom: '16px',
  } as React.CSSProperties,

  fieldLabel: {
    display: 'block',
    fontWeight: 500,
    fontSize: '18px',
    lineHeight: 1.5,
    color: '#696C80',
    marginBottom: '12px',
    fontFamily: font,
  } as React.CSSProperties,

  input: {
    width: '100%',
    height: '60px',
    padding: '0 20px',
    border: '1px solid #D8DAE5',
    borderRadius: '10px',
    background: '#FFFFFF',
    fontSize: '14px',
    lineHeight: 1.5,
    color: '#252833',
    fontFamily: font,
    outline: 'none',
    boxSizing: 'border-box' as const,
  } as React.CSSProperties,

  passwordWrapper: {
    position: 'relative' as const,
  } as React.CSSProperties,

  eyeBtn: {
    position: 'absolute' as const,
    right: '20px',
    top: '50%',
    transform: 'translateY(-50%)',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: 0,
    display: 'flex',
    alignItems: 'center',
  } as React.CSSProperties,

  forgotLink: {
    fontWeight: 400,
    fontSize: '20px',
    lineHeight: 1.5,
    color: '#2D4A98',
    textDecoration: 'underline',
    fontFamily: font,
    cursor: 'pointer',
    background: 'none',
    border: 'none',
    padding: 0,
    display: 'block',
    marginBottom: '48px',
  } as React.CSSProperties,

  signInBtn: (active: boolean) => ({
    width: '100%',
    height: '67px',
    borderRadius: '10px',
    border: 'none',
    background: active ? '#2D4A98' : '#BABDCC',
    color: '#F8FAFF',
    fontWeight: 700,
    fontSize: '22px',
    lineHeight: 1.5,
    cursor: active ? 'pointer' : 'default',
    fontFamily: font,
    marginBottom: '24px',
  } as React.CSSProperties),

  ssoLink: {
    fontWeight: 400,
    fontSize: '20px',
    lineHeight: 1.5,
    color: '#2D4A98',
    textDecoration: 'underline',
    display: 'block',
    textAlign: 'center' as const,
    fontFamily: font,
    cursor: 'pointer',
    background: 'none',
    border: 'none',
    padding: 0,
    width: '100%',
  } as React.CSSProperties,

  errorBox: {
    background: '#FEF2F2',
    border: '1px solid #FECACA',
    color: '#DC2626',
    padding: '12px 16px',
    borderRadius: '10px',
    marginBottom: '16px',
    fontSize: '14px',
    fontFamily: font,
  } as React.CSSProperties,
};

/* ── Component ────────────────────────────────────────── */

export default function SignInPage() {
  const navigate = useNavigate();
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [showPassword, setShowPassword] = useState(false);

  const handleLogin = async () => {
    if (!email || !password) return;
    setLoading(true);
    setError('');
    try {
      const res = await fetch('/api/login', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ email, password }),
      });
      const data = await res.json();
      if (!res.ok) {
        setError(data.error || 'Login failed');
      } else {
        localStorage.setItem('token', data.token);
        navigate('/');
      }
    } catch {
      setError('Something went wrong. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && email && password) handleLogin();
  };

  const isActive = Boolean(email && password);

  return (
    <div style={styles.page}>
      {/* ── Navigation Bar ── */}
      <nav style={styles.nav}>
        <span style={styles.brand}>Time Keeper</span>
        <div style={styles.navRight}>
          <span style={styles.langSelector}>
            <GlobeIcon /> EN
          </span>
          <button style={styles.signUpBtn}>Sign Up</button>
        </div>
      </nav>

      {/* ── Form ── */}
      <div style={styles.formContainer}>
        <h1 style={styles.heading}>Sign in</h1>

        {/* Social login */}
        <div style={styles.socialRow}>
          <button style={styles.googleBtn}>
            <GoogleIcon />
            <span>Sign in with Google</span>
          </button>
          <div style={styles.socialIcons}>
            <button style={styles.socialIconBtn} title="Slack"><SlackIcon /></button>
            <button style={styles.socialIconBtn} title="Microsoft Teams"><TeamsIcon /></button>
            <button style={styles.socialIconBtn} title="Apple"><AppleIcon /></button>
            <button style={styles.socialIconBtn} title="Facebook"><FacebookIcon /></button>
          </div>
        </div>

        {/* Email section */}
        <p style={styles.emailLabel}>or use your email to sign in:</p>

        <div style={styles.fieldGroup}>
          <div>
            <label style={styles.fieldLabel}>Work email</label>
            <input
              type="email"
              placeholder="Add work email address"
              value={email}
              onChange={e => setEmail(e.target.value)}
              onKeyDown={handleKeyDown}
              style={styles.input}
            />
          </div>
          <div>
            <label style={styles.fieldLabel}>Password</label>
            <div style={styles.passwordWrapper}>
              <input
                type={showPassword ? 'text' : 'password'}
                placeholder="Password"
                value={password}
                onChange={e => setPassword(e.target.value)}
                onKeyDown={handleKeyDown}
                style={styles.input}
              />
              <button
                type="button"
                onClick={() => setShowPassword(!showPassword)}
                style={styles.eyeBtn}
                tabIndex={-1}
              >
                <EyeIcon open={showPassword} />
              </button>
            </div>
          </div>
        </div>

        <button
          onClick={(e) => { e.preventDefault(); navigate('/forgot-password'); }}
          style={styles.forgotLink}
        >
          I forgot my password
        </button>

        {error && <div style={styles.errorBox}>{error}</div>}

        <button
          onClick={handleLogin}
          disabled={loading || !isActive}
          style={styles.signInBtn(isActive && !loading)}
        >
          {loading ? 'Signing in...' : 'Sign In'}
        </button>

        <button style={styles.ssoLink}>
          Sign in with Single Sign On
        </button>
      </div>
    </div>
  );
}
