// Generated by Human compiler — do not edit

import { BrowserRouter, Routes, Route } from 'react-router-dom';
import './styles/global.css';
import SignInPage from './pages/SignInPage';
import ForgotPasswordPage from './pages/ForgotPasswordPage';

export default function App() {
  return (
    <BrowserRouter>
      <Routes>
        <Route path="/sign-in" element={<SignInPage />} />
        <Route path="/forgot-password" element={<ForgotPasswordPage />} />
        <Route path="*" element={<div style={{ textAlign: 'center', padding: '4rem' }}><h1>404</h1><p>Page not found</p></div>} />
      </Routes>
    </BrowserRouter>
  );
}
