package react

import (
	"strings"

	"github.com/barun-bash/human/internal/ir"
)

// generateAuthContext produces src/contexts/AuthContext.tsx with a React context
// that manages authentication state via localStorage token.
func generateAuthContext(app *ir.Application) string {
	_ = app // reserved for future auth method customization

	var b strings.Builder

	b.WriteString("// Generated by Human compiler — do not edit\n\n")
	b.WriteString("import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';\n\n")

	// Interface
	b.WriteString("interface AuthContextType {\n")
	b.WriteString("  isAuthenticated: boolean;\n")
	b.WriteString("  login: (token: string) => void;\n")
	b.WriteString("  logout: () => void;\n")
	b.WriteString("}\n\n")

	// Context
	b.WriteString("const AuthContext = createContext<AuthContextType | undefined>(undefined);\n\n")

	// Provider
	b.WriteString("export function AuthProvider({ children }: { children: ReactNode }) {\n")
	b.WriteString("  const [isAuthenticated, setIsAuthenticated] = useState<boolean>(() => {\n")
	b.WriteString("    return !!localStorage.getItem('token');\n")
	b.WriteString("  });\n\n")

	b.WriteString("  useEffect(() => {\n")
	b.WriteString("    const token = localStorage.getItem('token');\n")
	b.WriteString("    setIsAuthenticated(!!token);\n")
	b.WriteString("  }, []);\n\n")

	b.WriteString("  const login = (token: string) => {\n")
	b.WriteString("    localStorage.setItem('token', token);\n")
	b.WriteString("    setIsAuthenticated(true);\n")
	b.WriteString("  };\n\n")

	b.WriteString("  const logout = () => {\n")
	b.WriteString("    localStorage.removeItem('token');\n")
	b.WriteString("    setIsAuthenticated(false);\n")
	b.WriteString("  };\n\n")

	b.WriteString("  return (\n")
	b.WriteString("    <AuthContext.Provider value={{ isAuthenticated, login, logout }}>\n")
	b.WriteString("      {children}\n")
	b.WriteString("    </AuthContext.Provider>\n")
	b.WriteString("  );\n")
	b.WriteString("}\n\n")

	// Hook
	b.WriteString("export function useAuth(): AuthContextType {\n")
	b.WriteString("  const context = useContext(AuthContext);\n")
	b.WriteString("  if (!context) {\n")
	b.WriteString("    throw new Error('useAuth must be used within an AuthProvider');\n")
	b.WriteString("  }\n")
	b.WriteString("  return context;\n")
	b.WriteString("}\n")

	return b.String()
}

// generateProtectedRoute produces src/components/ProtectedRoute.tsx which
// guards routes by checking authentication state via useAuth().
func generateProtectedRoute() string {
	var b strings.Builder

	b.WriteString("// Generated by Human compiler — do not edit\n\n")
	b.WriteString("import { Navigate } from 'react-router-dom';\n")
	b.WriteString("import { useAuth } from '../contexts/AuthContext';\n\n")

	b.WriteString("export default function ProtectedRoute({ children }: { children: React.ReactNode }) {\n")
	b.WriteString("  const { isAuthenticated } = useAuth();\n\n")
	b.WriteString("  if (!isAuthenticated) {\n")
	b.WriteString("    return <Navigate to=\"/login\" replace />;\n")
	b.WriteString("  }\n\n")
	b.WriteString("  return <>{children}</>;\n")
	b.WriteString("}\n")

	return b.String()
}

// isPublicPage returns true for pages that should not be wrapped with ProtectedRoute.
// These are pages that unauthenticated users need access to.
func isPublicPage(name string) bool {
	lower := strings.ToLower(name)
	return lower == "home" || lower == "login" || lower == "signup" ||
		lower == "sign-up" || lower == "register" || lower == "landing"
}
