package react

import (
	"fmt"
	"strings"

	"github.com/barun-bash/human/internal/codegen/themes"
	"github.com/barun-bash/human/internal/ir"
)

// generateApp produces App.tsx with React Router setup.
// If a design system with a provider component is configured, the routes
// are wrapped in the appropriate ThemeProvider.
func generateApp(app *ir.Application) string {
	var b strings.Builder

	b.WriteString("// Generated by Human compiler — do not edit\n\n")
	b.WriteString("import { BrowserRouter, Routes, Route } from 'react-router-dom';\n")

	// Determine theme provider wrapping
	provider := ""
	if app.Theme != nil && app.Theme.DesignSystem != "" {
		ds := themes.Registry(app.Theme.DesignSystem)
		if ds != nil {
			if fs, ok := ds.Frameworks["react"]; ok && fs.Provider != "" {
				provider = fs.Provider
				for _, imp := range fs.Imports {
					b.WriteString(imp + "\n")
				}
				// Import the theme config file
				switch app.Theme.DesignSystem {
				case "material", "chakra":
					b.WriteString("import theme from './theme';\n")
				case "ant":
					b.WriteString("import themeConfig from './theme';\n")
				}
			}
		}
	}

	// Import global styles
	if app.Theme != nil {
		b.WriteString("import './styles/global.css';\n")
	}

	// Import each page
	for _, page := range app.Pages {
		name := page.Name + "Page"
		fmt.Fprintf(&b, "import %s from './pages/%s';\n", name, name)
	}

	b.WriteString("\n")
	b.WriteString("export default function App() {\n")
	b.WriteString("  return (\n")

	// Open provider
	indent := "    "
	switch provider {
	case "ThemeProvider":
		if app.Theme.DesignSystem == "material" {
			b.WriteString("    <ThemeProvider theme={theme}>\n")
			b.WriteString("      <CssBaseline />\n")
			indent = "      "
		}
	case "ChakraProvider":
		b.WriteString("    <ChakraProvider theme={theme}>\n")
		indent = "      "
	case "ConfigProvider":
		b.WriteString("    <ConfigProvider theme={themeConfig}>\n")
		indent = "      "
	}

	fmt.Fprintf(&b, "%s<BrowserRouter>\n", indent)
	fmt.Fprintf(&b, "%s  <Routes>\n", indent)

	for _, page := range app.Pages {
		name := page.Name + "Page"
		path := routePath(page.Name)
		fmt.Fprintf(&b, "%s    <Route path=\"%s\" element={<%s />} />\n", indent, path, name)
	}

	fmt.Fprintf(&b, "%s  </Routes>\n", indent)
	fmt.Fprintf(&b, "%s</BrowserRouter>\n", indent)

	// Close provider
	switch provider {
	case "ThemeProvider":
		if app.Theme.DesignSystem == "material" {
			b.WriteString("    </ThemeProvider>\n")
		}
	case "ChakraProvider":
		b.WriteString("    </ChakraProvider>\n")
	case "ConfigProvider":
		b.WriteString("    </ConfigProvider>\n")
	}

	b.WriteString("  );\n")
	b.WriteString("}\n")

	return b.String()
}

// routePath converts a page name to a route path.
// "Home" → "/", others → "/<kebab-case>"
func routePath(name string) string {
	if strings.ToLower(name) == "home" {
		return "/"
	}
	return "/" + toKebabCase(name)
}
