package monitoring

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/barun-bash/human/internal/ir"
)

// Generator produces monitoring configuration files (Prometheus, Grafana,
// backend instrumentation) from Intent IR.
type Generator struct{}

// Generate writes monitoring configuration files to outputDir.
func (g Generator) Generate(app *ir.Application, outputDir string) error {
	files := map[string]string{
		filepath.Join(outputDir, "prometheus", "prometheus.yml"):     generatePrometheusConfig(app),
		filepath.Join(outputDir, "prometheus", "alerts.yml"):         generateAlertRules(app),
		filepath.Join(outputDir, "grafana", "provisioning", "datasources", "prometheus.yml"): generateGrafanaDatasource(),
		filepath.Join(outputDir, "grafana", "provisioning", "dashboards", "dashboards.yml"):  generateGrafanaDashboardProvisioning(),
		filepath.Join(outputDir, "grafana", "dashboards", "app.json"):                        generateGrafanaDashboard(app),
		filepath.Join(outputDir, "docker-compose.monitoring.yml"):                             generateMonitoringCompose(app),
	}

	// Backend instrumentation
	if isNodeBackend(app) {
		files[filepath.Join(outputDir, "instrumentation", "metrics.ts")] = generateNodeMetrics(app)
		files[filepath.Join(outputDir, "instrumentation", "middleware.ts")] = generateNodeMiddleware(app)
	} else if isPythonBackend(app) {
		files[filepath.Join(outputDir, "instrumentation", "metrics.py")] = generatePythonMetrics(app)
		files[filepath.Join(outputDir, "instrumentation", "middleware.py")] = generatePythonMiddleware(app)
	} else if isGoBackend(app) {
		files[filepath.Join(outputDir, "instrumentation", "metrics.go")] = generateGoMetrics(app)
		files[filepath.Join(outputDir, "instrumentation", "middleware.go")] = generateGoMiddleware(app)
	}

	for path, content := range files {
		if err := writeFile(path, content); err != nil {
			return err
		}
	}

	return nil
}

func writeFile(path, content string) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("creating directory %s: %w", dir, err)
	}
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		return fmt.Errorf("writing %s: %w", path, err)
	}
	return nil
}

// ── Stack Detection ──

func isNodeBackend(app *ir.Application) bool {
	if app.Config == nil || app.Config.Backend == "" {
		return true
	}
	return strings.Contains(strings.ToLower(app.Config.Backend), "node")
}

func isPythonBackend(app *ir.Application) bool {
	if app.Config == nil {
		return false
	}
	return strings.Contains(strings.ToLower(app.Config.Backend), "python")
}

func isGoBackend(app *ir.Application) bool {
	if app.Config == nil {
		return false
	}
	lower := strings.ToLower(app.Config.Backend)
	if lower == "go" || strings.HasPrefix(lower, "go ") {
		return true
	}
	for _, kw := range []string{"gin", "fiber", "golang"} {
		if strings.Contains(lower, kw) {
			return true
		}
	}
	return false
}

func appNameLower(app *ir.Application) string {
	if app.Name != "" {
		return strings.ToLower(strings.ReplaceAll(app.Name, " ", "-"))
	}
	return "app"
}

// ── Prometheus ──

func generatePrometheusConfig(app *ir.Application) string {
	var b strings.Builder
	name := appNameLower(app)

	b.WriteString("# Generated by Human compiler — Prometheus configuration\n\n")
	b.WriteString("global:\n")
	b.WriteString("  scrape_interval: 15s\n")
	b.WriteString("  evaluation_interval: 15s\n\n")

	b.WriteString("rule_files:\n")
	b.WriteString("  - alerts.yml\n\n")

	// Alertmanager (if alert rules exist)
	hasAlerts := false
	for _, m := range app.Monitoring {
		if m.Kind == "alert" {
			hasAlerts = true
			break
		}
	}
	if hasAlerts {
		b.WriteString("alerting:\n")
		b.WriteString("  alertmanagers:\n")
		b.WriteString("    - static_configs:\n")
		b.WriteString("        - targets:\n")
		b.WriteString("            - alertmanager:9093\n\n")
	}

	b.WriteString("scrape_configs:\n")

	// Prometheus self-monitoring
	b.WriteString("  - job_name: prometheus\n")
	b.WriteString("    static_configs:\n")
	b.WriteString("      - targets: [\"localhost:9090\"]\n\n")

	// Backend application
	port := "3000"
	b.WriteString(fmt.Sprintf("  - job_name: %s\n", name))
	b.WriteString("    metrics_path: /metrics\n")
	b.WriteString("    static_configs:\n")
	b.WriteString(fmt.Sprintf("      - targets: [\"%s-backend:%s\"]\n", name, port))
	b.WriteString("        labels:\n")
	b.WriteString(fmt.Sprintf("          app: %s\n", name))

	// Microservices
	if app.Architecture != nil && len(app.Architecture.Services) > 0 {
		for _, svc := range app.Architecture.Services {
			svcName := strings.ToLower(strings.ReplaceAll(svc.Name, " ", "-"))
			svcPort := svc.Port
			if svcPort == 0 {
				svcPort = 3000
			}
			b.WriteString(fmt.Sprintf("\n  - job_name: %s\n", svcName))
			b.WriteString("    metrics_path: /metrics\n")
			b.WriteString("    static_configs:\n")
			b.WriteString(fmt.Sprintf("      - targets: [\"%s:%d\"]\n", svcName, svcPort))
			b.WriteString("        labels:\n")
			b.WriteString(fmt.Sprintf("          app: %s\n", name))
			b.WriteString(fmt.Sprintf("          service: %s\n", svcName))
		}
	}

	return b.String()
}

// ── Alert Rules ──

func generateAlertRules(app *ir.Application) string {
	var b strings.Builder

	b.WriteString("# Generated by Human compiler — Prometheus alert rules\n\n")
	b.WriteString("groups:\n")
	b.WriteString("  - name: app_alerts\n")
	b.WriteString("    rules:\n")

	// Default alerts
	b.WriteString("      - alert: HighErrorRate\n")
	b.WriteString("        expr: rate(http_requests_total{status=~\"5..\"}[5m]) / rate(http_requests_total[5m]) > 0.05\n")
	b.WriteString("        for: 5m\n")
	b.WriteString("        labels:\n")
	b.WriteString("          severity: critical\n")
	b.WriteString("        annotations:\n")
	b.WriteString("          summary: \"High error rate detected\"\n")
	b.WriteString("          description: \"More than 5% of requests are failing.\"\n\n")

	b.WriteString("      - alert: HighLatency\n")
	b.WriteString("        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1\n")
	b.WriteString("        for: 5m\n")
	b.WriteString("        labels:\n")
	b.WriteString("          severity: warning\n")
	b.WriteString("        annotations:\n")
	b.WriteString("          summary: \"High latency detected\"\n")
	b.WriteString("          description: \"p95 latency is above 1 second.\"\n\n")

	b.WriteString("      - alert: ServiceDown\n")
	b.WriteString("        expr: up == 0\n")
	b.WriteString("        for: 1m\n")
	b.WriteString("        labels:\n")
	b.WriteString("          severity: critical\n")
	b.WriteString("        annotations:\n")
	b.WriteString("          summary: \"Service is down\"\n")
	b.WriteString("          description: \"{{ $labels.job }} has been down for more than 1 minute.\"\n")

	// User-defined alerts from monitoring rules
	for _, m := range app.Monitoring {
		if m.Kind == "alert" && m.Condition != "" {
			alertName := sanitizeAlertName(m.Condition)
			b.WriteString(fmt.Sprintf("\n      - alert: %s\n", alertName))
			b.WriteString(fmt.Sprintf("        expr: %s\n", conditionToPromQL(m.Condition)))
			b.WriteString("        for: 5m\n")
			b.WriteString("        labels:\n")
			b.WriteString("          severity: warning\n")
			b.WriteString("        annotations:\n")
			b.WriteString(fmt.Sprintf("          summary: \"%s\"\n", m.Condition))
			if m.Channel != "" {
				b.WriteString(fmt.Sprintf("          channel: \"%s\"\n", m.Channel))
			}
		}
	}

	return b.String()
}

func sanitizeAlertName(condition string) string {
	words := strings.Fields(condition)
	var parts []string
	for _, w := range words {
		w = strings.Map(func(r rune) rune {
			if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') {
				return r
			}
			return -1
		}, w)
		if w != "" {
			parts = append(parts, strings.Title(w))
		}
	}
	if len(parts) == 0 {
		return "CustomAlert"
	}
	return strings.Join(parts, "")
}

func conditionToPromQL(condition string) string {
	lower := strings.ToLower(condition)
	switch {
	case strings.Contains(lower, "error rate") && strings.Contains(lower, "above"):
		return "rate(http_requests_total{status=~\"5..\"}[5m]) / rate(http_requests_total[5m]) > 0.05"
	case strings.Contains(lower, "response time") || strings.Contains(lower, "latency"):
		return "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1"
	case strings.Contains(lower, "cpu") && strings.Contains(lower, "above"):
		return "process_cpu_seconds_total > 0.8"
	case strings.Contains(lower, "memory") && strings.Contains(lower, "above"):
		return "process_resident_memory_bytes / 1024 / 1024 > 512"
	case strings.Contains(lower, "disk"):
		return "node_filesystem_avail_bytes / node_filesystem_size_bytes < 0.1"
	default:
		return fmt.Sprintf("# TODO: translate condition to PromQL: %s\nup == 0", condition)
	}
}

// ── Grafana ──

func generateGrafanaDatasource() string {
	var b strings.Builder

	b.WriteString("# Generated by Human compiler\n")
	b.WriteString("apiVersion: 1\n\n")
	b.WriteString("datasources:\n")
	b.WriteString("  - name: Prometheus\n")
	b.WriteString("    type: prometheus\n")
	b.WriteString("    access: proxy\n")
	b.WriteString("    url: http://prometheus:9090\n")
	b.WriteString("    isDefault: true\n")

	return b.String()
}

func generateGrafanaDashboardProvisioning() string {
	var b strings.Builder

	b.WriteString("# Generated by Human compiler\n")
	b.WriteString("apiVersion: 1\n\n")
	b.WriteString("providers:\n")
	b.WriteString("  - name: default\n")
	b.WriteString("    folder: \"\"\n")
	b.WriteString("    type: file\n")
	b.WriteString("    options:\n")
	b.WriteString("      path: /var/lib/grafana/dashboards\n")

	return b.String()
}

func generateGrafanaDashboard(app *ir.Application) string {
	name := appNameLower(app)

	// Generate a minimal Grafana dashboard JSON
	panels := []string{
		// Request rate panel
		fmt.Sprintf(`{
      "title": "Request Rate",
      "type": "graph",
      "gridPos": {"h": 8, "w": 12, "x": 0, "y": 0},
      "targets": [{"expr": "rate(http_requests_total{app=\"%s\"}[5m])", "legendFormat": "{{method}} {{path}}"}]
    }`, name),
		// Error rate panel
		fmt.Sprintf(`{
      "title": "Error Rate",
      "type": "graph",
      "gridPos": {"h": 8, "w": 12, "x": 12, "y": 0},
      "targets": [{"expr": "rate(http_requests_total{app=\"%s\",status=~\"5..\"}[5m])", "legendFormat": "{{status}}"}]
    }`, name),
		// Latency panel
		fmt.Sprintf(`{
      "title": "Request Latency (p95)",
      "type": "graph",
      "gridPos": {"h": 8, "w": 12, "x": 0, "y": 8},
      "targets": [{"expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{app=\"%s\"}[5m]))", "legendFormat": "p95"}]
    }`, name),
		// Active connections
		fmt.Sprintf(`{
      "title": "Active Connections",
      "type": "stat",
      "gridPos": {"h": 8, "w": 12, "x": 12, "y": 8},
      "targets": [{"expr": "http_active_connections{app=\"%s\"}", "legendFormat": "connections"}]
    }`, name),
	}

	// Add custom metric panels from monitoring rules
	y := 16
	for _, m := range app.Monitoring {
		if m.Kind == "track" && m.Metric != "" {
			metricName := strings.ToLower(strings.ReplaceAll(m.Metric, " ", "_"))
			panel := fmt.Sprintf(`{
      "title": "%s",
      "type": "graph",
      "gridPos": {"h": 8, "w": 12, "x": 0, "y": %d},
      "targets": [{"expr": "%s{app=\"%s\"}", "legendFormat": "%s"}]
    }`, m.Metric, y, metricName, name, metricName)
			panels = append(panels, panel)
			y += 8
		}
	}

	return fmt.Sprintf(`{
  "dashboard": {
    "title": "%s Dashboard",
    "uid": "%s-dashboard",
    "timezone": "browser",
    "panels": [%s],
    "time": {"from": "now-1h", "to": "now"},
    "refresh": "10s"
  }
}`, app.Name, name, strings.Join(panels, ",\n    "))
}

// ── Docker Compose for Monitoring Stack ──

func generateMonitoringCompose(app *ir.Application) string {
	var b strings.Builder
	name := appNameLower(app)
	_ = name

	b.WriteString("# Generated by Human compiler — Monitoring Stack\n")
	b.WriteString("# Run with: docker compose -f docker-compose.monitoring.yml up -d\n\n")

	b.WriteString("services:\n")

	// Prometheus
	b.WriteString("  prometheus:\n")
	b.WriteString("    image: prom/prometheus:v2.50.0\n")
	b.WriteString("    ports:\n")
	b.WriteString("      - \"9090:9090\"\n")
	b.WriteString("    volumes:\n")
	b.WriteString("      - ./prometheus:/etc/prometheus\n")
	b.WriteString("      - prometheus_data:/prometheus\n")
	b.WriteString("    command:\n")
	b.WriteString("      - --config.file=/etc/prometheus/prometheus.yml\n")
	b.WriteString("      - --storage.tsdb.retention.time=30d\n")
	b.WriteString("    restart: unless-stopped\n\n")

	// Grafana
	b.WriteString("  grafana:\n")
	b.WriteString("    image: grafana/grafana:10.3.0\n")
	b.WriteString("    ports:\n")
	b.WriteString("      - \"3001:3000\"\n")
	b.WriteString("    volumes:\n")
	b.WriteString("      - ./grafana/provisioning:/etc/grafana/provisioning\n")
	b.WriteString("      - ./grafana/dashboards:/var/lib/grafana/dashboards\n")
	b.WriteString("      - grafana_data:/var/lib/grafana\n")
	b.WriteString("    environment:\n")
	b.WriteString("      - GF_SECURITY_ADMIN_PASSWORD=admin\n")
	b.WriteString("      - GF_USERS_ALLOW_SIGN_UP=false\n")
	b.WriteString("    restart: unless-stopped\n\n")

	// Alertmanager (if alerts exist)
	hasAlerts := false
	for _, m := range app.Monitoring {
		if m.Kind == "alert" {
			hasAlerts = true
			break
		}
	}
	if hasAlerts {
		b.WriteString("  alertmanager:\n")
		b.WriteString("    image: prom/alertmanager:v0.27.0\n")
		b.WriteString("    ports:\n")
		b.WriteString("      - \"9093:9093\"\n")
		b.WriteString("    restart: unless-stopped\n\n")
	}

	// Volumes
	b.WriteString("volumes:\n")
	b.WriteString("  prometheus_data:\n")
	b.WriteString("  grafana_data:\n")

	return b.String()
}

// ── Node.js Instrumentation ──

func generateNodeMetrics(app *ir.Application) string {
	var b strings.Builder

	b.WriteString("// Generated by Human compiler — Prometheus metrics for Node.js\n\n")
	b.WriteString("import { Registry, Counter, Histogram, Gauge, collectDefaultMetrics } from 'prom-client';\n\n")
	b.WriteString("export const register = new Registry();\n\n")
	b.WriteString("// Collect default Node.js metrics (memory, CPU, event loop)\n")
	b.WriteString("collectDefaultMetrics({ register });\n\n")

	b.WriteString("export const httpRequestsTotal = new Counter({\n")
	b.WriteString("  name: 'http_requests_total',\n")
	b.WriteString("  help: 'Total number of HTTP requests',\n")
	b.WriteString("  labelNames: ['method', 'path', 'status'],\n")
	b.WriteString("  registers: [register],\n")
	b.WriteString("});\n\n")

	b.WriteString("export const httpRequestDuration = new Histogram({\n")
	b.WriteString("  name: 'http_request_duration_seconds',\n")
	b.WriteString("  help: 'Duration of HTTP requests in seconds',\n")
	b.WriteString("  labelNames: ['method', 'path', 'status'],\n")
	b.WriteString("  buckets: [0.01, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10],\n")
	b.WriteString("  registers: [register],\n")
	b.WriteString("});\n\n")

	b.WriteString("export const httpActiveConnections = new Gauge({\n")
	b.WriteString("  name: 'http_active_connections',\n")
	b.WriteString("  help: 'Number of active HTTP connections',\n")
	b.WriteString("  registers: [register],\n")
	b.WriteString("});\n")

	// Custom metrics from monitoring rules
	for _, m := range app.Monitoring {
		if m.Kind == "track" && m.Metric != "" {
			metricName := strings.ToLower(strings.ReplaceAll(m.Metric, " ", "_"))
			b.WriteString(fmt.Sprintf("\nexport const %s = new Counter({\n", metricName))
			b.WriteString(fmt.Sprintf("  name: '%s',\n", metricName))
			b.WriteString(fmt.Sprintf("  help: '%s',\n", m.Metric))
			b.WriteString("  registers: [register],\n")
			b.WriteString("});\n")
		}
	}

	return b.String()
}

func generateNodeMiddleware(app *ir.Application) string {
	var b strings.Builder

	b.WriteString("// Generated by Human compiler — Prometheus metrics middleware\n\n")
	b.WriteString("import { Request, Response, NextFunction } from 'express';\n")
	b.WriteString("import { register, httpRequestsTotal, httpRequestDuration, httpActiveConnections } from './metrics';\n\n")

	b.WriteString("export function metricsMiddleware(req: Request, res: Response, next: NextFunction): void {\n")
	b.WriteString("  httpActiveConnections.inc();\n")
	b.WriteString("  const start = process.hrtime.bigint();\n\n")
	b.WriteString("  res.on('finish', () => {\n")
	b.WriteString("    httpActiveConnections.dec();\n")
	b.WriteString("    const duration = Number(process.hrtime.bigint() - start) / 1e9;\n")
	b.WriteString("    const labels = { method: req.method, path: req.route?.path || req.path, status: String(res.statusCode) };\n")
	b.WriteString("    httpRequestsTotal.inc(labels);\n")
	b.WriteString("    httpRequestDuration.observe(labels, duration);\n")
	b.WriteString("  });\n\n")
	b.WriteString("  next();\n")
	b.WriteString("}\n\n")

	b.WriteString("export async function metricsEndpoint(_req: Request, res: Response): Promise<void> {\n")
	b.WriteString("  res.set('Content-Type', register.contentType);\n")
	b.WriteString("  res.end(await register.metrics());\n")
	b.WriteString("}\n")

	return b.String()
}

// ── Python Instrumentation ──

func generatePythonMetrics(app *ir.Application) string {
	var b strings.Builder

	b.WriteString("# Generated by Human compiler — Prometheus metrics for Python\n\n")
	b.WriteString("from prometheus_client import Counter, Histogram, Gauge, CollectorRegistry, generate_latest\n\n")
	b.WriteString("registry = CollectorRegistry()\n\n")

	b.WriteString("http_requests_total = Counter(\n")
	b.WriteString("    'http_requests_total',\n")
	b.WriteString("    'Total number of HTTP requests',\n")
	b.WriteString("    ['method', 'path', 'status'],\n")
	b.WriteString("    registry=registry,\n")
	b.WriteString(")\n\n")

	b.WriteString("http_request_duration = Histogram(\n")
	b.WriteString("    'http_request_duration_seconds',\n")
	b.WriteString("    'Duration of HTTP requests in seconds',\n")
	b.WriteString("    ['method', 'path', 'status'],\n")
	b.WriteString("    buckets=[0.01, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10],\n")
	b.WriteString("    registry=registry,\n")
	b.WriteString(")\n\n")

	b.WriteString("http_active_connections = Gauge(\n")
	b.WriteString("    'http_active_connections',\n")
	b.WriteString("    'Number of active HTTP connections',\n")
	b.WriteString("    registry=registry,\n")
	b.WriteString(")\n")

	for _, m := range app.Monitoring {
		if m.Kind == "track" && m.Metric != "" {
			metricName := strings.ToLower(strings.ReplaceAll(m.Metric, " ", "_"))
			b.WriteString(fmt.Sprintf("\n%s = Counter(\n", metricName))
			b.WriteString(fmt.Sprintf("    '%s',\n", metricName))
			b.WriteString(fmt.Sprintf("    '%s',\n", m.Metric))
			b.WriteString("    registry=registry,\n")
			b.WriteString(")\n")
		}
	}

	return b.String()
}

func generatePythonMiddleware(app *ir.Application) string {
	var b strings.Builder
	_ = app

	b.WriteString("# Generated by Human compiler — Prometheus metrics middleware\n\n")
	b.WriteString("import time\n")
	b.WriteString("from .metrics import http_requests_total, http_request_duration, http_active_connections, registry\n")
	b.WriteString("from prometheus_client import generate_latest\n\n")

	b.WriteString("class MetricsMiddleware:\n")
	b.WriteString("    def __init__(self, app):\n")
	b.WriteString("        self.app = app\n\n")
	b.WriteString("    async def __call__(self, scope, receive, send):\n")
	b.WriteString("        if scope['type'] != 'http':\n")
	b.WriteString("            await self.app(scope, receive, send)\n")
	b.WriteString("            return\n\n")
	b.WriteString("        http_active_connections.inc()\n")
	b.WriteString("        start = time.time()\n")
	b.WriteString("        status_code = 500\n\n")
	b.WriteString("        async def send_wrapper(message):\n")
	b.WriteString("            nonlocal status_code\n")
	b.WriteString("            if message['type'] == 'http.response.start':\n")
	b.WriteString("                status_code = message['status']\n")
	b.WriteString("            await send(message)\n\n")
	b.WriteString("        try:\n")
	b.WriteString("            await self.app(scope, receive, send_wrapper)\n")
	b.WriteString("        finally:\n")
	b.WriteString("            http_active_connections.dec()\n")
	b.WriteString("            duration = time.time() - start\n")
	b.WriteString("            method = scope.get('method', 'UNKNOWN')\n")
	b.WriteString("            path = scope.get('path', '/')\n")
	b.WriteString("            labels = {'method': method, 'path': path, 'status': str(status_code)}\n")
	b.WriteString("            http_requests_total.labels(**labels).inc()\n")
	b.WriteString("            http_request_duration.labels(**labels).observe(duration)\n\n")

	b.WriteString("def metrics_endpoint(request):\n")
	b.WriteString("    from starlette.responses import Response\n")
	b.WriteString("    return Response(generate_latest(registry), media_type='text/plain')\n")

	return b.String()
}

// ── Go Instrumentation ──

func generateGoMetrics(app *ir.Application) string {
	var b strings.Builder

	b.WriteString("// Generated by Human compiler — Prometheus metrics for Go\n")
	b.WriteString("package instrumentation\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"github.com/prometheus/client_golang/prometheus\"\n")
	b.WriteString("\t\"github.com/prometheus/client_golang/prometheus/promauto\"\n")
	b.WriteString(")\n\n")

	b.WriteString("var (\n")
	b.WriteString("\tHTTPRequestsTotal = promauto.NewCounterVec(prometheus.CounterOpts{\n")
	b.WriteString("\t\tName: \"http_requests_total\",\n")
	b.WriteString("\t\tHelp: \"Total number of HTTP requests\",\n")
	b.WriteString("\t}, []string{\"method\", \"path\", \"status\"})\n\n")

	b.WriteString("\tHTTPRequestDuration = promauto.NewHistogramVec(prometheus.HistogramOpts{\n")
	b.WriteString("\t\tName:    \"http_request_duration_seconds\",\n")
	b.WriteString("\t\tHelp:    \"Duration of HTTP requests in seconds\",\n")
	b.WriteString("\t\tBuckets: prometheus.DefBuckets,\n")
	b.WriteString("\t}, []string{\"method\", \"path\", \"status\"})\n\n")

	b.WriteString("\tHTTPActiveConnections = promauto.NewGauge(prometheus.GaugeOpts{\n")
	b.WriteString("\t\tName: \"http_active_connections\",\n")
	b.WriteString("\t\tHelp: \"Number of active HTTP connections\",\n")
	b.WriteString("\t})\n")

	for _, m := range app.Monitoring {
		if m.Kind == "track" && m.Metric != "" {
			metricName := strings.ToLower(strings.ReplaceAll(m.Metric, " ", "_"))
			varName := strings.Title(strings.ReplaceAll(m.Metric, " ", ""))
			b.WriteString(fmt.Sprintf("\n\t%s = promauto.NewCounter(prometheus.CounterOpts{\n", varName))
			b.WriteString(fmt.Sprintf("\t\tName: \"%s\",\n", metricName))
			b.WriteString(fmt.Sprintf("\t\tHelp: \"%s\",\n", m.Metric))
			b.WriteString("\t})\n")
		}
	}

	b.WriteString(")\n")

	return b.String()
}

func generateGoMiddleware(app *ir.Application) string {
	var b strings.Builder
	_ = app

	b.WriteString("// Generated by Human compiler — Prometheus metrics middleware\n")
	b.WriteString("package instrumentation\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"net/http\"\n")
	b.WriteString("\t\"strconv\"\n")
	b.WriteString("\t\"time\"\n\n")
	b.WriteString("\t\"github.com/prometheus/client_golang/prometheus/promhttp\"\n")
	b.WriteString(")\n\n")

	b.WriteString("// MetricsMiddleware records request metrics for Prometheus.\n")
	b.WriteString("func MetricsMiddleware(next http.Handler) http.Handler {\n")
	b.WriteString("\treturn http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {\n")
	b.WriteString("\t\tHTTPActiveConnections.Inc()\n")
	b.WriteString("\t\tdefer HTTPActiveConnections.Dec()\n\n")
	b.WriteString("\t\tstart := time.Now()\n")
	b.WriteString("\t\trw := &responseWriter{ResponseWriter: w, statusCode: http.StatusOK}\n")
	b.WriteString("\t\tnext.ServeHTTP(rw, r)\n\n")
	b.WriteString("\t\tduration := time.Since(start).Seconds()\n")
	b.WriteString("\t\tlabels := []string{r.Method, r.URL.Path, strconv.Itoa(rw.statusCode)}\n")
	b.WriteString("\t\tHTTPRequestsTotal.WithLabelValues(labels...).Inc()\n")
	b.WriteString("\t\tHTTPRequestDuration.WithLabelValues(labels...).Observe(duration)\n")
	b.WriteString("\t})\n")
	b.WriteString("}\n\n")

	b.WriteString("type responseWriter struct {\n")
	b.WriteString("\thttp.ResponseWriter\n")
	b.WriteString("\tstatusCode int\n")
	b.WriteString("}\n\n")

	b.WriteString("func (rw *responseWriter) WriteHeader(code int) {\n")
	b.WriteString("\trw.statusCode = code\n")
	b.WriteString("\trw.ResponseWriter.WriteHeader(code)\n")
	b.WriteString("}\n\n")

	b.WriteString("// MetricsHandler returns the Prometheus metrics HTTP handler.\n")
	b.WriteString("func MetricsHandler() http.Handler {\n")
	b.WriteString("\treturn promhttp.Handler()\n")
	b.WriteString("}\n")

	return b.String()
}
