package terraform

import (
	"fmt"
	"strings"

	"github.com/barun-bash/human/internal/ir"
)

// ── AWS ECS Fargate ──

func generateAWSECS(app *ir.Application) string {
	var b strings.Builder
	name := appNameLower(app)

	b.WriteString("# Generated by Human compiler — AWS ECS Fargate\n\n")

	// ECR Repository
	b.WriteString("resource \"aws_ecr_repository\" \"app\" {\n")
	b.WriteString(fmt.Sprintf("  name                 = \"%s\"\n", name))
	b.WriteString("  image_tag_mutability = \"MUTABLE\"\n\n")
	b.WriteString("  image_scanning_configuration {\n")
	b.WriteString("    scan_on_push = true\n")
	b.WriteString("  }\n")
	b.WriteString("}\n\n")

	// ECS Cluster
	b.WriteString("resource \"aws_ecs_cluster\" \"main\" {\n")
	b.WriteString(fmt.Sprintf("  name = \"%s-${var.environment}\"\n\n", name))
	b.WriteString("  setting {\n")
	b.WriteString("    name  = \"containerInsights\"\n")
	b.WriteString("    value = \"enabled\"\n")
	b.WriteString("  }\n")
	b.WriteString("}\n\n")

	// CloudWatch Log Group
	b.WriteString("resource \"aws_cloudwatch_log_group\" \"app\" {\n")
	b.WriteString(fmt.Sprintf("  name              = \"/ecs/%s-${var.environment}\"\n", name))
	b.WriteString("  retention_in_days = 30\n")
	b.WriteString("}\n\n")

	// IAM Role for ECS Task Execution
	b.WriteString("resource \"aws_iam_role\" \"ecs_task_execution\" {\n")
	b.WriteString(fmt.Sprintf("  name = \"%s-ecs-execution-${var.environment}\"\n\n", name))
	b.WriteString("  assume_role_policy = jsonencode({\n")
	b.WriteString("    Version = \"2012-10-17\"\n")
	b.WriteString("    Statement = [{\n")
	b.WriteString("      Action = \"sts:AssumeRole\"\n")
	b.WriteString("      Effect = \"Allow\"\n")
	b.WriteString("      Principal = {\n")
	b.WriteString("        Service = \"ecs-tasks.amazonaws.com\"\n")
	b.WriteString("      }\n")
	b.WriteString("    }]\n")
	b.WriteString("  })\n")
	b.WriteString("}\n\n")

	b.WriteString("resource \"aws_iam_role_policy_attachment\" \"ecs_task_execution\" {\n")
	b.WriteString("  role       = aws_iam_role.ecs_task_execution.name\n")
	b.WriteString("  policy_arn = \"arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy\"\n")
	b.WriteString("}\n\n")

	// Task Definition
	b.WriteString("resource \"aws_ecs_task_definition\" \"app\" {\n")
	b.WriteString(fmt.Sprintf("  family                   = \"%s-${var.environment}\"\n", name))
	b.WriteString("  network_mode             = \"awsvpc\"\n")
	b.WriteString("  requires_compatibilities = [\"FARGATE\"]\n")
	b.WriteString("  cpu                      = var.cpu\n")
	b.WriteString("  memory                   = var.memory\n")
	b.WriteString("  execution_role_arn       = aws_iam_role.ecs_task_execution.arn\n\n")

	b.WriteString("  container_definitions = jsonencode([{\n")
	b.WriteString(fmt.Sprintf("    name  = \"%s\"\n", name))
	b.WriteString(fmt.Sprintf("    image = \"${aws_ecr_repository.app.repository_url}:latest\"\n"))
	b.WriteString("    portMappings = [{\n")
	b.WriteString("      containerPort = var.container_port\n")
	b.WriteString("      protocol      = \"tcp\"\n")
	b.WriteString("    }]\n")
	b.WriteString("    environment = [\n")
	b.WriteString(fmt.Sprintf("      { name = \"%s\", value = var.environment },\n", envVarName(app)))
	b.WriteString("      { name = \"PORT\", value = tostring(var.container_port) },\n")

	if hasDatabase(app) {
		scheme := "postgresql"
		if isMySQL(app) {
			scheme = "mysql"
		}
		b.WriteString(fmt.Sprintf("      { name = \"DATABASE_URL\", value = \"%s://${var.db_username}:${var.db_password}@${aws_db_instance.main.endpoint}/%s\" },\n", scheme, appNameSnake(app)))
	}

	b.WriteString("    ]\n")
	b.WriteString("    logConfiguration = {\n")
	b.WriteString("      logDriver = \"awslogs\"\n")
	b.WriteString("      options = {\n")
	b.WriteString(fmt.Sprintf("        \"awslogs-group\"         = aws_cloudwatch_log_group.app.name\n"))
	b.WriteString("        \"awslogs-region\"        = var.aws_region\n")
	b.WriteString(fmt.Sprintf("        \"awslogs-stream-prefix\" = \"%s\"\n", name))
	b.WriteString("      }\n")
	b.WriteString("    }\n")
	b.WriteString("  }])\n")
	b.WriteString("}\n\n")

	// ECS Service
	b.WriteString("resource \"aws_ecs_service\" \"app\" {\n")
	b.WriteString(fmt.Sprintf("  name            = \"%s-${var.environment}\"\n", name))
	b.WriteString("  cluster         = aws_ecs_cluster.main.id\n")
	b.WriteString("  task_definition = aws_ecs_task_definition.app.arn\n")
	b.WriteString("  desired_count   = var.desired_count\n")
	b.WriteString("  launch_type     = \"FARGATE\"\n\n")
	b.WriteString("  network_configuration {\n")
	b.WriteString("    subnets          = aws_subnet.private[*].id\n")
	b.WriteString("    security_groups  = [aws_security_group.ecs.id]\n")
	b.WriteString("    assign_public_ip = false\n")
	b.WriteString("  }\n\n")
	b.WriteString("  load_balancer {\n")
	b.WriteString("    target_group_arn = aws_lb_target_group.app.arn\n")
	b.WriteString(fmt.Sprintf("    container_name   = \"%s\"\n", name))
	b.WriteString("    container_port   = var.container_port\n")
	b.WriteString("  }\n\n")
	b.WriteString("  depends_on = [aws_lb_listener.http]\n")
	b.WriteString("}\n")

	return b.String()
}

// ── AWS RDS ──

func generateAWSRDS(app *ir.Application) string {
	var b strings.Builder
	name := appNameLower(app)

	b.WriteString("# Generated by Human compiler — AWS RDS\n\n")

	if !hasDatabase(app) {
		b.WriteString("# No database configured — skipping RDS resources.\n")
		return b.String()
	}

	engine := "postgres"
	engineVersion := "16"
	port := "5432"
	if isMySQL(app) {
		engine = "mysql"
		engineVersion = "8.0"
		port = "3306"
	}

	// Security group for RDS
	b.WriteString("resource \"aws_security_group\" \"rds\" {\n")
	b.WriteString(fmt.Sprintf("  name   = \"%s-rds-${var.environment}\"\n", name))
	b.WriteString("  vpc_id = aws_vpc.main.id\n\n")
	b.WriteString("  ingress {\n")
	b.WriteString(fmt.Sprintf("    from_port       = %s\n", port))
	b.WriteString(fmt.Sprintf("    to_port         = %s\n", port))
	b.WriteString("    protocol        = \"tcp\"\n")
	b.WriteString("    security_groups = [aws_security_group.ecs.id]\n")
	b.WriteString("  }\n")
	b.WriteString("}\n\n")

	// Subnet group
	b.WriteString("resource \"aws_db_subnet_group\" \"main\" {\n")
	b.WriteString(fmt.Sprintf("  name       = \"%s-${var.environment}\"\n", name))
	b.WriteString("  subnet_ids = aws_subnet.private[*].id\n")
	b.WriteString("}\n\n")

	// RDS instance
	b.WriteString("resource \"aws_db_instance\" \"main\" {\n")
	b.WriteString(fmt.Sprintf("  identifier     = \"%s-${var.environment}\"\n", name))
	b.WriteString(fmt.Sprintf("  engine         = \"%s\"\n", engine))
	b.WriteString(fmt.Sprintf("  engine_version = \"%s\"\n", engineVersion))
	b.WriteString("  instance_class = var.db_instance_class\n\n")
	b.WriteString("  allocated_storage     = 20\n")
	b.WriteString("  max_allocated_storage = 100\n\n")
	b.WriteString(fmt.Sprintf("  db_name  = \"%s\"\n", appNameSnake(app)))
	b.WriteString("  username = var.db_username\n")
	b.WriteString("  password = var.db_password\n\n")
	b.WriteString("  vpc_security_group_ids = [aws_security_group.rds.id]\n")
	b.WriteString("  db_subnet_group_name   = aws_db_subnet_group.main.name\n\n")
	b.WriteString("  skip_final_snapshot = true\n")
	b.WriteString("  multi_az            = var.environment == \"production\" ? true : false\n\n")
	b.WriteString("  backup_retention_period = var.environment == \"production\" ? 7 : 1\n")
	b.WriteString("}\n")

	return b.String()
}

// ── AWS Networking (VPC, Subnets, ALB) ──

func generateAWSNetworking(app *ir.Application) string {
	var b strings.Builder
	name := appNameLower(app)

	b.WriteString("# Generated by Human compiler — AWS Networking\n\n")

	// VPC
	b.WriteString("resource \"aws_vpc\" \"main\" {\n")
	b.WriteString("  cidr_block           = \"10.0.0.0/16\"\n")
	b.WriteString("  enable_dns_hostnames = true\n")
	b.WriteString("  enable_dns_support   = true\n\n")
	b.WriteString("  tags = {\n")
	b.WriteString(fmt.Sprintf("    Name = \"%s-${var.environment}\"\n", name))
	b.WriteString("  }\n")
	b.WriteString("}\n\n")

	// Internet Gateway
	b.WriteString("resource \"aws_internet_gateway\" \"main\" {\n")
	b.WriteString("  vpc_id = aws_vpc.main.id\n")
	b.WriteString("}\n\n")

	// Public subnets (2 AZs)
	b.WriteString("data \"aws_availability_zones\" \"available\" {\n")
	b.WriteString("  state = \"available\"\n")
	b.WriteString("}\n\n")

	b.WriteString("resource \"aws_subnet\" \"public\" {\n")
	b.WriteString("  count             = 2\n")
	b.WriteString("  vpc_id            = aws_vpc.main.id\n")
	b.WriteString("  cidr_block        = cidrsubnet(aws_vpc.main.cidr_block, 8, count.index)\n")
	b.WriteString("  availability_zone = data.aws_availability_zones.available.names[count.index]\n\n")
	b.WriteString("  map_public_ip_on_launch = true\n\n")
	b.WriteString("  tags = {\n")
	b.WriteString(fmt.Sprintf("    Name = \"%s-public-${count.index}\"\n", name))
	b.WriteString("  }\n")
	b.WriteString("}\n\n")

	// Private subnets
	b.WriteString("resource \"aws_subnet\" \"private\" {\n")
	b.WriteString("  count             = 2\n")
	b.WriteString("  vpc_id            = aws_vpc.main.id\n")
	b.WriteString("  cidr_block        = cidrsubnet(aws_vpc.main.cidr_block, 8, count.index + 10)\n")
	b.WriteString("  availability_zone = data.aws_availability_zones.available.names[count.index]\n\n")
	b.WriteString("  tags = {\n")
	b.WriteString(fmt.Sprintf("    Name = \"%s-private-${count.index}\"\n", name))
	b.WriteString("  }\n")
	b.WriteString("}\n\n")

	// NAT Gateway
	b.WriteString("resource \"aws_eip\" \"nat\" {\n")
	b.WriteString("  domain = \"vpc\"\n")
	b.WriteString("}\n\n")

	b.WriteString("resource \"aws_nat_gateway\" \"main\" {\n")
	b.WriteString("  allocation_id = aws_eip.nat.id\n")
	b.WriteString("  subnet_id     = aws_subnet.public[0].id\n")
	b.WriteString("}\n\n")

	// Route tables
	b.WriteString("resource \"aws_route_table\" \"public\" {\n")
	b.WriteString("  vpc_id = aws_vpc.main.id\n\n")
	b.WriteString("  route {\n")
	b.WriteString("    cidr_block = \"0.0.0.0/0\"\n")
	b.WriteString("    gateway_id = aws_internet_gateway.main.id\n")
	b.WriteString("  }\n")
	b.WriteString("}\n\n")

	b.WriteString("resource \"aws_route_table_association\" \"public\" {\n")
	b.WriteString("  count          = 2\n")
	b.WriteString("  subnet_id      = aws_subnet.public[count.index].id\n")
	b.WriteString("  route_table_id = aws_route_table.public.id\n")
	b.WriteString("}\n\n")

	b.WriteString("resource \"aws_route_table\" \"private\" {\n")
	b.WriteString("  vpc_id = aws_vpc.main.id\n\n")
	b.WriteString("  route {\n")
	b.WriteString("    cidr_block     = \"0.0.0.0/0\"\n")
	b.WriteString("    nat_gateway_id = aws_nat_gateway.main.id\n")
	b.WriteString("  }\n")
	b.WriteString("}\n\n")

	b.WriteString("resource \"aws_route_table_association\" \"private\" {\n")
	b.WriteString("  count          = 2\n")
	b.WriteString("  subnet_id      = aws_subnet.private[count.index].id\n")
	b.WriteString("  route_table_id = aws_route_table.private.id\n")
	b.WriteString("}\n\n")

	// ECS security group
	b.WriteString("resource \"aws_security_group\" \"ecs\" {\n")
	b.WriteString(fmt.Sprintf("  name   = \"%s-ecs-${var.environment}\"\n", name))
	b.WriteString("  vpc_id = aws_vpc.main.id\n\n")
	b.WriteString("  ingress {\n")
	b.WriteString("    from_port       = var.container_port\n")
	b.WriteString("    to_port         = var.container_port\n")
	b.WriteString("    protocol        = \"tcp\"\n")
	b.WriteString("    security_groups = [aws_security_group.alb.id]\n")
	b.WriteString("  }\n\n")
	b.WriteString("  egress {\n")
	b.WriteString("    from_port   = 0\n")
	b.WriteString("    to_port     = 0\n")
	b.WriteString("    protocol    = \"-1\"\n")
	b.WriteString("    cidr_blocks = [\"0.0.0.0/0\"]\n")
	b.WriteString("  }\n")
	b.WriteString("}\n\n")

	// ALB
	b.WriteString("resource \"aws_security_group\" \"alb\" {\n")
	b.WriteString(fmt.Sprintf("  name   = \"%s-alb-${var.environment}\"\n", name))
	b.WriteString("  vpc_id = aws_vpc.main.id\n\n")
	b.WriteString("  ingress {\n")
	b.WriteString("    from_port   = 80\n")
	b.WriteString("    to_port     = 80\n")
	b.WriteString("    protocol    = \"tcp\"\n")
	b.WriteString("    cidr_blocks = [\"0.0.0.0/0\"]\n")
	b.WriteString("  }\n\n")
	b.WriteString("  ingress {\n")
	b.WriteString("    from_port   = 443\n")
	b.WriteString("    to_port     = 443\n")
	b.WriteString("    protocol    = \"tcp\"\n")
	b.WriteString("    cidr_blocks = [\"0.0.0.0/0\"]\n")
	b.WriteString("  }\n\n")
	b.WriteString("  egress {\n")
	b.WriteString("    from_port   = 0\n")
	b.WriteString("    to_port     = 0\n")
	b.WriteString("    protocol    = \"-1\"\n")
	b.WriteString("    cidr_blocks = [\"0.0.0.0/0\"]\n")
	b.WriteString("  }\n")
	b.WriteString("}\n\n")

	b.WriteString("resource \"aws_lb\" \"main\" {\n")
	b.WriteString(fmt.Sprintf("  name               = \"%s-${var.environment}\"\n", name))
	b.WriteString("  internal           = false\n")
	b.WriteString("  load_balancer_type = \"application\"\n")
	b.WriteString("  security_groups    = [aws_security_group.alb.id]\n")
	b.WriteString("  subnets            = aws_subnet.public[*].id\n")
	b.WriteString("}\n\n")

	b.WriteString("resource \"aws_lb_target_group\" \"app\" {\n")
	b.WriteString(fmt.Sprintf("  name        = \"%s-${var.environment}\"\n", name))
	b.WriteString("  port        = var.container_port\n")
	b.WriteString("  protocol    = \"HTTP\"\n")
	b.WriteString("  vpc_id      = aws_vpc.main.id\n")
	b.WriteString("  target_type = \"ip\"\n\n")
	b.WriteString("  health_check {\n")
	b.WriteString("    path                = \"/health\"\n")
	b.WriteString("    healthy_threshold   = 2\n")
	b.WriteString("    unhealthy_threshold = 3\n")
	b.WriteString("    interval            = 30\n")
	b.WriteString("  }\n")
	b.WriteString("}\n\n")

	b.WriteString("resource \"aws_lb_listener\" \"http\" {\n")
	b.WriteString("  load_balancer_arn = aws_lb.main.arn\n")
	b.WriteString("  port             = 80\n")
	b.WriteString("  protocol         = \"HTTP\"\n\n")
	b.WriteString("  default_action {\n")
	b.WriteString("    type             = \"forward\"\n")
	b.WriteString("    target_group_arn = aws_lb_target_group.app.arn\n")
	b.WriteString("  }\n")
	b.WriteString("}\n")

	return b.String()
}

// ── AWS CloudFront + S3 for frontend ──

func generateAWSCDN(app *ir.Application) string {
	var b strings.Builder
	name := appNameLower(app)

	b.WriteString("# Generated by Human compiler — AWS CloudFront + S3\n\n")

	// S3 bucket for static assets
	b.WriteString("resource \"aws_s3_bucket\" \"frontend\" {\n")
	b.WriteString(fmt.Sprintf("  bucket = \"%s-frontend-${var.environment}\"\n", name))
	b.WriteString("}\n\n")

	b.WriteString("resource \"aws_s3_bucket_public_access_block\" \"frontend\" {\n")
	b.WriteString("  bucket = aws_s3_bucket.frontend.id\n\n")
	b.WriteString("  block_public_acls       = true\n")
	b.WriteString("  block_public_policy     = true\n")
	b.WriteString("  ignore_public_acls      = true\n")
	b.WriteString("  restrict_public_buckets = true\n")
	b.WriteString("}\n\n")

	// CloudFront OAC
	b.WriteString("resource \"aws_cloudfront_origin_access_control\" \"frontend\" {\n")
	b.WriteString(fmt.Sprintf("  name                              = \"%s-${var.environment}\"\n", name))
	b.WriteString("  origin_access_control_origin_type = \"s3\"\n")
	b.WriteString("  signing_behavior                  = \"always\"\n")
	b.WriteString("  signing_protocol                  = \"sigv4\"\n")
	b.WriteString("}\n\n")

	// CloudFront distribution
	b.WriteString("resource \"aws_cloudfront_distribution\" \"frontend\" {\n")
	b.WriteString("  enabled             = true\n")
	b.WriteString("  default_root_object = \"index.html\"\n\n")

	b.WriteString("  origin {\n")
	b.WriteString("    domain_name              = aws_s3_bucket.frontend.bucket_regional_domain_name\n")
	b.WriteString(fmt.Sprintf("    origin_id               = \"%s-s3\"\n", name))
	b.WriteString("    origin_access_control_id = aws_cloudfront_origin_access_control.frontend.id\n")
	b.WriteString("  }\n\n")

	b.WriteString("  default_cache_behavior {\n")
	b.WriteString(fmt.Sprintf("    target_origin_id       = \"%s-s3\"\n", name))
	b.WriteString("    viewer_protocol_policy = \"redirect-to-https\"\n")
	b.WriteString("    allowed_methods        = [\"GET\", \"HEAD\"]\n")
	b.WriteString("    cached_methods         = [\"GET\", \"HEAD\"]\n")
	b.WriteString("    compress               = true\n\n")
	b.WriteString("    forwarded_values {\n")
	b.WriteString("      query_string = false\n")
	b.WriteString("      cookies {\n")
	b.WriteString("        forward = \"none\"\n")
	b.WriteString("      }\n")
	b.WriteString("    }\n")
	b.WriteString("  }\n\n")

	// SPA fallback
	b.WriteString("  custom_error_response {\n")
	b.WriteString("    error_code         = 404\n")
	b.WriteString("    response_code      = 200\n")
	b.WriteString("    response_page_path = \"/index.html\"\n")
	b.WriteString("  }\n\n")

	b.WriteString("  restrictions {\n")
	b.WriteString("    geo_restriction {\n")
	b.WriteString("      restriction_type = \"none\"\n")
	b.WriteString("    }\n")
	b.WriteString("  }\n\n")

	b.WriteString("  viewer_certificate {\n")
	b.WriteString("    cloudfront_default_certificate = true\n")
	b.WriteString("  }\n")
	b.WriteString("}\n\n")

	// S3 bucket policy for CloudFront
	b.WriteString("resource \"aws_s3_bucket_policy\" \"frontend\" {\n")
	b.WriteString("  bucket = aws_s3_bucket.frontend.id\n\n")
	b.WriteString("  policy = jsonencode({\n")
	b.WriteString("    Version = \"2012-10-17\"\n")
	b.WriteString("    Statement = [{\n")
	b.WriteString("      Effect    = \"Allow\"\n")
	b.WriteString("      Principal = { Service = \"cloudfront.amazonaws.com\" }\n")
	b.WriteString("      Action    = \"s3:GetObject\"\n")
	b.WriteString("      Resource  = \"${aws_s3_bucket.frontend.arn}/*\"\n")
	b.WriteString("      Condition = {\n")
	b.WriteString("        StringEquals = {\n")
	b.WriteString("          \"AWS:SourceArn\" = aws_cloudfront_distribution.frontend.arn\n")
	b.WriteString("        }\n")
	b.WriteString("      }\n")
	b.WriteString("    }]\n")
	b.WriteString("  })\n")
	b.WriteString("}\n")

	return b.String()
}
