package terraform

import (
	"fmt"
	"strings"

	"github.com/barun-bash/human/internal/ir"
)

// generateDockerProd produces Terraform config for managing Docker containers
// in a production-like setup (self-hosted or VPS).
func generateDockerProd(app *ir.Application) string {
	var b strings.Builder
	name := appNameLower(app)

	b.WriteString("# Generated by Human compiler — Docker Production\n")
	b.WriteString("# Manages Docker containers via the Terraform Docker provider.\n\n")

	// Network
	b.WriteString("resource \"docker_network\" \"app\" {\n")
	b.WriteString(fmt.Sprintf("  name = \"%s-${var.environment}\"\n", name))
	b.WriteString("}\n\n")

	// Backend container
	b.WriteString("resource \"docker_image\" \"backend\" {\n")
	b.WriteString(fmt.Sprintf("  name = \"%s-backend:latest\"\n", name))
	b.WriteString("  build {\n")
	b.WriteString("    context = \"../node\"\n")
	b.WriteString("  }\n")
	b.WriteString("}\n\n")

	b.WriteString("resource \"docker_container\" \"backend\" {\n")
	b.WriteString(fmt.Sprintf("  name  = \"%s-backend-${var.environment}\"\n", name))
	b.WriteString("  image = docker_image.backend.image_id\n\n")
	b.WriteString("  ports {\n")
	b.WriteString("    internal = var.container_port\n")
	b.WriteString("    external = var.container_port\n")
	b.WriteString("  }\n\n")
	b.WriteString("  networks_advanced {\n")
	b.WriteString("    name = docker_network.app.name\n")
	b.WriteString("  }\n\n")
	b.WriteString("  env = [\n")
	b.WriteString("    \"NODE_ENV=${var.environment}\",\n")
	b.WriteString("    \"PORT=${var.container_port}\",\n")

	if hasDatabase(app) {
		db := dbEngine(app)
		port := "5432"
		user := "postgres"
		if db == "mysql" {
			port = "3306"
			user = "root"
		}
		b.WriteString(fmt.Sprintf("    \"DATABASE_URL=%s://%s:${var.db_password}@%s-db-${var.environment}:%s/%s\",\n",
			db, user, name, port, appNameSnake(app)))
	}

	b.WriteString("  ]\n\n")
	b.WriteString("  restart = \"unless-stopped\"\n")
	b.WriteString("}\n\n")

	// Database container
	if hasDatabase(app) {
		if isPostgres(app) {
			b.WriteString("resource \"docker_image\" \"db\" {\n")
			b.WriteString("  name = \"postgres:16-alpine\"\n")
			b.WriteString("}\n\n")

			b.WriteString("resource \"docker_container\" \"db\" {\n")
			b.WriteString(fmt.Sprintf("  name  = \"%s-db-${var.environment}\"\n", name))
			b.WriteString("  image = docker_image.db.image_id\n\n")
			b.WriteString("  networks_advanced {\n")
			b.WriteString("    name = docker_network.app.name\n")
			b.WriteString("  }\n\n")
			b.WriteString("  env = [\n")
			b.WriteString("    \"POSTGRES_PASSWORD=${var.db_password}\",\n")
			b.WriteString(fmt.Sprintf("    \"POSTGRES_DB=%s\",\n", appNameSnake(app)))
			b.WriteString("  ]\n\n")
			b.WriteString("  volumes {\n")
			b.WriteString(fmt.Sprintf("    volume_name    = \"%s-pgdata-${var.environment}\"\n", name))
			b.WriteString("    container_path = \"/var/lib/postgresql/data\"\n")
			b.WriteString("  }\n\n")
			b.WriteString("  restart = \"unless-stopped\"\n")
			b.WriteString("}\n\n")
		} else if isMySQL(app) {
			b.WriteString("resource \"docker_image\" \"db\" {\n")
			b.WriteString("  name = \"mysql:8\"\n")
			b.WriteString("}\n\n")

			b.WriteString("resource \"docker_container\" \"db\" {\n")
			b.WriteString(fmt.Sprintf("  name  = \"%s-db-${var.environment}\"\n", name))
			b.WriteString("  image = docker_image.db.image_id\n\n")
			b.WriteString("  networks_advanced {\n")
			b.WriteString("    name = docker_network.app.name\n")
			b.WriteString("  }\n\n")
			b.WriteString("  env = [\n")
			b.WriteString("    \"MYSQL_ROOT_PASSWORD=${var.db_password}\",\n")
			b.WriteString(fmt.Sprintf("    \"MYSQL_DATABASE=%s\",\n", appNameSnake(app)))
			b.WriteString("  ]\n\n")
			b.WriteString("  volumes {\n")
			b.WriteString(fmt.Sprintf("    volume_name    = \"%s-mysqldata-${var.environment}\"\n", name))
			b.WriteString("    container_path = \"/var/lib/mysql\"\n")
			b.WriteString("  }\n\n")
			b.WriteString("  restart = \"unless-stopped\"\n")
			b.WriteString("}\n\n")
		}

		// Volume
		b.WriteString("resource \"docker_volume\" \"db_data\" {\n")
		suffix := "pgdata"
		if isMySQL(app) {
			suffix = "mysqldata"
		}
		b.WriteString(fmt.Sprintf("  name = \"%s-%s-${var.environment}\"\n", name, suffix))
		b.WriteString("}\n")
	}

	return b.String()
}
