package terraform

import (
	"fmt"
	"strings"

	"github.com/barun-bash/human/internal/ir"
)

// ── GCP Cloud Run ──

func generateGCPCloudRun(app *ir.Application) string {
	var b strings.Builder
	name := appNameLower(app)

	b.WriteString("# Generated by Human compiler — GCP Cloud Run\n\n")

	// Enable required APIs
	b.WriteString("resource \"google_project_service\" \"run\" {\n")
	b.WriteString("  service            = \"run.googleapis.com\"\n")
	b.WriteString("  disable_on_destroy = false\n")
	b.WriteString("}\n\n")

	b.WriteString("resource \"google_project_service\" \"artifactregistry\" {\n")
	b.WriteString("  service            = \"artifactregistry.googleapis.com\"\n")
	b.WriteString("  disable_on_destroy = false\n")
	b.WriteString("}\n\n")

	// Artifact Registry
	b.WriteString("resource \"google_artifact_registry_repository\" \"app\" {\n")
	b.WriteString(fmt.Sprintf("  repository_id = \"%s\"\n", name))
	b.WriteString("  location      = var.gcp_region\n")
	b.WriteString("  format        = \"DOCKER\"\n\n")
	b.WriteString("  depends_on = [google_project_service.artifactregistry]\n")
	b.WriteString("}\n\n")

	// Cloud Run service
	b.WriteString("resource \"google_cloud_run_v2_service\" \"backend\" {\n")
	b.WriteString(fmt.Sprintf("  name     = \"%s-${var.environment}\"\n", name))
	b.WriteString("  location = var.gcp_region\n\n")
	b.WriteString("  template {\n")
	b.WriteString("    scaling {\n")
	b.WriteString("      min_instance_count = var.environment == \"production\" ? 1 : 0\n")
	b.WriteString("      max_instance_count = var.environment == \"production\" ? 10 : 3\n")
	b.WriteString("    }\n\n")
	b.WriteString("    containers {\n")
	b.WriteString(fmt.Sprintf("      image = \"%s-docker.pkg.dev/${var.gcp_project_id}/%s/%s:latest\"\n",
		"${var.gcp_region}", name, name))
	b.WriteString("\n")
	b.WriteString("      ports {\n")
	b.WriteString("        container_port = var.container_port\n")
	b.WriteString("      }\n\n")
	b.WriteString("      env {\n")
	b.WriteString("        name  = \"NODE_ENV\"\n")
	b.WriteString("        value = var.environment\n")
	b.WriteString("      }\n")
	b.WriteString("      env {\n")
	b.WriteString("        name  = \"PORT\"\n")
	b.WriteString("        value = tostring(var.container_port)\n")
	b.WriteString("      }\n")

	if hasDatabase(app) {
		b.WriteString("      env {\n")
		b.WriteString("        name  = \"DATABASE_URL\"\n")
		db := dbEngine(app)
		if db == "postgres" {
			b.WriteString(fmt.Sprintf("        value = \"postgresql://postgres:${var.db_password}@//cloudsql/${google_sql_database_instance.main.connection_name}/%s\"\n", appNameSnake(app)))
		} else {
			b.WriteString(fmt.Sprintf("        value = \"mysql://root:${var.db_password}@//cloudsql/${google_sql_database_instance.main.connection_name}/%s\"\n", appNameSnake(app)))
		}
		b.WriteString("      }\n\n")
		b.WriteString("      volume_mounts {\n")
		b.WriteString("        name       = \"cloudsql\"\n")
		b.WriteString("        mount_path = \"/cloudsql\"\n")
		b.WriteString("      }\n")
	}

	b.WriteString("    }\n")

	if hasDatabase(app) {
		b.WriteString("\n    volumes {\n")
		b.WriteString("      name = \"cloudsql\"\n")
		b.WriteString("      cloud_sql_instance {\n")
		b.WriteString("        instances = [google_sql_database_instance.main.connection_name]\n")
		b.WriteString("      }\n")
		b.WriteString("    }\n")
	}

	b.WriteString("  }\n\n")
	b.WriteString("  depends_on = [google_project_service.run]\n")
	b.WriteString("}\n\n")

	// Allow unauthenticated access
	b.WriteString("resource \"google_cloud_run_v2_service_iam_member\" \"public\" {\n")
	b.WriteString("  location = google_cloud_run_v2_service.backend.location\n")
	b.WriteString("  name     = google_cloud_run_v2_service.backend.name\n")
	b.WriteString("  role     = \"roles/run.invoker\"\n")
	b.WriteString("  member   = \"allUsers\"\n")
	b.WriteString("}\n")

	return b.String()
}

// ── GCP Cloud SQL ──

func generateGCPCloudSQL(app *ir.Application) string {
	var b strings.Builder
	name := appNameLower(app)

	b.WriteString("# Generated by Human compiler — GCP Cloud SQL\n\n")

	if !hasDatabase(app) {
		b.WriteString("# No database configured — skipping Cloud SQL resources.\n")
		return b.String()
	}

	// Enable SQL Admin API
	b.WriteString("resource \"google_project_service\" \"sqladmin\" {\n")
	b.WriteString("  service            = \"sqladmin.googleapis.com\"\n")
	b.WriteString("  disable_on_destroy = false\n")
	b.WriteString("}\n\n")

	dbVersion := "POSTGRES_16"
	if isMySQL(app) {
		dbVersion = "MYSQL_8_0"
	}

	b.WriteString("resource \"google_sql_database_instance\" \"main\" {\n")
	b.WriteString(fmt.Sprintf("  name             = \"%s-${var.environment}\"\n", name))
	b.WriteString(fmt.Sprintf("  database_version = \"%s\"\n", dbVersion))
	b.WriteString("  region           = var.gcp_region\n\n")
	b.WriteString("  settings {\n")
	b.WriteString("    tier = var.db_tier\n\n")
	b.WriteString("    backup_configuration {\n")
	b.WriteString("      enabled    = true\n")
	b.WriteString("      start_time = \"03:00\"\n")
	if isMySQL(app) {
		b.WriteString("      binary_log_enabled = true\n")
	}
	b.WriteString("    }\n\n")
	b.WriteString("    ip_configuration {\n")
	b.WriteString("      ipv4_enabled = true\n")
	b.WriteString("    }\n")
	b.WriteString("  }\n\n")
	b.WriteString("  deletion_protection = var.environment == \"production\" ? true : false\n\n")
	b.WriteString("  depends_on = [google_project_service.sqladmin]\n")
	b.WriteString("}\n\n")

	b.WriteString("resource \"google_sql_database\" \"main\" {\n")
	b.WriteString(fmt.Sprintf("  name     = \"%s\"\n", appNameSnake(app)))
	b.WriteString("  instance = google_sql_database_instance.main.name\n")
	b.WriteString("}\n\n")

	b.WriteString("resource \"google_sql_user\" \"main\" {\n")
	if isPostgres(app) {
		b.WriteString("  name     = \"postgres\"\n")
	} else {
		b.WriteString("  name     = \"root\"\n")
	}
	b.WriteString("  instance = google_sql_database_instance.main.name\n")
	b.WriteString("  password = var.db_password\n")
	b.WriteString("}\n")

	return b.String()
}

// ── GCP CDN (Cloud Storage + Load Balancer) ──

func generateGCPCDN(app *ir.Application) string {
	var b strings.Builder
	name := appNameLower(app)

	b.WriteString("# Generated by Human compiler — GCP Cloud Storage + CDN\n\n")

	// Storage bucket for frontend
	b.WriteString("resource \"google_storage_bucket\" \"frontend\" {\n")
	b.WriteString(fmt.Sprintf("  name     = \"%s-frontend-${var.environment}\"\n", name))
	b.WriteString("  location = var.gcp_region\n\n")
	b.WriteString("  website {\n")
	b.WriteString("    main_page_suffix = \"index.html\"\n")
	b.WriteString("    not_found_page   = \"index.html\"\n")
	b.WriteString("  }\n\n")
	b.WriteString("  uniform_bucket_level_access = true\n")
	b.WriteString("}\n\n")

	// Make bucket public
	b.WriteString("resource \"google_storage_bucket_iam_member\" \"public\" {\n")
	b.WriteString("  bucket = google_storage_bucket.frontend.name\n")
	b.WriteString("  role   = \"roles/storage.objectViewer\"\n")
	b.WriteString("  member = \"allUsers\"\n")
	b.WriteString("}\n")

	return b.String()
}
