package terraform

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/barun-bash/human/internal/ir"
)

// Generator produces Terraform infrastructure-as-code files from Intent IR.
type Generator struct{}

// Generate writes Terraform configuration files to outputDir based on the
// application's deploy target (AWS, GCP, or Docker production).
func (g Generator) Generate(app *ir.Application, outputDir string) error {
	files := make(map[string]string)

	target := deployTarget(app)

	// Common files
	files[filepath.Join(outputDir, "main.tf")] = generateMainTF(app, target)
	files[filepath.Join(outputDir, "variables.tf")] = generateVariablesTF(app, target)
	files[filepath.Join(outputDir, "outputs.tf")] = generateOutputsTF(app, target)
	files[filepath.Join(outputDir, "terraform.tfvars.example")] = generateTFVarsExample(app, target)

	// Provider-specific files
	switch target {
	case "aws":
		files[filepath.Join(outputDir, "aws_ecs.tf")] = generateAWSECS(app)
		files[filepath.Join(outputDir, "aws_rds.tf")] = generateAWSRDS(app)
		files[filepath.Join(outputDir, "aws_networking.tf")] = generateAWSNetworking(app)
		if hasFrontend(app) {
			files[filepath.Join(outputDir, "aws_cdn.tf")] = generateAWSCDN(app)
		}
	case "gcp":
		files[filepath.Join(outputDir, "gcp_cloudrun.tf")] = generateGCPCloudRun(app)
		files[filepath.Join(outputDir, "gcp_cloudsql.tf")] = generateGCPCloudSQL(app)
		if hasFrontend(app) {
			files[filepath.Join(outputDir, "gcp_cdn.tf")] = generateGCPCDN(app)
		}
	default: // docker-prod
		files[filepath.Join(outputDir, "docker_prod.tf")] = generateDockerProd(app)
	}

	// Per-environment tfvars
	for _, env := range app.Environments {
		name := strings.ToLower(env.Name)
		files[filepath.Join(outputDir, "envs", name+".tfvars")] = generateEnvTFVars(app, env, target)
	}

	for path, content := range files {
		if err := writeFile(path, content); err != nil {
			return err
		}
	}

	return nil
}

func writeFile(path, content string) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("creating directory %s: %w", dir, err)
	}
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		return fmt.Errorf("writing %s: %w", path, err)
	}
	return nil
}

// ── Stack Detection ──

func deployTarget(app *ir.Application) string {
	if app.Config == nil || app.Config.Deploy == "" {
		return "docker"
	}
	lower := strings.ToLower(app.Config.Deploy)
	if strings.Contains(lower, "aws") {
		return "aws"
	}
	if strings.Contains(lower, "gcp") || strings.Contains(lower, "google") {
		return "gcp"
	}
	return "docker"
}

func appNameLower(app *ir.Application) string {
	if app.Name != "" {
		return strings.ToLower(strings.ReplaceAll(app.Name, " ", "-"))
	}
	return "app"
}

func appNameSnake(app *ir.Application) string {
	if app.Name != "" {
		return strings.ToLower(strings.ReplaceAll(app.Name, " ", "_"))
	}
	return "app"
}

func isPostgres(app *ir.Application) bool {
	if app.Config != nil && strings.Contains(strings.ToLower(app.Config.Database), "postgres") {
		return true
	}
	if app.Database != nil && strings.Contains(strings.ToLower(app.Database.Engine), "postgres") {
		return true
	}
	return false
}

func isMySQL(app *ir.Application) bool {
	if app.Config != nil && strings.Contains(strings.ToLower(app.Config.Database), "mysql") {
		return true
	}
	if app.Database != nil && strings.Contains(strings.ToLower(app.Database.Engine), "mysql") {
		return true
	}
	return false
}

func hasFrontend(app *ir.Application) bool {
	if app.Config != nil && app.Config.Frontend != "" {
		return true
	}
	return len(app.Pages) > 0
}

func hasDatabase(app *ir.Application) bool {
	return isPostgres(app) || isMySQL(app)
}

func dbEngine(app *ir.Application) string {
	if isPostgres(app) {
		return "postgres"
	}
	if isMySQL(app) {
		return "mysql"
	}
	return "postgres" // default
}

func isMicroservices(app *ir.Application) bool {
	return app.Architecture != nil && strings.Contains(strings.ToLower(app.Architecture.Style), "microservice")
}

func backendLang(app *ir.Application) string {
	if app.Config == nil || app.Config.Backend == "" {
		return "node"
	}
	lower := strings.ToLower(app.Config.Backend)
	if strings.Contains(lower, "python") || strings.Contains(lower, "django") ||
		strings.Contains(lower, "flask") || strings.Contains(lower, "fastapi") {
		return "python"
	}
	// Match Go precisely to avoid false positives on substrings like "mongo".
	if lower == "go" || strings.HasPrefix(lower, "go ") ||
		strings.Contains(lower, "gin") || strings.Contains(lower, "fiber") ||
		strings.Contains(lower, "golang") {
		return "go"
	}
	return "node"
}

func envVarName(app *ir.Application) string {
	if backendLang(app) == "node" {
		return "NODE_ENV"
	}
	return "APP_ENV"
}

// ── main.tf ──

func generateMainTF(app *ir.Application, target string) string {
	var b strings.Builder
	name := appNameLower(app)

	b.WriteString("# Generated by Human compiler — Terraform configuration\n")
	b.WriteString(fmt.Sprintf("# Application: %s\n\n", app.Name))

	b.WriteString("terraform {\n")
	b.WriteString("  required_version = \">= 1.0\"\n\n")
	b.WriteString("  required_providers {\n")

	switch target {
	case "aws":
		b.WriteString("    aws = {\n")
		b.WriteString("      source  = \"hashicorp/aws\"\n")
		b.WriteString("      version = \"~> 5.0\"\n")
		b.WriteString("    }\n")
	case "gcp":
		b.WriteString("    google = {\n")
		b.WriteString("      source  = \"hashicorp/google\"\n")
		b.WriteString("      version = \"~> 5.0\"\n")
		b.WriteString("    }\n")
	default:
		b.WriteString("    docker = {\n")
		b.WriteString("      source  = \"kreuzwerker/docker\"\n")
		b.WriteString("      version = \"~> 3.0\"\n")
		b.WriteString("    }\n")
	}

	b.WriteString("  }\n\n")

	// Backend for state storage
	switch target {
	case "aws":
		b.WriteString("  backend \"s3\" {\n")
		b.WriteString(fmt.Sprintf("    bucket = \"%s-terraform-state\"\n", name))
		b.WriteString(fmt.Sprintf("    key    = \"%s/terraform.tfstate\"\n", name))
		b.WriteString("    region = \"us-east-1\"  # Set via -backend-config or TF_VAR_aws_region\n")
		b.WriteString("  }\n")
	case "gcp":
		b.WriteString("  backend \"gcs\" {\n")
		b.WriteString(fmt.Sprintf("    bucket = \"%s-terraform-state\"\n", name))
		b.WriteString(fmt.Sprintf("    prefix = \"%s\"\n", name))
		b.WriteString("  }\n")
	}

	b.WriteString("}\n\n")

	// Provider configuration
	switch target {
	case "aws":
		b.WriteString("provider \"aws\" {\n")
		b.WriteString("  region = var.aws_region\n\n")
		b.WriteString("  default_tags {\n")
		b.WriteString("    tags = {\n")
		b.WriteString(fmt.Sprintf("      Project     = \"%s\"\n", app.Name))
		b.WriteString("      Environment = var.environment\n")
		b.WriteString("      ManagedBy   = \"terraform\"\n")
		b.WriteString("    }\n")
		b.WriteString("  }\n")
		b.WriteString("}\n")
	case "gcp":
		b.WriteString("provider \"google\" {\n")
		b.WriteString("  project = var.gcp_project_id\n")
		b.WriteString("  region  = var.gcp_region\n")
		b.WriteString("}\n")
	default:
		b.WriteString("provider \"docker\" {}\n")
	}

	return b.String()
}

// ── variables.tf ──

func generateVariablesTF(app *ir.Application, target string) string {
	var b strings.Builder
	name := appNameLower(app)

	b.WriteString("# Generated by Human compiler\n\n")

	b.WriteString("variable \"environment\" {\n")
	b.WriteString("  description = \"Deployment environment (staging, production)\"\n")
	b.WriteString("  type        = string\n")
	b.WriteString("  default     = \"staging\"\n")
	b.WriteString("}\n\n")

	b.WriteString("variable \"app_name\" {\n")
	b.WriteString("  description = \"Application name\"\n")
	b.WriteString("  type        = string\n")
	b.WriteString(fmt.Sprintf("  default     = \"%s\"\n", name))
	b.WriteString("}\n\n")

	switch target {
	case "aws":
		b.WriteString("variable \"aws_region\" {\n")
		b.WriteString("  description = \"AWS region for deployment\"\n")
		b.WriteString("  type        = string\n")
		b.WriteString("  default     = \"us-east-1\"\n")
		b.WriteString("}\n\n")

		b.WriteString("variable \"container_port\" {\n")
		b.WriteString("  description = \"Port the backend container listens on\"\n")
		b.WriteString("  type        = number\n")
		b.WriteString("  default     = 3000\n")
		b.WriteString("}\n\n")

		b.WriteString("variable \"cpu\" {\n")
		b.WriteString("  description = \"Fargate CPU units (256, 512, 1024, 2048, 4096)\"\n")
		b.WriteString("  type        = number\n")
		b.WriteString("  default     = 256\n")
		b.WriteString("}\n\n")

		b.WriteString("variable \"memory\" {\n")
		b.WriteString("  description = \"Fargate memory in MB\"\n")
		b.WriteString("  type        = number\n")
		b.WriteString("  default     = 512\n")
		b.WriteString("}\n\n")

		b.WriteString("variable \"desired_count\" {\n")
		b.WriteString("  description = \"Number of ECS tasks to run\"\n")
		b.WriteString("  type        = number\n")
		b.WriteString("  default     = 2\n")
		b.WriteString("}\n\n")

		if hasDatabase(app) {
			b.WriteString("variable \"db_instance_class\" {\n")
			b.WriteString("  description = \"RDS instance class\"\n")
			b.WriteString("  type        = string\n")
			b.WriteString("  default     = \"db.t3.micro\"\n")
			b.WriteString("}\n\n")

			b.WriteString("variable \"db_username\" {\n")
			b.WriteString("  description = \"Database master username\"\n")
			b.WriteString("  type        = string\n")
			b.WriteString("  default     = \"postgres\"\n")
			b.WriteString("  sensitive   = true\n")
			b.WriteString("}\n\n")

			b.WriteString("variable \"db_password\" {\n")
			b.WriteString("  description = \"Database master password\"\n")
			b.WriteString("  type        = string\n")
			b.WriteString("  sensitive   = true\n")
			b.WriteString("}\n\n")
		}

	case "gcp":
		b.WriteString("variable \"gcp_project_id\" {\n")
		b.WriteString("  description = \"GCP project ID\"\n")
		b.WriteString("  type        = string\n")
		b.WriteString("}\n\n")

		b.WriteString("variable \"gcp_region\" {\n")
		b.WriteString("  description = \"GCP region for deployment\"\n")
		b.WriteString("  type        = string\n")
		b.WriteString("  default     = \"us-central1\"\n")
		b.WriteString("}\n\n")

		b.WriteString("variable \"container_port\" {\n")
		b.WriteString("  description = \"Port the backend container listens on\"\n")
		b.WriteString("  type        = number\n")
		b.WriteString("  default     = 3000\n")
		b.WriteString("}\n\n")

		if hasDatabase(app) {
			b.WriteString("variable \"db_tier\" {\n")
			b.WriteString("  description = \"Cloud SQL instance tier\"\n")
			b.WriteString("  type        = string\n")
			b.WriteString("  default     = \"db-f1-micro\"\n")
			b.WriteString("}\n\n")

			b.WriteString("variable \"db_password\" {\n")
			b.WriteString("  description = \"Database password\"\n")
			b.WriteString("  type        = string\n")
			b.WriteString("  sensitive   = true\n")
			b.WriteString("}\n\n")
		}

	default: // docker
		b.WriteString("variable \"container_port\" {\n")
		b.WriteString("  description = \"Port the backend container listens on\"\n")
		b.WriteString("  type        = number\n")
		b.WriteString("  default     = 3000\n")
		b.WriteString("}\n\n")

		b.WriteString("variable \"db_password\" {\n")
		b.WriteString("  description = \"Database password\"\n")
		b.WriteString("  type        = string\n")
		b.WriteString("  default     = \"postgres\"\n")
		b.WriteString("  sensitive   = true\n")
		b.WriteString("}\n\n")
	}

	return b.String()
}

// ── outputs.tf ──

func generateOutputsTF(app *ir.Application, target string) string {
	var b strings.Builder

	b.WriteString("# Generated by Human compiler\n\n")

	switch target {
	case "aws":
		b.WriteString("output \"alb_dns_name\" {\n")
		b.WriteString("  description = \"DNS name of the Application Load Balancer\"\n")
		b.WriteString("  value       = aws_lb.main.dns_name\n")
		b.WriteString("}\n\n")

		b.WriteString("output \"ecr_repository_url\" {\n")
		b.WriteString("  description = \"ECR repository URL for pushing images\"\n")
		b.WriteString("  value       = aws_ecr_repository.app.repository_url\n")
		b.WriteString("}\n\n")

		if hasDatabase(app) {
			b.WriteString("output \"rds_endpoint\" {\n")
			b.WriteString("  description = \"RDS database endpoint\"\n")
			b.WriteString("  value       = aws_db_instance.main.endpoint\n")
			b.WriteString("}\n\n")
		}

		if hasFrontend(app) {
			b.WriteString("output \"cdn_domain_name\" {\n")
			b.WriteString("  description = \"CloudFront distribution domain name\"\n")
			b.WriteString("  value       = aws_cloudfront_distribution.frontend.domain_name\n")
			b.WriteString("}\n\n")
		}

	case "gcp":
		b.WriteString("output \"service_url\" {\n")
		b.WriteString("  description = \"Cloud Run service URL\"\n")
		b.WriteString("  value       = google_cloud_run_v2_service.backend.uri\n")
		b.WriteString("}\n\n")

		if hasDatabase(app) {
			b.WriteString("output \"database_connection_name\" {\n")
			b.WriteString("  description = \"Cloud SQL connection name\"\n")
			b.WriteString("  value       = google_sql_database_instance.main.connection_name\n")
			b.WriteString("}\n\n")
		}

	default:
		b.WriteString("output \"backend_url\" {\n")
		b.WriteString("  description = \"Backend service URL\"\n")
		b.WriteString("  value       = \"http://localhost:${var.container_port}\"\n")
		b.WriteString("}\n\n")
	}

	return b.String()
}

// ── terraform.tfvars.example ──

func generateTFVarsExample(app *ir.Application, target string) string {
	var b strings.Builder
	name := appNameLower(app)

	b.WriteString("# Copy this file to terraform.tfvars and fill in values\n\n")
	b.WriteString(fmt.Sprintf("app_name    = \"%s\"\n", name))
	b.WriteString("environment = \"staging\"\n\n")

	switch target {
	case "aws":
		b.WriteString("aws_region     = \"us-east-1\"\n")
		b.WriteString("container_port = 3000\n")
		b.WriteString("cpu            = 256\n")
		b.WriteString("memory         = 512\n")
		b.WriteString("desired_count  = 2\n")
		if hasDatabase(app) {
			b.WriteString("\ndb_instance_class = \"db.t3.micro\"\n")
			b.WriteString("db_username       = \"postgres\"\n")
			b.WriteString("db_password       = \"CHANGE_ME\"\n")
		}
	case "gcp":
		b.WriteString("gcp_project_id = \"your-project-id\"\n")
		b.WriteString("gcp_region     = \"us-central1\"\n")
		b.WriteString("container_port = 3000\n")
		if hasDatabase(app) {
			b.WriteString("\ndb_tier     = \"db-f1-micro\"\n")
			b.WriteString("db_password = \"CHANGE_ME\"\n")
		}
	default:
		b.WriteString("container_port = 3000\n")
		b.WriteString("db_password    = \"postgres\"\n")
	}

	return b.String()
}

// ── Per-environment tfvars ──

func generateEnvTFVars(app *ir.Application, env *ir.Environment, target string) string {
	var b strings.Builder

	b.WriteString(fmt.Sprintf("# Environment: %s\n\n", env.Name))
	b.WriteString(fmt.Sprintf("environment = \"%s\"\n", strings.ToLower(env.Name)))

	// Use config values from the environment declaration
	for k, v := range env.Config {
		key := strings.ToLower(strings.ReplaceAll(k, " ", "_"))
		switch {
		case strings.Contains(key, "region"):
			switch target {
			case "aws":
				b.WriteString(fmt.Sprintf("aws_region = \"%s\"\n", v))
			case "gcp":
				b.WriteString(fmt.Sprintf("gcp_region = \"%s\"\n", v))
			}
		case strings.Contains(key, "instance") || strings.Contains(key, "tier"):
			switch target {
			case "aws":
				b.WriteString(fmt.Sprintf("db_instance_class = \"%s\"\n", v))
			case "gcp":
				b.WriteString(fmt.Sprintf("db_tier = \"%s\"\n", v))
			}
		case strings.Contains(key, "count") || strings.Contains(key, "replicas"):
			if target == "aws" {
				b.WriteString(fmt.Sprintf("desired_count = %s\n", v))
			}
		}
	}

	// Production defaults
	if strings.EqualFold(env.Name, "production") {
		switch target {
		case "aws":
			if _, ok := env.Config["instance"]; !ok {
				b.WriteString("db_instance_class = \"db.t3.small\"\n")
			}
			// Only write desired_count if not already set from env config
			hasCount := false
			for k := range env.Config {
				kl := strings.ToLower(strings.ReplaceAll(k, " ", "_"))
				if strings.Contains(kl, "count") || strings.Contains(kl, "replicas") {
					hasCount = true
					break
				}
			}
			if !hasCount {
				b.WriteString("desired_count     = 3\n")
			}
			b.WriteString("cpu               = 512\n")
			b.WriteString("memory            = 1024\n")
		case "gcp":
			if _, ok := env.Config["tier"]; !ok {
				b.WriteString("db_tier = \"db-g1-small\"\n")
			}
		}
	}

	return b.String()
}
