package scaffold

import (
	"fmt"
	"strings"

	"github.com/barun-bash/human/internal/codegen/docker"
	"github.com/barun-bash/human/internal/ir"
)

// generateEnvExample produces a .env.example with all required environment
// variables. It reuses the Docker package's CollectEnvVars for consistency.
// This overwrites the Docker generator's .env.example.
func generateEnvExample(app *ir.Application) string {
	var b strings.Builder

	b.WriteString("# Generated by Human compiler — do not edit\n")
	b.WriteString("# Copy to .env and fill in your values\n\n")

	vars := docker.CollectEnvVars(app)

	lastCategory := ""
	for _, v := range vars {
		category := envCategory(v)
		if category != lastCategory {
			if lastCategory != "" {
				b.WriteString("\n")
			}
			fmt.Fprintf(&b, "# %s\n", category)
			lastCategory = category
		}

		if v.Example != "" {
			fmt.Fprintf(&b, "%s=%s\n", v.Name, v.Example)
		} else {
			fmt.Fprintf(&b, "%s=\n", v.Name)
		}
	}

	return b.String()
}

// envCategory returns a section header for an env var based on its name.
func envCategory(v docker.EnvVar) string {
	name := strings.ToUpper(v.Name)

	switch {
	case strings.Contains(name, "DATABASE"):
		return "Database"
	case strings.Contains(name, "JWT"):
		return "Authentication"
	case strings.Contains(name, "PORT"):
		return "Server"
	case strings.Contains(name, "VITE") || strings.Contains(name, "NG_APP"):
		return "Frontend"
	default:
		if v.Comment != "" {
			return "Integration: " + v.Comment
		}
		return "Other"
	}
}
