package scaffold

import (
	"fmt"
	"strings"

	"github.com/barun-bash/human/internal/ir"
)

// generateRootPackageJSON produces a root package.json with npm workspaces
// that orchestrate the backend and frontend, dynamically based on stack config.
// This overwrites the Docker generator's simpler package.json.
func generateRootPackageJSON(app *ir.Application) string {
	var b strings.Builder
	name := appNameLower(app)

	frontend := ""
	backend := ""
	deploy := ""
	if app.Config != nil {
		frontend = strings.ToLower(app.Config.Frontend)
		backend = strings.ToLower(app.Config.Backend)
		deploy = strings.ToLower(app.Config.Deploy)
	}

	// Determine which workspaces exist
	var workspaces []string
	if strings.Contains(backend, "node") {
		workspaces = append(workspaces, "node")
	}
	if strings.Contains(frontend, "react") {
		workspaces = append(workspaces, "react")
	}
	if strings.Contains(frontend, "vue") {
		workspaces = append(workspaces, "vue")
	}
	if strings.Contains(frontend, "angular") {
		workspaces = append(workspaces, "angular")
	}
	if strings.Contains(frontend, "svelte") {
		workspaces = append(workspaces, "svelte")
	}

	// Determine frontend workspace name for scripts
	frontendWS := ""
	for _, ws := range []string{"react", "vue", "angular", "svelte"} {
		if strings.Contains(frontend, ws) {
			frontendWS = ws
			break
		}
	}

	b.WriteString("{\n")
	fmt.Fprintf(&b, "  \"name\": \"%s\",\n", name)
	b.WriteString("  \"version\": \"0.1.0\",\n")
	b.WriteString("  \"private\": true,\n")
	fmt.Fprintf(&b, "  \"description\": \"%s — generated by Human compiler\",\n", app.Name)

	if len(workspaces) > 0 {
		b.WriteString("  \"workspaces\": [\n")
		for i, ws := range workspaces {
			fmt.Fprintf(&b, "    \"%s\"", ws)
			if i < len(workspaces)-1 {
				b.WriteString(",")
			}
			b.WriteString("\n")
		}
		b.WriteString("  ],\n")
	}

	b.WriteString("  \"scripts\": {\n")

	// Build dev/start/build/test scripts based on active workspaces
	var scripts []string
	if strings.Contains(backend, "node") && frontendWS != "" {
		scripts = append(scripts,
			fmt.Sprintf("    \"dev\": \"concurrently \\\"npm run dev --workspace=node\\\" \\\"npm run dev --workspace=%s\\\"\"", frontendWS),
			fmt.Sprintf("    \"start\": \"concurrently \\\"npm run start --workspace=node\\\" \\\"npm run start --workspace=%s\\\"\"", frontendWS),
			fmt.Sprintf("    \"build\": \"npm run build --workspace=node && npm run build --workspace=%s\"", frontendWS),
			"    \"test\": \"npm run test --workspace=node\"",
		)
	} else if strings.Contains(backend, "node") {
		scripts = append(scripts,
			"    \"dev\": \"npm run dev --workspace=node\"",
			"    \"start\": \"npm run start --workspace=node\"",
			"    \"build\": \"npm run build --workspace=node\"",
			"    \"test\": \"npm run test --workspace=node\"",
		)
	} else if frontendWS != "" {
		scripts = append(scripts,
			fmt.Sprintf("    \"dev\": \"npm run dev --workspace=%s\"", frontendWS),
			fmt.Sprintf("    \"start\": \"npm run start --workspace=%s\"", frontendWS),
			fmt.Sprintf("    \"build\": \"npm run build --workspace=%s\"", frontendWS),
		)
	}

	// Prisma scripts only for Node backend
	if strings.Contains(backend, "node") {
		scripts = append(scripts,
			"    \"db:migrate\": \"cd node && npx prisma migrate deploy\"",
			"    \"db:seed\": \"cd node && npx prisma db seed\"",
			"    \"db:studio\": \"cd node && npx prisma studio\"",
		)
	}

	// Docker scripts only if deploy target is Docker
	if strings.Contains(deploy, "docker") {
		scripts = append(scripts,
			"    \"docker:dev\": \"docker compose up --build\"",
			"    \"docker:start\": \"docker compose up -d\"",
			"    \"docker:stop\": \"docker compose down\"",
		)
	}

	for i, s := range scripts {
		b.WriteString(s)
		if i < len(scripts)-1 {
			b.WriteString(",")
		}
		b.WriteString("\n")
	}
	b.WriteString("  }")

	// devDependencies only if we have multiple workspaces (need concurrently)
	if len(workspaces) > 1 {
		b.WriteString(",\n")
		b.WriteString("  \"devDependencies\": {\n")
		b.WriteString("    \"concurrently\": \"^9.0.0\"\n")
		b.WriteString("  }\n")
	} else {
		b.WriteString("\n")
	}

	b.WriteString("}\n")

	return b.String()
}

// generateNodePackageJSON produces node/package.json with Express, Prisma,
// and all backend dependencies.
func generateNodePackageJSON(app *ir.Application) string {
	var b strings.Builder
	name := appNameLower(app)

	b.WriteString("{\n")
	fmt.Fprintf(&b, "  \"name\": \"%s-backend\",\n", name)
	b.WriteString("  \"version\": \"0.1.0\",\n")
	b.WriteString("  \"private\": true,\n")
	b.WriteString("  \"scripts\": {\n")
	b.WriteString("    \"start\": \"node dist/server.js\",\n")
	b.WriteString("    \"dev\": \"ts-node src/server.ts\",\n")
	b.WriteString("    \"build\": \"tsc\",\n")
	b.WriteString("    \"test\": \"jest\"\n")
	b.WriteString("  },\n")
	b.WriteString("  \"dependencies\": {\n")
	b.WriteString("    \"@prisma/client\": \"^6.0.0\",\n")
	b.WriteString("    \"bcryptjs\": \"^2.4.3\",\n")
	b.WriteString("    \"cors\": \"^2.8.5\",\n")
	b.WriteString("    \"express\": \"^4.21.0\",\n")
	b.WriteString("    \"jsonwebtoken\": \"^9.0.0\"\n")
	b.WriteString("  },\n")
	b.WriteString("  \"devDependencies\": {\n")
	b.WriteString("    \"@types/bcryptjs\": \"^2.4.6\",\n")
	b.WriteString("    \"@types/cors\": \"^2.8.17\",\n")
	b.WriteString("    \"@types/express\": \"^5.0.0\",\n")
	b.WriteString("    \"@types/jest\": \"^29.5.0\",\n")
	b.WriteString("    \"@types/jsonwebtoken\": \"^9.0.7\",\n")
	b.WriteString("    \"@types/supertest\": \"^6.0.0\",\n")
	b.WriteString("    \"jest\": \"^29.7.0\",\n")
	b.WriteString("    \"prisma\": \"^6.0.0\",\n")
	b.WriteString("    \"supertest\": \"^7.0.0\",\n")
	b.WriteString("    \"ts-jest\": \"^29.2.0\",\n")
	b.WriteString("    \"ts-node\": \"^10.9.0\",\n")
	b.WriteString("    \"typescript\": \"^5.7.0\"\n")
	b.WriteString("  }\n")
	b.WriteString("}\n")

	return b.String()
}

// generateReactPackageJSON produces react/package.json with React, Vite,
// and frontend dependencies.
func generateReactPackageJSON(app *ir.Application) string {
	var b strings.Builder
	name := appNameLower(app)

	b.WriteString("{\n")
	fmt.Fprintf(&b, "  \"name\": \"%s-frontend\",\n", name)
	b.WriteString("  \"version\": \"0.1.0\",\n")
	b.WriteString("  \"private\": true,\n")
	b.WriteString("  \"type\": \"module\",\n")
	b.WriteString("  \"scripts\": {\n")
	b.WriteString("    \"dev\": \"vite\",\n")
	b.WriteString("    \"build\": \"tsc && vite build\",\n")
	b.WriteString("    \"preview\": \"vite preview\",\n")
	b.WriteString("    \"start\": \"vite preview\"\n")
	b.WriteString("  },\n")
	b.WriteString("  \"dependencies\": {\n")
	b.WriteString("    \"react\": \"^19.0.0\",\n")
	b.WriteString("    \"react-dom\": \"^19.0.0\",\n")
	b.WriteString("    \"react-router-dom\": \"^7.0.0\"\n")
	b.WriteString("  },\n")
	b.WriteString("  \"devDependencies\": {\n")
	b.WriteString("    \"@types/react\": \"^19.0.0\",\n")
	b.WriteString("    \"@types/react-dom\": \"^19.0.0\",\n")
	b.WriteString("    \"@vitejs/plugin-react\": \"^4.3.0\",\n")
	b.WriteString("    \"autoprefixer\": \"^10.4.0\",\n")
	b.WriteString("    \"postcss\": \"^8.4.0\",\n")
	b.WriteString("    \"tailwindcss\": \"^3.4.0\",\n")
	b.WriteString("    \"typescript\": \"^5.7.0\",\n")
	b.WriteString("    \"vite\": \"^6.0.0\"\n")
	b.WriteString("  }\n")
	b.WriteString("}\n")

	return b.String()
}

// generateVuePackageJSON produces vue/package.json with Vue 3, Vite,
// and frontend dependencies.
func generateVuePackageJSON(app *ir.Application) string {
	var b strings.Builder
	name := appNameLower(app)

	b.WriteString("{\n")
	fmt.Fprintf(&b, "  \"name\": \"%s-frontend\",\n", name)
	b.WriteString("  \"version\": \"0.1.0\",\n")
	b.WriteString("  \"private\": true,\n")
	b.WriteString("  \"type\": \"module\",\n")
	b.WriteString("  \"scripts\": {\n")
	b.WriteString("    \"dev\": \"vite\",\n")
	b.WriteString("    \"build\": \"vue-tsc && vite build\",\n")
	b.WriteString("    \"preview\": \"vite preview\",\n")
	b.WriteString("    \"start\": \"vite preview\"\n")
	b.WriteString("  },\n")
	b.WriteString("  \"dependencies\": {\n")
	b.WriteString("    \"vue\": \"^3.5.0\",\n")
	b.WriteString("    \"vue-router\": \"^4.4.0\",\n")
	b.WriteString("    \"pinia\": \"^2.2.0\"\n")
	b.WriteString("  },\n")
	b.WriteString("  \"devDependencies\": {\n")
	b.WriteString("    \"@vitejs/plugin-vue\": \"^5.2.0\",\n")
	b.WriteString("    \"autoprefixer\": \"^10.4.0\",\n")
	b.WriteString("    \"postcss\": \"^8.4.0\",\n")
	b.WriteString("    \"tailwindcss\": \"^3.4.0\",\n")
	b.WriteString("    \"typescript\": \"^5.7.0\",\n")
	b.WriteString("    \"vite\": \"^6.0.0\",\n")
	b.WriteString("    \"vue-tsc\": \"^2.1.0\"\n")
	b.WriteString("  }\n")
	b.WriteString("}\n")

	return b.String()
}
