package scaffold

import (
	"fmt"
	"strings"

	"github.com/barun-bash/human/internal/ir"
)

// generateReadme produces a README.md dynamically from the IR,
// including the app name, tech stack, data models, and API endpoints.
func generateReadme(app *ir.Application) string {
	var b strings.Builder

	// Title
	fmt.Fprintf(&b, "# %s\n\n", app.Name)
	b.WriteString("Generated by the [Human](https://github.com/barun-bash/human) compiler.\n\n")

	// Tech stack
	if app.Config != nil {
		b.WriteString("## Tech Stack\n\n")
		b.WriteString("| Layer | Technology |\n")
		b.WriteString("|-------|------------|\n")
		if app.Config.Frontend != "" {
			fmt.Fprintf(&b, "| Frontend | %s |\n", app.Config.Frontend)
		}
		if app.Config.Backend != "" {
			fmt.Fprintf(&b, "| Backend | %s |\n", app.Config.Backend)
		}
		if app.Config.Database != "" {
			fmt.Fprintf(&b, "| Database | %s |\n", app.Config.Database)
		}
		if app.Config.Deploy != "" {
			fmt.Fprintf(&b, "| Deploy | %s |\n", app.Config.Deploy)
		}
		b.WriteString("\n")
	}

	// Data models
	if len(app.Data) > 0 {
		b.WriteString("## Data Models\n\n")
		b.WriteString("| Model | Fields |\n")
		b.WriteString("|-------|--------|\n")
		for _, model := range app.Data {
			fields := make([]string, 0, len(model.Fields))
			for _, f := range model.Fields {
				fields = append(fields, f.Name)
			}
			fmt.Fprintf(&b, "| %s | %s |\n", model.Name, strings.Join(fields, ", "))
		}
		b.WriteString("\n")
	}

	// API endpoints
	if len(app.APIs) > 0 {
		b.WriteString("## API Endpoints\n\n")
		b.WriteString("| Endpoint | Auth |\n")
		b.WriteString("|----------|------|\n")
		for _, api := range app.APIs {
			auth := "No"
			if api.Auth {
				auth = "Yes"
			}
			fmt.Fprintf(&b, "| %s | %s |\n", api.Name, auth)
		}
		b.WriteString("\n")
	}

	// Quick start
	b.WriteString("## Quick Start\n\n")
	b.WriteString("### Option 1: npm (local development)\n\n")
	b.WriteString("```bash\n")
	b.WriteString("./start.sh\n")
	b.WriteString("```\n\n")
	b.WriteString("Or manually:\n\n")
	b.WriteString("```bash\n")
	b.WriteString("npm install\n")
	b.WriteString("cp .env.example .env   # edit with your values\n")
	b.WriteString("cd node && npx prisma generate && npx prisma db push && cd ..\n")
	b.WriteString("npm run dev\n")
	b.WriteString("```\n\n")
	b.WriteString("### Option 2: Docker\n\n")
	b.WriteString("```bash\n")
	b.WriteString("cp .env.example .env   # edit with your values\n")
	b.WriteString("npm run docker:dev\n")
	b.WriteString("```\n\n")

	// Ports
	b.WriteString("## Ports\n\n")
	b.WriteString("| Service | Port |\n")
	b.WriteString("|---------|------|\n")
	b.WriteString("| Backend | 3000 |\n")
	b.WriteString("| Frontend (dev) | 5173 |\n")
	b.WriteString("| PostgreSQL | 5432 |\n")

	return b.String()
}
