package gobackend

import (
	"fmt"
	"strings"

	"github.com/barun-bash/human/internal/ir"
)

// generateIntegrations returns a map of file paths (relative to outputDir) to
// their generated Go content for all integration services.
func generateIntegrations(moduleName string, app *ir.Application) map[string]string {
	if len(app.Integrations) == 0 {
		return nil
	}

	files := make(map[string]string)

	for _, integ := range app.Integrations {
		switch integ.Type {
		case "email":
			files["services/email.go"] = generateEmailService(moduleName, integ)
		case "storage":
			files["services/storage.go"] = generateStorageService(moduleName, integ)
		case "payment":
			files["services/stripe.go"] = generatePaymentService(moduleName, integ)
		case "messaging":
			files["services/slack.go"] = generateMessagingService(moduleName, integ)
		case "oauth":
			files["services/oauth.go"] = generateOAuthService(moduleName, integ)
		default:
			files["services/"+toSnakeCase(integ.Service)+".go"] = generateGenericGoService(moduleName, integ)
		}
	}

	return files
}

// generateEmailService produces a Go email service using SendGrid.
func generateEmailService(_ string, integ *ir.Integration) string {
	var b strings.Builder

	b.WriteString("// Generated by Human compiler — do not edit\n")
	fmt.Fprintf(&b, "// Integration: %s (email)\n", integ.Service)
	b.WriteString("package services\n\n")

	b.WriteString("import (\n")
	b.WriteString("\t\"os\"\n\n")
	b.WriteString("\t\"github.com/sendgrid/sendgrid-go\"\n")
	b.WriteString("\t\"github.com/sendgrid/sendgrid-go/helpers/mail\"\n")
	b.WriteString(")\n\n")

	// Determine the API key env var.
	apiKeyEnv := "SENDGRID_API_KEY"
	for _, envVar := range integ.Credentials {
		apiKeyEnv = envVar
		break
	}

	// Sender email.
	senderEmail := "noreply@example.com"
	if v, ok := integ.Config["sender_email"]; ok {
		senderEmail = v
	}

	b.WriteString("// SendEmail sends an email via SendGrid.\n")
	b.WriteString("func SendEmail(to, subject, textContent string) error {\n")
	fmt.Fprintf(&b, "\tfrom := mail.NewEmail(\"App\", os.Getenv(\"%s\"))\n", "SENDER_EMAIL")
	if senderEmail != "noreply@example.com" {
		// If a custom sender is configured, use it as fallback.
		b.WriteString("\tif from.Address == \"\" {\n")
		fmt.Fprintf(&b, "\t\tfrom = mail.NewEmail(\"App\", \"%s\")\n", senderEmail)
		b.WriteString("\t}\n")
	}
	b.WriteString("\ttoAddr := mail.NewEmail(\"\", to)\n")
	b.WriteString("\tmessage := mail.NewSingleEmail(from, subject, toAddr, textContent, \"\")\n")
	fmt.Fprintf(&b, "\tclient := sendgrid.NewSendClient(os.Getenv(\"%s\"))\n", apiKeyEnv)
	b.WriteString("\t_, err := client.Send(message)\n")
	b.WriteString("\treturn err\n")
	b.WriteString("}\n")

	return b.String()
}

// generateStorageService produces a Go storage service using AWS SDK v2.
func generateStorageService(_ string, integ *ir.Integration) string {
	var b strings.Builder

	b.WriteString("// Generated by Human compiler — do not edit\n")
	fmt.Fprintf(&b, "// Integration: %s (storage)\n", integ.Service)
	b.WriteString("package services\n\n")

	b.WriteString("import (\n")
	b.WriteString("\t\"context\"\n")
	b.WriteString("\t\"io\"\n")
	b.WriteString("\t\"os\"\n\n")
	b.WriteString("\t\"github.com/aws/aws-sdk-go-v2/config\"\n")
	b.WriteString("\t\"github.com/aws/aws-sdk-go-v2/service/s3\"\n")
	b.WriteString(")\n\n")

	bucketEnv := "S3_BUCKET"
	if v, ok := integ.Config["bucket_env"]; ok {
		bucketEnv = v
	}

	b.WriteString("var s3Client *s3.Client\n\n")

	b.WriteString("func initS3() {\n")
	b.WriteString("\tcfg, _ := config.LoadDefaultConfig(context.TODO())\n")
	b.WriteString("\ts3Client = s3.NewFromConfig(cfg)\n")
	b.WriteString("}\n\n")

	b.WriteString("// UploadFile uploads a file to S3.\n")
	b.WriteString("func UploadFile(key string, body io.Reader) error {\n")
	b.WriteString("\tif s3Client == nil {\n")
	b.WriteString("\t\tinitS3()\n")
	b.WriteString("\t}\n")
	fmt.Fprintf(&b, "\tbucket := os.Getenv(\"%s\")\n", bucketEnv)
	b.WriteString("\t_, err := s3Client.PutObject(context.TODO(), &s3.PutObjectInput{\n")
	b.WriteString("\t\tBucket: &bucket,\n")
	b.WriteString("\t\tKey:    &key,\n")
	b.WriteString("\t\tBody:   body,\n")
	b.WriteString("\t})\n")
	b.WriteString("\treturn err\n")
	b.WriteString("}\n")

	return b.String()
}

// generatePaymentService produces a Go payment service using Stripe.
func generatePaymentService(_ string, integ *ir.Integration) string {
	var b strings.Builder

	b.WriteString("// Generated by Human compiler — do not edit\n")
	fmt.Fprintf(&b, "// Integration: %s (payment)\n", integ.Service)
	b.WriteString("package services\n\n")

	b.WriteString("import (\n")
	b.WriteString("\t\"os\"\n\n")
	b.WriteString("\t\"github.com/stripe/stripe-go/v81\"\n")
	b.WriteString("\t\"github.com/stripe/stripe-go/v81/checkout/session\"\n")
	b.WriteString(")\n\n")

	// Determine the API key env var.
	apiKeyEnv := "STRIPE_SECRET_KEY"
	for _, envVar := range integ.Credentials {
		apiKeyEnv = envVar
		break
	}

	fmt.Fprintf(&b, "func init() {\n\tstripe.Key = os.Getenv(\"%s\")\n}\n\n", apiKeyEnv)

	b.WriteString("// CreateCheckoutSession creates a Stripe checkout session.\n")
	b.WriteString("func CreateCheckoutSession(priceID, successURL, cancelURL string) (*stripe.CheckoutSession, error) {\n")
	b.WriteString("\tparams := &stripe.CheckoutSessionParams{\n")
	b.WriteString("\t\tMode: stripe.String(string(stripe.CheckoutSessionModePayment)),\n")
	b.WriteString("\t\tLineItems: []*stripe.CheckoutSessionLineItemParams{{\n")
	b.WriteString("\t\t\tPrice:    stripe.String(priceID),\n")
	b.WriteString("\t\t\tQuantity: stripe.Int64(1),\n")
	b.WriteString("\t\t}},\n")
	b.WriteString("\t\tSuccessURL: stripe.String(successURL),\n")
	b.WriteString("\t\tCancelURL:  stripe.String(cancelURL),\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn session.New(params)\n")
	b.WriteString("}\n")

	return b.String()
}

// generateMessagingService produces a Go messaging service using Slack.
func generateMessagingService(_ string, integ *ir.Integration) string {
	var b strings.Builder

	b.WriteString("// Generated by Human compiler — do not edit\n")
	fmt.Fprintf(&b, "// Integration: %s (messaging)\n", integ.Service)
	b.WriteString("package services\n\n")

	b.WriteString("import (\n")
	b.WriteString("\t\"os\"\n\n")
	b.WriteString("\t\"github.com/slack-go/slack\"\n")
	b.WriteString(")\n\n")

	// Determine the webhook env var.
	webhookEnv := "SLACK_WEBHOOK_URL"
	for _, envVar := range integ.Credentials {
		webhookEnv = envVar
		break
	}

	b.WriteString("// SendSlackMessage sends a message via Slack webhook.\n")
	b.WriteString("func SendSlackMessage(text string) error {\n")
	fmt.Fprintf(&b, "\twebhookURL := os.Getenv(\"%s\")\n", webhookEnv)
	b.WriteString("\treturn slack.PostWebhook(webhookURL, &slack.WebhookMessage{Text: text})\n")
	b.WriteString("}\n")

	return b.String()
}

// generateOAuthService produces a Go OAuth2 service.
func generateOAuthService(_ string, integ *ir.Integration) string {
	var b strings.Builder

	b.WriteString("// Generated by Human compiler — do not edit\n")
	fmt.Fprintf(&b, "// Integration: %s (oauth)\n", integ.Service)
	b.WriteString("package services\n\n")

	b.WriteString("import \"golang.org/x/oauth2\"\n\n")

	// Determine credential env vars.
	clientIDEnv := strings.ToUpper(strings.ReplaceAll(integ.Service, " ", "_")) + "_CLIENT_ID"
	clientSecretEnv := strings.ToUpper(strings.ReplaceAll(integ.Service, " ", "_")) + "_CLIENT_SECRET"
	for key, envVar := range integ.Credentials {
		lower := strings.ToLower(key)
		if strings.Contains(lower, "secret") {
			clientSecretEnv = envVar
		} else if strings.Contains(lower, "id") || strings.Contains(lower, "client") {
			clientIDEnv = envVar
		}
	}

	// Determine OAuth endpoints based on provider.
	serviceLower := strings.ToLower(integ.Service)
	authURL := "https://accounts.google.com/o/oauth2/auth"
	tokenURL := "https://oauth2.googleapis.com/token"
	if strings.Contains(serviceLower, "github") {
		authURL = "https://github.com/login/oauth/authorize"
		tokenURL = "https://github.com/login/oauth/access_token"
	} else if strings.Contains(serviceLower, "facebook") {
		authURL = "https://www.facebook.com/v18.0/dialog/oauth"
		tokenURL = "https://graph.facebook.com/v18.0/oauth/access_token"
	}

	callbackURL := "/auth/callback"
	if v, ok := integ.Config["callback_url"]; ok {
		callbackURL = v
	}

	b.WriteString("// GetOAuth2Config returns an OAuth2 configuration for the given provider.\n")
	b.WriteString("func GetOAuth2Config() *oauth2.Config {\n")
	b.WriteString("\treturn &oauth2.Config{\n")
	fmt.Fprintf(&b, "\t\tClientID:     os.Getenv(\"%s\"),\n", clientIDEnv)
	fmt.Fprintf(&b, "\t\tClientSecret: os.Getenv(\"%s\"),\n", clientSecretEnv)
	fmt.Fprintf(&b, "\t\tRedirectURL:  \"%s\",\n", callbackURL)
	b.WriteString("\t\tEndpoint: oauth2.Endpoint{\n")
	fmt.Fprintf(&b, "\t\t\tAuthURL:  \"%s\",\n", authURL)
	fmt.Fprintf(&b, "\t\t\tTokenURL: \"%s\",\n", tokenURL)
	b.WriteString("\t\t},\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n")

	return b.String()
}

// generateGenericGoService produces a minimal Go service for unknown integrations.
func generateGenericGoService(_ string, integ *ir.Integration) string {
	var b strings.Builder

	b.WriteString("// Generated by Human compiler — do not edit\n")
	fmt.Fprintf(&b, "// Integration: %s\n", integ.Service)
	b.WriteString("package services\n\n")

	structName := toPascalCase(integ.Service) + "Service"

	fmt.Fprintf(&b, "// %s provides access to the %s integration.\n", structName, integ.Service)
	fmt.Fprintf(&b, "type %s struct {\n", structName)
	for key, envVar := range integ.Credentials {
		fieldName := toPascalCase(key)
		fmt.Fprintf(&b, "\t%s string // from env: %s\n", fieldName, envVar)
	}
	for key, val := range integ.Config {
		fieldName := toPascalCase(key)
		fmt.Fprintf(&b, "\t%s string // default: %s\n", fieldName, val)
	}
	b.WriteString("}\n\n")

	fmt.Fprintf(&b, "// New%s creates a new %s with configuration from environment.\n", structName, structName)
	fmt.Fprintf(&b, "func New%s() *%s {\n", structName, structName)
	fmt.Fprintf(&b, "\treturn &%s{}\n", structName)
	b.WriteString("}\n")

	return b.String()
}
