package python

import (
	"fmt"
	"strings"

	"github.com/barun-bash/human/internal/ir"
)

// generateIntegrations returns a map of file paths (relative to outputDir) to
// their generated Python content for all integration services.
func generateIntegrations(app *ir.Application) map[string]string {
	if len(app.Integrations) == 0 {
		return nil
	}

	files := make(map[string]string)
	usedFilenames := make(map[string]bool)

	for _, integ := range app.Integrations {
		var content string
		var filename string

		switch integ.Type {
		case "email":
			filename = "email_service.py"
			content = generateEmailService(integ)
		case "storage":
			filename = "storage_service.py"
			content = generateStorageService(integ)
		case "payment":
			filename = "stripe_service.py"
			content = generatePaymentService(integ)
		case "messaging":
			filename = "slack_service.py"
			content = generateMessagingService(integ)
		case "oauth":
			filename = "oauth_service.py"
			content = generateOAuthService(integ)
		default:
			filename = toSnakeCase(integ.Service) + "_service.py"
			content = generateGenericService(integ)
		}

		// If filename is already used (two integrations of same type),
		// fall back to a service-specific filename.
		if usedFilenames[filename] {
			filename = toSnakeCase(integ.Service) + "_service.py"
		}
		usedFilenames[filename] = true

		files["services/"+filename] = content
	}

	// Generate __init__.py
	files["services/__init__.py"] = generateServiceInit(files)

	return files
}

// generateEmailService produces a Python email service using SendGrid.
func generateEmailService(integ *ir.Integration) string {
	var b strings.Builder

	b.WriteString("# Generated by Human compiler — do not edit\n")
	fmt.Fprintf(&b, "# Integration: %s (email)\n\n", integ.Service)

	// Determine the API key env var.
	apiKeyEnv := "SENDGRID_API_KEY"
	for _, envVar := range integ.Credentials {
		apiKeyEnv = envVar
		break
	}

	// Sender email.
	senderEmail := "noreply@example.com"
	if v, ok := integ.Config["sender_email"]; ok {
		senderEmail = v
	}

	b.WriteString("import os\n")
	b.WriteString("from sendgrid import SendGridAPIClient\n")
	b.WriteString("from sendgrid.helpers.mail import Mail\n\n")

	fmt.Fprintf(&b, "sg = SendGridAPIClient(os.environ.get('%s', ''))\n\n", apiKeyEnv)

	b.WriteString("async def send_email(to: str, subject: str, text: str = '', html: str = '') -> None:\n")
	b.WriteString("    message = Mail(\n")
	fmt.Fprintf(&b, "        from_email=os.environ.get('SENDER_EMAIL', '%s'),\n", senderEmail)
	b.WriteString("        to_emails=to,\n")
	b.WriteString("        subject=subject,\n")
	b.WriteString("        plain_text_content=text,\n")
	b.WriteString("        html_content=html or None,\n")
	b.WriteString("    )\n")
	b.WriteString("    sg.send(message)\n")

	// Generate template helpers if templates are defined.
	if len(integ.Templates) > 0 {
		b.WriteString("\n\n# Available email templates\n")
		b.WriteString("EMAIL_TEMPLATES = {\n")
		for _, tpl := range integ.Templates {
			constName := strings.ReplaceAll(strings.ToUpper(tpl), "-", "_")
			fmt.Fprintf(&b, "    '%s': '%s',\n", constName, tpl)
		}
		b.WriteString("}\n")
	}

	return b.String()
}

// generateStorageService produces a Python storage service using boto3 / S3.
func generateStorageService(integ *ir.Integration) string {
	var b strings.Builder

	b.WriteString("# Generated by Human compiler — do not edit\n")
	fmt.Fprintf(&b, "# Integration: %s (storage)\n\n", integ.Service)

	// Determine env vars.
	accessKeyEnv := "AWS_ACCESS_KEY"
	secretKeyEnv := "AWS_SECRET_KEY"
	for key, envVar := range integ.Credentials {
		lower := strings.ToLower(key)
		if strings.Contains(lower, "secret") {
			secretKeyEnv = envVar
		} else {
			accessKeyEnv = envVar
		}
	}

	region := "us-east-1"
	if v, ok := integ.Config["region"]; ok {
		region = v
	}

	bucket := strings.ToLower(strings.ReplaceAll(integ.Service, " ", "-")) + "-bucket"
	if v, ok := integ.Config["bucket"]; ok {
		bucket = v
	}

	b.WriteString("import os\n")
	b.WriteString("import boto3\n\n")

	b.WriteString("s3_client = boto3.client(\n")
	b.WriteString("    's3',\n")
	fmt.Fprintf(&b, "    region_name=os.environ.get('AWS_REGION', '%s'),\n", region)
	fmt.Fprintf(&b, "    aws_access_key_id=os.environ.get('%s', ''),\n", accessKeyEnv)
	fmt.Fprintf(&b, "    aws_secret_access_key=os.environ.get('%s', ''),\n", secretKeyEnv)
	b.WriteString(")\n\n")

	fmt.Fprintf(&b, "BUCKET = os.environ.get('S3_BUCKET', '%s')\n\n", bucket)

	b.WriteString("async def upload_file(key: str, file_obj, content_type: str = None) -> str:\n")
	b.WriteString("    extra_args = {}\n")
	b.WriteString("    if content_type:\n")
	b.WriteString("        extra_args['ContentType'] = content_type\n")
	b.WriteString("    s3_client.upload_fileobj(file_obj, BUCKET, key, ExtraArgs=extra_args)\n")
	b.WriteString("    return key\n\n")

	b.WriteString("async def get_signed_url(key: str, expires_in: int = 3600) -> str:\n")
	b.WriteString("    return s3_client.generate_presigned_url(\n")
	b.WriteString("        'get_object', Params={'Bucket': BUCKET, 'Key': key}, ExpiresIn=expires_in\n")
	b.WriteString("    )\n\n")

	b.WriteString("async def delete_file(key: str) -> None:\n")
	b.WriteString("    s3_client.delete_object(Bucket=BUCKET, Key=key)\n")

	return b.String()
}

// generatePaymentService produces a Python payment service using Stripe.
func generatePaymentService(integ *ir.Integration) string {
	var b strings.Builder

	b.WriteString("# Generated by Human compiler — do not edit\n")
	fmt.Fprintf(&b, "# Integration: %s (payment)\n\n", integ.Service)

	apiKeyEnv := "STRIPE_SECRET_KEY"
	for _, envVar := range integ.Credentials {
		apiKeyEnv = envVar
		break
	}

	b.WriteString("import os\n")
	b.WriteString("import stripe\n\n")

	fmt.Fprintf(&b, "stripe.api_key = os.environ.get('%s', '')\n\n", apiKeyEnv)

	b.WriteString("async def create_checkout_session(price_id: str, success_url: str, cancel_url: str, customer_id: str = None):\n")
	b.WriteString("    params = {\n")
	b.WriteString("        'mode': 'payment',\n")
	b.WriteString("        'line_items': [{'price': price_id, 'quantity': 1}],\n")
	b.WriteString("        'success_url': success_url,\n")
	b.WriteString("        'cancel_url': cancel_url,\n")
	b.WriteString("    }\n")
	b.WriteString("    if customer_id:\n")
	b.WriteString("        params['customer'] = customer_id\n")
	b.WriteString("    return stripe.checkout.Session.create(**params)\n\n")

	b.WriteString("def verify_webhook_signature(payload: bytes, signature: str, secret: str):\n")
	b.WriteString("    return stripe.Webhook.construct_event(payload, signature, secret)\n")

	// Webhook endpoint constant if configured.
	if webhookEndpoint, ok := integ.Config["webhook_endpoint"]; ok {
		fmt.Fprintf(&b, "\nWEBHOOK_ENDPOINT = '%s'\n", webhookEndpoint)
	}

	return b.String()
}

// generateMessagingService produces a Python messaging service using Slack SDK.
func generateMessagingService(integ *ir.Integration) string {
	var b strings.Builder

	b.WriteString("# Generated by Human compiler — do not edit\n")
	fmt.Fprintf(&b, "# Integration: %s (messaging)\n\n", integ.Service)

	webhookEnv := "SLACK_WEBHOOK_URL"
	for _, envVar := range integ.Credentials {
		webhookEnv = envVar
		break
	}

	channel := ""
	if v, ok := integ.Config["channel"]; ok {
		channel = v
	}

	b.WriteString("import os\n")
	b.WriteString("from slack_sdk.webhook import WebhookClient\n\n")

	fmt.Fprintf(&b, "webhook = WebhookClient(os.environ.get('%s', ''))\n\n", webhookEnv)

	b.WriteString("async def send_slack_message(text: str, channel: str = None) -> None:\n")
	if channel != "" {
		fmt.Fprintf(&b, "    webhook.send(text=text, channel=channel or '%s')\n\n", channel)
	} else {
		b.WriteString("    webhook.send(text=text)\n\n")
	}

	b.WriteString("async def send_alert(message: str) -> None:\n")
	b.WriteString("    await send_slack_message(text=f':warning: {message}')\n")

	return b.String()
}

// generateOAuthService produces a Python OAuth service using authlib.
func generateOAuthService(integ *ir.Integration) string {
	var b strings.Builder

	b.WriteString("# Generated by Human compiler — do not edit\n")
	fmt.Fprintf(&b, "# Integration: %s (oauth)\n\n", integ.Service)

	serviceLower := strings.ToLower(integ.Service)

	// Determine credential env vars.
	clientIDEnv := strings.ToUpper(strings.ReplaceAll(integ.Service, " ", "_")) + "_CLIENT_ID"
	clientSecretEnv := strings.ToUpper(strings.ReplaceAll(integ.Service, " ", "_")) + "_CLIENT_SECRET"
	for key, envVar := range integ.Credentials {
		lower := strings.ToLower(key)
		if strings.Contains(lower, "secret") {
			clientSecretEnv = envVar
		} else if strings.Contains(lower, "id") || strings.Contains(lower, "client") {
			clientIDEnv = envVar
		}
	}

	b.WriteString("import os\n")
	b.WriteString("from authlib.integrations.starlette_client import OAuth\n\n")

	b.WriteString("oauth = OAuth()\n\n")

	// Select the right provider name.
	providerName := "google"
	if strings.Contains(serviceLower, "github") {
		providerName = "github"
	} else if strings.Contains(serviceLower, "facebook") {
		providerName = "facebook"
	}

	fmt.Fprintf(&b, "oauth.register(\n")
	fmt.Fprintf(&b, "    name='%s',\n", providerName)
	fmt.Fprintf(&b, "    client_id=os.environ.get('%s', ''),\n", clientIDEnv)
	fmt.Fprintf(&b, "    client_secret=os.environ.get('%s', ''),\n", clientSecretEnv)

	switch providerName {
	case "google":
		b.WriteString("    server_metadata_url='https://accounts.google.com/.well-known/openid-configuration',\n")
		b.WriteString("    client_kwargs={'scope': 'openid email profile'},\n")
	case "github":
		b.WriteString("    authorize_url='https://github.com/login/oauth/authorize',\n")
		b.WriteString("    access_token_url='https://github.com/login/oauth/access_token',\n")
		b.WriteString("    api_base_url='https://api.github.com/',\n")
		b.WriteString("    client_kwargs={'scope': 'user:email'},\n")
	case "facebook":
		b.WriteString("    authorize_url='https://www.facebook.com/v18.0/dialog/oauth',\n")
		b.WriteString("    access_token_url='https://graph.facebook.com/v18.0/oauth/access_token',\n")
		b.WriteString("    api_base_url='https://graph.facebook.com/v18.0/',\n")
		b.WriteString("    client_kwargs={'scope': 'email public_profile'},\n")
	}

	b.WriteString(")\n")

	return b.String()
}

// generateGenericService produces a minimal Python service for unknown integrations.
func generateGenericService(integ *ir.Integration) string {
	var b strings.Builder

	b.WriteString("# Generated by Human compiler — do not edit\n")
	fmt.Fprintf(&b, "# Integration: %s\n\n", integ.Service)

	b.WriteString("import os\n\n")

	if len(integ.Credentials) > 0 {
		b.WriteString("# Environment variables required:\n")
		for key, envVar := range integ.Credentials {
			fmt.Fprintf(&b, "#   %s: os.environ['%s']\n", key, envVar)
		}
		b.WriteString("\n")
	}

	className := toPascalCase(integ.Service) + "Service"
	fmt.Fprintf(&b, "class %s:\n", className)
	fmt.Fprintf(&b, "    service = '%s'\n", integ.Service)
	if integ.Purpose != "" {
		fmt.Fprintf(&b, "    purpose = '%s'\n", integ.Purpose)
	}
	b.WriteString("\n")

	b.WriteString("    def __init__(self):\n")
	if len(integ.Credentials) > 0 {
		for key, envVar := range integ.Credentials {
			safeKey := strings.ReplaceAll(key, " ", "_")
			fmt.Fprintf(&b, "        self.%s = os.environ.get('%s', '')\n", toSnakeCase(safeKey), envVar)
		}
	} else {
		b.WriteString("        pass\n")
	}

	return b.String()
}

// generateServiceInit produces a __init__.py that re-exports all service modules.
func generateServiceInit(files map[string]string) string {
	var b strings.Builder
	b.WriteString("# Generated by Human compiler — do not edit\n\n")

	for path := range files {
		if strings.HasSuffix(path, "__init__.py") {
			continue
		}
		// path is like "services/email_service.py"
		filename := strings.TrimPrefix(path, "services/")
		module := strings.TrimSuffix(filename, ".py")
		fmt.Fprintf(&b, "from .%s import *  # noqa: F401,F403\n", module)
	}

	return b.String()
}
