package python

import (
	"strings"

	"github.com/barun-bash/human/internal/ir"
)

// hasStorageIntegration returns true if the app has a storage integration.
func hasStorageIntegration(app *ir.Application) bool {
	for _, integ := range app.Integrations {
		if strings.ToLower(integ.Type) == "storage" {
			return true
		}
	}
	return false
}

// generateUploadRoutes generates a FastAPI upload route using python-multipart.
func generateUploadRoutes(app *ir.Application) string {
	var b strings.Builder

	b.WriteString(`# Generated by Human compiler — do not edit

from fastapi import APIRouter, UploadFile, File, HTTPException
from services.storage import upload_file
import time

router = APIRouter()

@router.post("/api/upload")
async def handle_upload(file: UploadFile = File(...)):
    if not file.filename:
        raise HTTPException(status_code=400, detail="No file provided")

    contents = await file.read()
    key = f"uploads/{int(time.time())}-{file.filename}"

    try:
        result = await upload_file(key, contents, file.content_type or "application/octet-stream")
        return {"key": result, "filename": file.filename, "size": len(contents)}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Upload failed: {str(e)}")
`)

	return b.String()
}
