package python

import (
	"fmt"
	"strings"

	"github.com/barun-bash/human/internal/ir"
)

// hasWebhookIntegration returns true if any integration has type "payment"
// and a "webhook_endpoint" config key.
func hasWebhookIntegration(app *ir.Application) bool {
	for _, integ := range app.Integrations {
		if integ.Type == "payment" {
			if _, ok := integ.Config["webhook_endpoint"]; ok {
				return true
			}
		}
	}
	return false
}

// generateWebhookRoutes generates a FastAPI webhook router file for Stripe webhooks.
func generateWebhookRoutes(app *ir.Application) string {
	var sb strings.Builder

	sb.WriteString(`# Generated by Human compiler — do not edit

from fastapi import APIRouter, Request, HTTPException
import stripe
import os

router = APIRouter()

`)

	// Determine the webhook secret env var — default to STRIPE_WEBHOOK_SECRET.
	webhookSecretEnv := "STRIPE_WEBHOOK_SECRET"
	for _, integ := range app.Integrations {
		if integ.Type == "payment" {
			for key, envVar := range integ.Credentials {
				if strings.Contains(strings.ToLower(key), "webhook") {
					webhookSecretEnv = envVar
					break
				}
			}
			break
		}
	}

	// Determine the endpoint path from config, default to /api/webhooks/stripe.
	endpointPath := "/api/webhooks/stripe"
	for _, integ := range app.Integrations {
		if integ.Type == "payment" {
			if v, ok := integ.Config["webhook_endpoint"]; ok && v != "" {
				endpointPath = v
			}
			break
		}
	}

	fmt.Fprintf(&sb, "@router.post(\"%s\")\n", endpointPath)
	sb.WriteString(`async def stripe_webhook(request: Request):
    payload = await request.body()
    sig_header = request.headers.get("stripe-signature")
`)
	fmt.Fprintf(&sb, "    endpoint_secret = os.getenv(\"%s\", \"\")\n", webhookSecretEnv)
	sb.WriteString(`
    try:
        event = stripe.Webhook.construct_event(payload, sig_header, endpoint_secret)
    except ValueError:
        raise HTTPException(status_code=400, detail="Invalid payload")
    except stripe.error.SignatureVerificationError:
        raise HTTPException(status_code=400, detail="Invalid signature")

    if event["type"] == "checkout.session.completed":
        session = event["data"]["object"]
        # Handle successful payment
        pass
    elif event["type"] == "payment_intent.succeeded":
        intent = event["data"]["object"]
        # Handle successful payment intent
        pass

    return {"status": "ok"}
`)

	return sb.String()
}

// hasOAuthIntegration returns true if any integration has type "oauth".
func hasOAuthIntegration(app *ir.Application) bool {
	for _, integ := range app.Integrations {
		if integ.Type == "oauth" {
			return true
		}
	}
	return false
}

// generateOAuthRoutes generates a FastAPI OAuth router for login/callback flows.
func generateOAuthRoutes(app *ir.Application) string {
	var sb strings.Builder

	sb.WriteString(`# Generated by Human compiler — do not edit

from fastapi import APIRouter, Request
from fastapi.responses import RedirectResponse
from authlib.integrations.starlette_client import OAuth
import os

router = APIRouter()
oauth = OAuth()

`)

	// Register each OAuth provider from integrations.
	for _, integ := range app.Integrations {
		if integ.Type != "oauth" {
			continue
		}

		serviceLower := strings.ToLower(integ.Service)

		providerName := "google"
		if strings.Contains(serviceLower, "github") {
			providerName = "github"
		} else if strings.Contains(serviceLower, "facebook") {
			providerName = "facebook"
		}

		// Determine credential env vars.
		clientIDEnv := strings.ToUpper(strings.ReplaceAll(integ.Service, " ", "_")) + "_CLIENT_ID"
		clientSecretEnv := strings.ToUpper(strings.ReplaceAll(integ.Service, " ", "_")) + "_CLIENT_SECRET"
		for key, envVar := range integ.Credentials {
			lower := strings.ToLower(key)
			if strings.Contains(lower, "secret") {
				clientSecretEnv = envVar
			} else if strings.Contains(lower, "id") || strings.Contains(lower, "client") {
				clientIDEnv = envVar
			}
		}

		fmt.Fprintf(&sb, "# Register %s provider\n", integ.Service)
		sb.WriteString("oauth.register(\n")
		fmt.Fprintf(&sb, "    name='%s',\n", providerName)
		fmt.Fprintf(&sb, "    client_id=os.getenv('%s'),\n", clientIDEnv)
		fmt.Fprintf(&sb, "    client_secret=os.getenv('%s'),\n", clientSecretEnv)

		switch providerName {
		case "google":
			sb.WriteString("    server_metadata_url='https://accounts.google.com/.well-known/openid-configuration',\n")
			sb.WriteString("    client_kwargs={'scope': 'openid email profile'},\n")
		case "github":
			sb.WriteString("    authorize_url='https://github.com/login/oauth/authorize',\n")
			sb.WriteString("    access_token_url='https://github.com/login/oauth/access_token',\n")
			sb.WriteString("    api_base_url='https://api.github.com/',\n")
			sb.WriteString("    client_kwargs={'scope': 'user:email'},\n")
		case "facebook":
			sb.WriteString("    authorize_url='https://www.facebook.com/v18.0/dialog/oauth',\n")
			sb.WriteString("    access_token_url='https://graph.facebook.com/v18.0/oauth/access_token',\n")
			sb.WriteString("    api_base_url='https://graph.facebook.com/v18.0/',\n")
			sb.WriteString("    client_kwargs={'scope': 'email public_profile'},\n")
		}

		sb.WriteString(")\n\n")
	}

	sb.WriteString(`@router.get("/auth/{provider}")
async def oauth_login(request: Request, provider: str):
    client = oauth.create_client(provider)
    redirect_uri = request.url_for('oauth_callback', provider=provider)
    return await client.authorize_redirect(request, redirect_uri)

@router.get("/auth/{provider}/callback")
async def oauth_callback(request: Request, provider: str):
    client = oauth.create_client(provider)
    token = await client.authorize_access_token(request)
    user_info = token.get('userinfo') or await client.userinfo()
    # Create/update user, generate JWT
    return {"token": "..."}
`)

	return sb.String()
}
