// Generated by Human compiler — do not edit

import React from 'react';
import { render, screen, fireEvent } from '@testing-library/react';
import { BrowserRouter } from 'react-router-dom';
import { ForgotPassword } from '../pages/forgot-password';

jest.mock('../api/client');

const renderPage = () => render(
  <BrowserRouter>
    <ForgotPassword />
  </BrowserRouter>
);

describe('ForgotPassword page', () => {
  it('should render without crashing', () => {
    renderPage();
  });

  it('should display a navigation bar with the app name Time Keeper on the left', () => {
    renderPage();
    expect(screen.getByText(/a navigation bar with the app name Time Keeper on the left/i)).toBeInTheDocument();
  });

  it('should display a heading Password recovery', () => {
    renderPage();
    expect(screen.getByText(/a heading Password recovery/i)).toBeInTheDocument();
  });

  it('should display text Enter the email address associated with your account to get a code', () => {
    renderPage();
    expect(screen.getByText(/text Enter the email address associated with your account to get a code/i)).toBeInTheDocument();
  });

  it('should handle clicking Send Recovery Email sends a password reset email', () => {
    renderPage();
    const button = screen.getByText(/Send Recovery Email sends a password reset email/i);
    fireEvent.click(button);
  });

  it('should display a link Back to Login', () => {
    renderPage();
    expect(screen.getByText(/a link Back to Login/i)).toBeInTheDocument();
  });

  it('should handle clicking Back to Login navigates to SignIn', () => {
    renderPage();
    const button = screen.getByText(/Back to Login navigates to SignIn/i);
    fireEvent.click(button);
  });

});
