// Generated by Human compiler — do not edit

import request from 'supertest';
import { app } from '../server';

describe('POST /api/login', () => {
  it('should succeed with valid request', async () => {
    const response = await request(app)
      .post('/api/login')
      .send({
        email: 'test-email',
        password: 'test-password',
      });

    expect(response.status).toBeLessThan(500);
  });

  it('should reject empty email', async () => {
    const response = await request(app)
      .post('/api/login')
      .send({
        email: '',
        password: 'valid-password',
      });

    expect(response.status).toBe(400);
    expect(response.body.error).toBeDefined();
  });

  it('should reject empty password', async () => {
    const response = await request(app)
      .post('/api/login')
      .send({
        email: 'valid-email',
        password: '',
      });

    expect(response.status).toBe(400);
    expect(response.body.error).toBeDefined();
  });

  it('should reject mismatched password', async () => {
    const response = await request(app)
      .post('/api/login')
      .send({
        email: 'valid-email',
        password: 'invalid',
      });

    expect(response.status).toBe(400);
    expect(response.body.error).toBeDefined();
  });

});
