// Generated by Human compiler — do not edit

import React from 'react';
import { render, screen, fireEvent } from '@testing-library/react';
import { BrowserRouter } from 'react-router-dom';
import { SignIn } from '../pages/sign-in';

jest.mock('../api/client');

const renderPage = () => render(
  <BrowserRouter>
    <SignIn />
  </BrowserRouter>
);

describe('SignIn page', () => {
  it('should render without crashing', () => {
    renderPage();
  });

  it('should display a navigation bar with the app name Time Keeper on the left', () => {
    renderPage();
    expect(screen.getByText(/a navigation bar with the app name Time Keeper on the left/i)).toBeInTheDocument();
  });

  it('should display a heading Sign in', () => {
    renderPage();
    expect(screen.getByText(/a heading Sign in/i)).toBeInTheDocument();
  });

  it('should display a Sign in with Google button with a Google icon', () => {
    renderPage();
    expect(screen.getByText(/a Sign in with Google button with a Google icon/i)).toBeInTheDocument();
  });

  it('should display social login icons for Slack, Microsoft Teams, Apple, and Facebook', () => {
    renderPage();
    expect(screen.getByText(/social login icons for Slack, Microsoft Teams, Apple, and Facebook/i)).toBeInTheDocument();
  });

  it('should display text or use your email to sign in:', () => {
    renderPage();
    expect(screen.getByText(/text or use your email to sign in:/i)).toBeInTheDocument();
  });

  it('should display a link I forgot my password', () => {
    renderPage();
    expect(screen.getByText(/a link I forgot my password/i)).toBeInTheDocument();
  });

  it('should handle clicking I forgot my password navigates to ForgotPassword', () => {
    renderPage();
    const button = screen.getByText(/I forgot my password navigates to ForgotPassword/i);
    fireEvent.click(button);
  });

  it('should handle clicking Sign In does Login with the email and password', () => {
    renderPage();
    const button = screen.getByText(/Sign In does Login with the email and password/i);
    fireEvent.click(button);
  });

  it('should display a link Sign in with Single Sign On', () => {
    renderPage();
    expect(screen.getByText(/a link Sign in with Single Sign On/i)).toBeInTheDocument();
  });

  it('should show loading state', () => {
    renderPage();
    expect(screen.getByText(/loading/i)).toBeInTheDocument();
  });

});
