package node

import (
	"fmt"
	"strings"

	"github.com/barun-bash/human/internal/ir"
)

// generateAuthMiddleware produces JWT authentication middleware.
func generateAuthMiddleware(app *ir.Application) string {
	var b strings.Builder

	b.WriteString("// Generated by Human compiler — do not edit\n\n")
	b.WriteString("import { Request, Response, NextFunction } from 'express';\n")
	b.WriteString("import jwt from 'jsonwebtoken';\n\n")

	// Extract JWT config from auth methods
	secret := "process.env.JWT_SECRET || 'change-me'"
	expiration := "'7d'"
	if app.Auth != nil {
		for _, m := range app.Auth.Methods {
			if m.Type == "jwt" {
				if exp, ok := m.Config["expiration"]; ok {
					expiration = fmt.Sprintf("'%s'", toJwtExpiry(exp))
				}
			}
		}
	}

	fmt.Fprintf(&b, "const JWT_SECRET = %s;\n", secret)
	fmt.Fprintf(&b, "export const JWT_EXPIRATION = %s;\n\n", expiration)

	// Extend Express Request type
	b.WriteString(`declare global {
  namespace Express {
    interface Request {
      userId?: string;
      userRole?: string;
    }
  }
}
`)

	// authenticate middleware
	b.WriteString(`
export function authenticate(req: Request, res: Response, next: NextFunction) {
  const header = req.headers.authorization;
  if (!header || !header.startsWith('Bearer ')) {
    return res.status(401).json({ error: 'Authentication required' });
  }

  const token = header.slice(7);
  try {
    const payload = jwt.verify(token, JWT_SECRET) as { userId: string; role?: string };
    req.userId = payload.userId;
    req.userRole = payload.role;
    next();
  } catch {
    return res.status(401).json({ error: 'Invalid or expired token' });
  }
}
`)

	// signToken helper
	b.WriteString(`
export function signToken(userId: string, role?: string): string {
  return jwt.sign({ userId, role }, JWT_SECRET, { expiresIn: JWT_EXPIRATION });
}
`)

	// requireRole middleware
	b.WriteString(`
export function requireRole(...roles: string[]) {
  return (req: Request, res: Response, next: NextFunction) => {
    if (!req.userRole || !roles.includes(req.userRole)) {
      return res.status(403).json({ error: 'Insufficient permissions' });
    }
    next();
  };
}
`)

	return b.String()
}

// toJwtExpiry converts human-readable duration to JWT format.
// "7 days" → "7d", "24 hours" → "24h", "30 minutes" → "30m"
func toJwtExpiry(s string) string {
	lower := strings.ToLower(strings.TrimSpace(s))
	parts := strings.Fields(lower)
	if len(parts) < 2 {
		return "7d"
	}

	num := parts[0]
	unit := parts[1]

	switch {
	case strings.HasPrefix(unit, "day"):
		return num + "d"
	case strings.HasPrefix(unit, "hour"):
		return num + "h"
	case strings.HasPrefix(unit, "minute") || strings.HasPrefix(unit, "min"):
		return num + "m"
	case strings.HasPrefix(unit, "second") || strings.HasPrefix(unit, "sec"):
		return num + "s"
	default:
		return num + "d"
	}
}
