package node

import (
	"fmt"
	"strings"

	"github.com/barun-bash/human/internal/ir"
)

// generateServer produces the server.ts entry point with Express setup.
func generateServer(app *ir.Application) string {
	var b strings.Builder

	b.WriteString("// Generated by Human compiler — do not edit\n\n")
	b.WriteString("import express from 'express';\n")
	b.WriteString("import cors from 'cors';\n")
	b.WriteString("import { router } from './routes';\n")
	b.WriteString("import { errorHandler } from './middleware/errors';\n\n")

	b.WriteString("const app = express();\n")
	fmt.Fprintf(&b, "const PORT = process.env.PORT || %d;\n\n", 3001)

	// Core middleware
	b.WriteString("// Middleware\n")
	b.WriteString("app.use(cors());\n")
	b.WriteString("app.use(express.json());\n")

	// Rate limiting from auth rules
	if hasRateLimiting(app) {
		b.WriteString("// TODO: configure rate limiting (see auth rules in .human file)\n")
	}

	b.WriteString("\n// Routes\n")
	b.WriteString("app.use('/api', router);\n\n")

	// Health check
	b.WriteString("// Health check\n")
	b.WriteString("app.get('/health', (_req, res) => {\n")
	b.WriteString("  res.json({ status: 'ok' });\n")
	b.WriteString("});\n\n")

	// Error handler (must be last)
	b.WriteString("// Error handling (must be registered last)\n")
	b.WriteString("app.use(errorHandler);\n\n")

	// Start
	b.WriteString("app.listen(PORT, () => {\n")
	fmt.Fprintf(&b, "  console.log(`%s server running on port ${PORT}`);\n", appName(app))
	b.WriteString("});\n\n")
	b.WriteString("export { app };\n")

	return b.String()
}

// hasRateLimiting checks if the app's auth rules mention rate limiting.
func hasRateLimiting(app *ir.Application) bool {
	if app.Auth == nil {
		return false
	}
	for _, rule := range app.Auth.Rules {
		if strings.Contains(strings.ToLower(rule.Text), "rate limit") {
			return true
		}
	}
	return false
}

// appName returns the application name or a default.
func appName(app *ir.Application) string {
	if app.Name != "" {
		return app.Name
	}
	return "App"
}
