package node

import (
	"strings"

	"github.com/barun-bash/human/internal/ir"
)

// hasStorageIntegration returns true if the app has a storage integration.
func hasStorageIntegration(app *ir.Application) bool {
	for _, integ := range app.Integrations {
		if strings.ToLower(integ.Type) == "storage" {
			return true
		}
	}
	return false
}

// generateUploadRoute produces a TypeScript Express route for file uploads using multer.
func generateUploadRoute(app *ir.Application) string {
	var b strings.Builder

	b.WriteString("// Generated by Human compiler — do not edit\n\n")
	b.WriteString("import { Router, Request, Response } from 'express';\n")
	b.WriteString("import multer from 'multer';\n")
	b.WriteString("import { uploadFile } from '../services/storage';\n\n")

	b.WriteString("const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 10 * 1024 * 1024 } });\n\n")
	b.WriteString("export const router = Router();\n\n")

	b.WriteString("router.post('/upload', upload.single('file'), async (req: Request, res: Response) => {\n")
	b.WriteString("  try {\n")
	b.WriteString("    if (!req.file) {\n")
	b.WriteString("      return res.status(400).json({ error: 'No file provided' });\n")
	b.WriteString("    }\n\n")
	b.WriteString("    const key = `uploads/${Date.now()}-${req.file.originalname}`;\n")
	b.WriteString("    const result = await uploadFile(key, req.file.buffer, req.file.mimetype);\n\n")
	b.WriteString("    res.json({ key: result, filename: req.file.originalname, size: req.file.size });\n")
	b.WriteString("  } catch (err) {\n")
	b.WriteString("    console.error('Upload error:', err);\n")
	b.WriteString("    res.status(500).json({ error: 'Upload failed' });\n")
	b.WriteString("  }\n")
	b.WriteString("});\n")

	return b.String()
}
