package node

import (
	"strings"

	"github.com/barun-bash/human/internal/ir"
)

// generateWebhookRoutes produces webhook endpoint handlers for payment integrations.
func generateWebhookRoutes(app *ir.Application) string {
	var b strings.Builder

	b.WriteString("// Generated by Human compiler — do not edit\n\n")
	b.WriteString("import { Router, Request, Response } from 'express';\n")

	// Check for Stripe payment integration with webhook
	hasStripeWebhook := false
	for _, integ := range app.Integrations {
		if integ.Type == "payment" {
			if _, ok := integ.Config["webhook_endpoint"]; ok {
				hasStripeWebhook = true
				b.WriteString("import { verifyWebhookSignature } from '../services/stripe';\n")
			}
		}
	}

	b.WriteString("\nconst router = Router();\n\n")

	if hasStripeWebhook {
		b.WriteString("// Stripe webhook handler\n")
		b.WriteString("router.post('/stripe', async (req: Request, res: Response) => {\n")
		b.WriteString("  try {\n")
		b.WriteString("    const signature = req.headers['stripe-signature'] as string;\n")
		b.WriteString("    const event = verifyWebhookSignature(\n")
		b.WriteString("      req.body,\n")
		b.WriteString("      signature,\n")
		b.WriteString("      process.env.STRIPE_WEBHOOK_SECRET || '',\n")
		b.WriteString("    );\n\n")
		b.WriteString("    switch (event.type) {\n")
		b.WriteString("      case 'checkout.session.completed':\n")
		b.WriteString("        // TODO: handle successful payment\n")
		b.WriteString("        break;\n")
		b.WriteString("      case 'payment_intent.payment_failed':\n")
		b.WriteString("        // TODO: handle failed payment\n")
		b.WriteString("        break;\n")
		b.WriteString("      default:\n")
		b.WriteString("        console.log(`Unhandled webhook event: ${event.type}`);\n")
		b.WriteString("    }\n\n")
		b.WriteString("    res.json({ received: true });\n")
		b.WriteString("  } catch (err) {\n")
		b.WriteString("    console.error('Webhook error:', err);\n")
		b.WriteString("    res.status(400).json({ error: 'Webhook verification failed' });\n")
		b.WriteString("  }\n")
		b.WriteString("});\n\n")
	}

	b.WriteString("export { router };\n")
	return b.String()
}

// hasWebhookIntegration returns true if any integration has a webhook endpoint configured.
func hasWebhookIntegration(app *ir.Application) bool {
	for _, integ := range app.Integrations {
		if integ.Type == "payment" {
			if _, ok := integ.Config["webhook_endpoint"]; ok {
				return true
			}
		}
	}
	return false
}
