-- Generated by Human compiler — do not edit
-- Migration: 001_initial

BEGIN;

-- ── Enum Types ──

CREATE TYPE user_role AS ENUM ('employee', 'manager', 'admin');

-- ── Tables ──

CREATE TABLE users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  role user_role NOT NULL,
  avatar TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ── Indexes ──

CREATE INDEX idx_users_email ON users (email);

COMMIT;
