package svelte

import (
	"strings"

	"github.com/barun-bash/human/internal/ir"
)

// generateAuthStore produces src/lib/auth.ts with a simple auth module
// that manages authentication state via localStorage token.
func generateAuthStore() string {
	var b strings.Builder

	b.WriteString("// Generated by Human compiler — do not edit\n\n")
	b.WriteString("export const auth = {\n")
	b.WriteString("  get isAuthenticated(): boolean {\n")
	b.WriteString("    if (typeof localStorage === 'undefined') return false;\n")
	b.WriteString("    return !!localStorage.getItem('token');\n")
	b.WriteString("  },\n\n")
	b.WriteString("  login(token: string): void {\n")
	b.WriteString("    localStorage.setItem('token', token);\n")
	b.WriteString("  },\n\n")
	b.WriteString("  logout(): void {\n")
	b.WriteString("    localStorage.removeItem('token');\n")
	b.WriteString("  },\n")
	b.WriteString("};\n")

	return b.String()
}

// generateLayoutGuard produces src/routes/+layout.ts with a SvelteKit load
// function that redirects unauthenticated users away from protected routes.
func generateLayoutGuard(app *ir.Application) string {
	// Collect public paths from pages
	publicPaths := []string{"/"}
	for _, page := range app.Pages {
		if isPublicPage(page.Name) {
			name := strings.ToLower(page.Name)
			if name != "home" && name != "index" {
				publicPaths = append(publicPaths, "/"+toKebabCase(page.Name))
			}
		}
	}

	var b strings.Builder

	b.WriteString("// Generated by Human compiler — do not edit\n\n")
	b.WriteString("import { redirect } from '@sveltejs/kit';\n")
	b.WriteString("import { browser } from '$app/environment';\n")
	b.WriteString("import type { LayoutLoad } from './$types';\n\n")

	b.WriteString("const publicPaths = [")
	for i, p := range publicPaths {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString("'" + p + "'")
	}
	b.WriteString("];\n\n")

	b.WriteString("export const load: LayoutLoad = ({ url }) => {\n")
	b.WriteString("  if (browser && !publicPaths.includes(url.pathname) && !localStorage.getItem('token')) {\n")
	b.WriteString("    throw redirect(302, '/login');\n")
	b.WriteString("  }\n")
	b.WriteString("};\n")

	return b.String()
}

// isPublicPage returns true for pages that should not require authentication.
// These are pages that unauthenticated users need access to.
func isPublicPage(name string) bool {
	lower := strings.ToLower(name)
	return lower == "home" || lower == "login" || lower == "signup" ||
		lower == "sign-up" || lower == "register" || lower == "landing"
}
