package svelte

import (
	"fmt"
	"strings"

	"github.com/barun-bash/human/internal/ir"
)

func generateTypes(app *ir.Application) string {
	var b strings.Builder
	b.WriteString("// Generated by Human compiler — do not edit\n\n")

	for i, model := range app.Data {
		if i > 0 {
			b.WriteString("\n")
		}
		fmt.Fprintf(&b, "export interface %s {\n", model.Name)
		b.WriteString("  id: string;\n")

		for _, f := range model.Fields {
			optional := ""
			if !f.Required {
				optional = "?"
			}
			fieldType := tsType(f.Type)
			if f.Type == "enum" && len(f.EnumValues) > 0 {
				fieldType = tsEnumType(f.EnumValues)
			}
			fmt.Fprintf(&b, "  %s%s: %s;\n", f.Name, optional, fieldType)
		}

		for _, rel := range model.Relations {
			switch rel.Kind {
			case "belongs_to":
				fmt.Fprintf(&b, "  %sId: string;\n", toCamelCase(rel.Target))
				fmt.Fprintf(&b, "  %s?: %s;\n", toCamelCase(rel.Target), rel.Target)
			case "has_many", "has_many_through":
				fmt.Fprintf(&b, "  %s?: %s[];\n", toCamelCase(rel.Target)+"s", rel.Target)
			}
		}
		b.WriteString("}\n")
	}

	return b.String()
}

func generateApi(app *ir.Application) string {
	var b strings.Builder
	b.WriteString(`// Generated by Human compiler — do not edit

export interface ApiResponse<T> {
  data: T;
  error?: string;
}

const API_BASE_URL = import.meta.env?.VITE_API_URL || '';

async function request<T>(
  method: string,
  path: string,
  body?: Record<string, unknown>,
): Promise<ApiResponse<T>> {
  let token: string | null = null;
  if (typeof localStorage !== 'undefined') {
    token = localStorage.getItem('token');
  }
  const headers: Record<string, string> = {
    'Content-Type': 'application/json',
  };
  if (token) {
    headers['Authorization'] = ` + "`Bearer ${token}`" + `;
  }
  const res = await fetch(` + "`${API_BASE_URL}${path}`" + `, {
    method,
    headers,
    body: body ? JSON.stringify(body) : undefined,
  });
  return res.json();
}
`)

	for _, ep := range app.APIs {
		b.WriteString("\n")
		funcName := toCamelCase(ep.Name)
		method := httpMethod(ep.Name)
		path := apiPath(ep.Name)

		if len(ep.Params) > 0 {
			paramFields := make([]string, len(ep.Params))
			for i, p := range ep.Params {
				paramName := toCamelCase(p.Name)
				paramFields[i] = fmt.Sprintf("%s: string", paramName)
			}
			paramType := fmt.Sprintf("{ %s }", strings.Join(paramFields, "; "))
			fmt.Fprintf(&b, "export async function %s(params: %s): Promise<ApiResponse<unknown>> {\n", funcName, paramType)
			if method == "GET" {
				fmt.Fprintf(&b, "  return request<unknown>('%s', '%s');\n", method, path)
			} else {
				fmt.Fprintf(&b, "  return request<unknown>('%s', '%s', params as unknown as Record<string, unknown>);\n", method, path)
			}
		} else {
			fmt.Fprintf(&b, "export async function %s(): Promise<ApiResponse<unknown>> {\n", funcName)
			fmt.Fprintf(&b, "  return request<unknown>('%s', '%s');\n", method, path)
		}
		b.WriteString("}\n")
	}

	return b.String()
}

func generateLayout(app *ir.Application) string {
	var b strings.Builder
	b.WriteString("<!-- Generated by Human compiler — do not edit -->\n")
	b.WriteString("<script lang=\"ts\">\n")
	b.WriteString("  let { children } = $props();\n")
	b.WriteString("</script>\n\n")

	b.WriteString("<nav>\n")
	for _, page := range app.Pages {
		routePath := "/"
		if strings.ToLower(page.Name) != "home" && strings.ToLower(page.Name) != "index" {
			routePath = "/" + toKebabCase(page.Name)
		}
		fmt.Fprintf(&b, "  <a href=\"%s\">%s</a>\n", routePath, page.Name)
	}
	b.WriteString("</nav>\n\n")

	b.WriteString("<main>\n")
	b.WriteString("  {@render children()}\n")
	b.WriteString("</main>\n")

	return b.String()
}

func generateErrorPage() string {
	return `<!-- Generated by Human compiler — do not edit -->
<script lang="ts">
  import { page } from '$app/stores';
</script>

<div style="text-align:center;padding:4rem">
  <h1>{$page.status}</h1>
  <p>{$page.error?.message ?? 'Page not found'}</p>
</div>
`
}
