package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
)

func runGenerate(args []string) error {
	fs := flag.NewFlagSet("generate", flag.ExitOnError)
	irFile := fs.String("ir", "", "Path to IR JSON file")
	outputDir := fs.String("output", "", "Output directory")
	settings := fs.String("settings", "", "Plugin settings JSON")
	fs.Parse(args)

	if *irFile == "" || *outputDir == "" {
		return fmt.Errorf("--ir and --output are required")
	}

	// Read the IR.
	data, err := os.ReadFile(*irFile)
	if err != nil {
		return fmt.Errorf("reading IR: %w", err)
	}

	var app map[string]interface{}
	if err := json.Unmarshal(data, &app); err != nil {
		return fmt.Errorf("parsing IR: %w", err)
	}

	// Parse settings if provided.
	var pluginSettings map[string]string
	if *settings != "" {
		if err := json.Unmarshal([]byte(*settings), &pluginSettings); err != nil {
			return fmt.Errorf("parsing settings: %w", err)
		}
	}

	// Create output directory.
	if err := os.MkdirAll(*outputDir, 0755); err != nil {
		return fmt.Errorf("creating output dir: %w", err)
	}

	// TODO: Generate your backend code here.
	// The IR contains the full application specification.
	// Write generated files to outputDir.

	appName, _ := app["name"].(string)
	if appName == "" {
		appName = "app"
	}

	content := fmt.Sprintf("// Generated by test-plugin plugin for %s\n", appName)
	outPath := filepath.Join(*outputDir, "generated.txt")
	return os.WriteFile(outPath, []byte(content), 0644)
}
