// Generated by Human compiler — do not edit

export interface User {
  id: string;
  name: string;
  email: string;
  password: string;
  role: "employee" | "manager" | "admin";
  avatar?: string;
  created: string;
}
