// Generated by Human compiler — do not edit

import express from 'express';
import cors from 'cors';
import { router } from './routes';
import { errorHandler } from './middleware/errors';

const app = express();
const PORT = process.env.PORT || 3000;

// Middleware
app.use(cors());
app.use(express.json());
// TODO: configure rate limiting (see auth rules in .human file)

// Routes
app.use('/api', router);

// Health check
app.get('/health', (_req, res) => {
  res.json({ status: 'ok' });
});

// Error handling (must be registered last)
app.use(errorHandler);

app.listen(PORT, () => {
  console.log(`TimeKeeper server running on port ${PORT}`);
});

export { app };
