// Generated by Human compiler — do not edit

import { useState } from 'react';
import { useNavigate } from 'react-router-dom';

export default function ForgotPasswordPage() {
  const navigate = useNavigate();
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);

  const handleSendCode = async () => {
    setLoading(true);
    setError('');
    try {
      // TODO: call SendResetCode API
    } catch (e: any) {
      setError(e.message || 'Failed to send code');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="forgot-password-page">
      <h2>Forgot your password?</h2>
      <p>Enter your email and we'll send you a verification code</p>
      <input type="email" placeholder="Email" />
      <button onClick={handleSendCode}>Send Code</button>
      <button onClick={() => navigate('/sign-in')}>Back to Sign In</button>
      {error && <div className="alert alert-error">{error}</div>}
      {loading && (
        <div className="loading-spinner">
          <div className="spinner" />
        </div>
      )}
    </div>
  );
}
