// Generated by Human compiler — do not edit

import { useState } from 'react';

export default function ResetPasswordPage() {
  const [success, setSuccess] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);

  const handleReset = async () => {
    setLoading(true);
    setError('');
    setSuccess('');
    try {
      // TODO: call ResetUserPassword API
      // check that new password matches confirm password
      setSuccess('Password reset successfully');
    } catch (e: any) {
      setError(e.message || 'Failed to reset password');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="reset-password-page">
      <h2>Set a new password</h2>
      <input type="password" placeholder="New Password" />
      <input type="password" placeholder="Confirm Password" />
      <button onClick={handleReset}>Reset Password</button>
      {error && <div className="alert alert-error">{error}</div>}
      {success && <div className="alert alert-success">{success}</div>}
      {loading && (
        <div className="loading-spinner">
          <div className="spinner" />
        </div>
      )}
    </div>
  );
}
