// Generated by Human compiler — do not edit

import { useState } from 'react';
import { useNavigate } from 'react-router-dom';

export default function SignUpPage() {
  const navigate = useNavigate();
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);

  const handleSignUp = async () => {
    setLoading(true);
    setError('');
    try {
      // TODO: call CreateAccount API
      // check that password matches confirm password
    } catch (e: any) {
      setError(e.message || 'Sign up failed');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="sign-up-page">
      <h1>TimeKeeper</h1>
      <p>Create your account</p>
      <input type="text" placeholder="Name" />
      <input type="email" placeholder="Email" />
      <input type="password" placeholder="Password" />
      <input type="password" placeholder="Confirm Password" />
      <button onClick={handleSignUp}>Sign Up</button>
      <button onClick={() => navigate('/sign-in')}>Sign In</button>
      {error && <div className="alert alert-error">{error}</div>}
      {loading && (
        <div className="loading-spinner">
          <div className="spinner" />
        </div>
      )}
    </div>
  );
}
