// Generated by Human compiler — do not edit

import { useState } from 'react';
import { useNavigate } from 'react-router-dom';

export default function SignInPage() {
  const navigate = useNavigate();
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);

  const handleLogin = async () => {
    setLoading(true);
    setError('');
    try {
      // TODO: call Login API
    } catch (e: any) {
      setError(e.message || 'Login failed');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="sign-in-page">
      <h1>TimeKeeper</h1>
      <p>Track your time, own your day</p>
      <input type="email" placeholder="Email" />
      <input type="password" placeholder="Password" />
      <label><input type="checkbox" /> Remember me</label>
      <button onClick={handleLogin}>Sign In</button>
      <button onClick={() => navigate('/forgot-password')}>Forgot Password?</button>
      <button onClick={() => navigate('/sign-up')}>Sign Up</button>
      <button onClick={() => {/* TODO: Google OAuth */}}>Continue with Google</button>
      <button onClick={() => {/* TODO: Slack OAuth */}}>Continue with Slack</button>
      {error && <div className="alert alert-error">{error}</div>}
      {loading && (
        <div className="loading-spinner">
          <div className="spinner" />
        </div>
      )}
    </div>
  );
}
