// Generated by Human compiler — do not edit

import { useState } from 'react';
import { useNavigate } from 'react-router-dom';

export default function VerifyCodePage() {
  const navigate = useNavigate();
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);

  const handleVerify = async () => {
    setLoading(true);
    setError('');
    try {
      // TODO: call VerifyResetCode API
    } catch (e: any) {
      setError(e.message || 'Verification failed');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="verify-code-page">
      <h2>Check your email</h2>
      <p>Enter the 6-digit code we sent to your email</p>
      <input type="text" placeholder="Verification Code" />
      <button onClick={handleVerify}>Verify</button>
      <button onClick={() => {/* TODO: call SendResetCode API */}}>Resend Code</button>
      <button onClick={() => navigate('/sign-in')}>Back to Sign In</button>
      {error && <div className="alert alert-error">{error}</div>}
      {loading && (
        <div className="loading-spinner">
          <div className="spinner" />
        </div>
      )}
    </div>
  );
}
