package docker

import (
	"fmt"
	"strings"

	"github.com/barun-bash/human/internal/ir"
)

// generateDockerCompose produces a docker-compose.yml wiring postgres, backend, and frontend.
func generateDockerCompose(app *ir.Application) string {
	var b strings.Builder
	name := AppNameLower(app)
	db := DbName(app)
	port := BackendPort(app)
	backendDir := BackendDir(app)

	b.WriteString("# Generated by Human compiler — do not edit\n\n")

	b.WriteString("services:\n")

	// PostgreSQL
	b.WriteString("  db:\n")
	b.WriteString("    image: postgres:16-alpine\n")
	b.WriteString("    restart: unless-stopped\n")
	b.WriteString("    environment:\n")
	b.WriteString("      POSTGRES_USER: postgres\n")
	b.WriteString("      POSTGRES_PASSWORD: postgres\n")
	fmt.Fprintf(&b, "      POSTGRES_DB: %s\n", db)
	b.WriteString("    ports:\n")
	b.WriteString("      - \"5432:5432\"\n")
	b.WriteString("    volumes:\n")
	fmt.Fprintf(&b, "      - %s-data:/var/lib/postgresql/data\n", name)
	b.WriteString("\n")

	// Backend
	b.WriteString("  backend:\n")
	b.WriteString("    build:\n")
	fmt.Fprintf(&b, "      context: ./%s\n", backendDir)
	b.WriteString("    restart: unless-stopped\n")
	b.WriteString("    ports:\n")
	fmt.Fprintf(&b, "      - \"%s:%s\"\n", port, port)
	b.WriteString("    depends_on:\n")
	b.WriteString("      - db\n")
	b.WriteString("    environment:\n")
	fmt.Fprintf(&b, "      DATABASE_URL: postgresql://postgres:postgres@db:5432/%s?schema=public\n", db)
	b.WriteString("      JWT_SECRET: ${JWT_SECRET}\n")
	fmt.Fprintf(&b, "      PORT: \"%s\"\n", port)

	// Integration env vars (credentials + config-derived)
	for _, integ := range app.Integrations {
		for _, envVar := range integ.Credentials {
			fmt.Fprintf(&b, "      %s: ${%s}\n", envVar, envVar)
		}
		for _, ev := range configEnvVars(integ) {
			fmt.Fprintf(&b, "      %s: ${%s}\n", ev.Name, ev.Name)
		}
	}
	b.WriteString("\n")

	// Frontend (only when a frontend framework is configured)
	if hasFrontend(app) {
		feDir := FrontendDir(app)
		feEnvName := FrontendAPIEnvName(app)
		b.WriteString("  frontend:\n")
		b.WriteString("    build:\n")
		fmt.Fprintf(&b, "      context: ./%s\n", feDir)
		b.WriteString("      args:\n")
		fmt.Fprintf(&b, "        %s: http://localhost:%s\n", feEnvName, port)
		b.WriteString("    restart: unless-stopped\n")
		b.WriteString("    ports:\n")
		b.WriteString("      - \"80:80\"\n")
		b.WriteString("    depends_on:\n")
		b.WriteString("      - backend\n")
		b.WriteString("\n")
	}

	// Volumes
	b.WriteString("volumes:\n")
	fmt.Fprintf(&b, "  %s-data:\n", name)

	return b.String()
}
