package docker

import (
	"fmt"
	"strings"

	"github.com/barun-bash/human/internal/ir"
)

// generateDockerCompose produces a docker-compose.yml wiring postgres, backend, and frontend.
func generateDockerCompose(app *ir.Application) string {
	var b strings.Builder
	name := AppNameLower(app)
	db := DbName(app)

	b.WriteString("# Generated by Human compiler — do not edit\n\n")

	b.WriteString("services:\n")

	// PostgreSQL
	b.WriteString("  db:\n")
	b.WriteString("    image: postgres:16-alpine\n")
	b.WriteString("    restart: unless-stopped\n")
	b.WriteString("    environment:\n")
	b.WriteString("      POSTGRES_USER: postgres\n")
	b.WriteString("      POSTGRES_PASSWORD: postgres\n")
	fmt.Fprintf(&b, "      POSTGRES_DB: %s\n", db)
	b.WriteString("    ports:\n")
	b.WriteString("      - \"5432:5432\"\n")
	b.WriteString("    volumes:\n")
	fmt.Fprintf(&b, "      - %s-data:/var/lib/postgresql/data\n", name)
	b.WriteString("\n")

	// Backend
	b.WriteString("  backend:\n")
	b.WriteString("    build:\n")
	b.WriteString("      context: ./node\n")
	b.WriteString("    restart: unless-stopped\n")
	b.WriteString("    ports:\n")
	b.WriteString("      - \"3000:3000\"\n")
	b.WriteString("    depends_on:\n")
	b.WriteString("      - db\n")
	b.WriteString("    environment:\n")
	fmt.Fprintf(&b, "      DATABASE_URL: postgresql://postgres:postgres@db:5432/%s?schema=public\n", db)
	b.WriteString("      JWT_SECRET: ${JWT_SECRET}\n")
	b.WriteString("      PORT: \"3000\"\n")

	// Integration env vars
	for _, integ := range app.Integrations {
		for _, envVar := range integ.Credentials {
			fmt.Fprintf(&b, "      %s: ${%s}\n", envVar, envVar)
		}
	}
	b.WriteString("\n")

	// Frontend
	b.WriteString("  frontend:\n")
	b.WriteString("    build:\n")
	b.WriteString("      context: ./react\n")
	b.WriteString("      args:\n")
	b.WriteString("        VITE_API_URL: http://localhost:3000\n")
	b.WriteString("    restart: unless-stopped\n")
	b.WriteString("    ports:\n")
	b.WriteString("      - \"80:80\"\n")
	b.WriteString("    depends_on:\n")
	b.WriteString("      - backend\n")
	b.WriteString("\n")

	// Volumes
	b.WriteString("volumes:\n")
	fmt.Fprintf(&b, "  %s-data:\n", name)

	return b.String()
}
