package docker

import (
	"strings"

	"github.com/barun-bash/human/internal/ir"
)

// generateBackendDockerfile produces a Dockerfile for the Node + Express backend.
func generateBackendDockerfile(app *ir.Application) string {
	var b strings.Builder

	b.WriteString("# Generated by Human compiler — do not edit\n\n")
	b.WriteString("FROM node:20-alpine AS builder\n\n")
	b.WriteString("WORKDIR /app\n\n")

	// Install dependencies
	b.WriteString("# Install dependencies\n")
	b.WriteString("COPY package.json package-lock.json* ./\n")
	b.WriteString("RUN npm ci\n\n")

	// Copy Prisma schema and generate client
	b.WriteString("# Generate Prisma client\n")
	b.WriteString("COPY prisma ./prisma\n")
	b.WriteString("RUN npx prisma generate\n\n")

	// Copy source and build
	b.WriteString("# Copy source and build\n")
	b.WriteString("COPY . .\n")
	b.WriteString("RUN npm run build\n\n")

	// Production stage
	b.WriteString("# Production\n")
	b.WriteString("FROM node:20-alpine\n\n")
	b.WriteString("WORKDIR /app\n\n")

	b.WriteString("COPY --from=builder /app/package.json ./\n")
	b.WriteString("COPY --from=builder /app/node_modules ./node_modules\n")
	b.WriteString("COPY --from=builder /app/dist ./dist\n")
	b.WriteString("COPY --from=builder /app/prisma ./prisma\n\n")

	b.WriteString("EXPOSE 3000\n\n")
	b.WriteString("CMD [\"node\", \"dist/server.js\"]\n")

	_ = app // used for future customization
	return b.String()
}

// generateFrontendDockerfile produces a multi-stage Dockerfile for the React frontend.
func generateFrontendDockerfile(app *ir.Application) string {
	var b strings.Builder

	b.WriteString("# Generated by Human compiler — do not edit\n\n")

	// Build stage
	b.WriteString("# Build stage\n")
	b.WriteString("FROM node:20-alpine AS builder\n\n")
	b.WriteString("WORKDIR /app\n\n")

	b.WriteString("COPY package.json package-lock.json* ./\n")
	b.WriteString("RUN npm ci\n\n")

	b.WriteString("COPY . .\n\n")

	// Vite inlines env vars at build time — the ARG must be declared
	// before `npm run build` so that VITE_API_URL is available.
	b.WriteString("ARG VITE_API_URL\n")
	b.WriteString("ENV VITE_API_URL=$VITE_API_URL\n\n")

	b.WriteString("RUN npm run build\n\n")

	// Serve stage
	b.WriteString("# Serve stage\n")
	b.WriteString("FROM nginx:alpine\n\n")

	b.WriteString("COPY --from=builder /app/dist /usr/share/nginx/html\n\n")

	// SPA routing: redirect all paths to index.html
	b.WriteString("# SPA routing\n")
	b.WriteString("RUN printf 'server {\\n\\\n")
	b.WriteString("  listen 80;\\n\\\n")
	b.WriteString("  location / {\\n\\\n")
	b.WriteString("    root /usr/share/nginx/html;\\n\\\n")
	b.WriteString("    try_files $uri $uri/ /index.html;\\n\\\n")
	b.WriteString("  }\\n\\\n")
	b.WriteString("}\\n' > /etc/nginx/conf.d/default.conf\n\n")

	b.WriteString("EXPOSE 80\n\n")
	b.WriteString("CMD [\"nginx\", \"-g\", \"daemon off;\"]\n")

	_ = app
	return b.String()
}
