package docker

import (
	"fmt"
	"strings"

	"github.com/barun-bash/human/internal/ir"
)

// generatePackageJSON produces a root package.json with orchestration scripts.
func generatePackageJSON(app *ir.Application) string {
	var b strings.Builder
	name := AppNameLower(app)

	b.WriteString("{\n")
	fmt.Fprintf(&b, "  \"name\": \"%s\",\n", name)
	b.WriteString("  \"version\": \"0.1.0\",\n")
	b.WriteString("  \"private\": true,\n")
	fmt.Fprintf(&b, "  \"description\": \"%s — generated by Human compiler\",\n", app.Name)
	b.WriteString("  \"scripts\": {\n")
	b.WriteString("    \"dev\": \"docker compose up --build\",\n")
	b.WriteString("    \"build\": \"docker compose build\",\n")
	b.WriteString("    \"start\": \"docker compose up -d\",\n")
	b.WriteString("    \"stop\": \"docker compose down\",\n")
	b.WriteString("    \"db:migrate\": \"cd node && npx prisma migrate deploy\",\n")
	b.WriteString("    \"db:seed\": \"cd node && npx prisma db seed\",\n")
	b.WriteString("    \"db:studio\": \"cd node && npx prisma studio\"\n")
	b.WriteString("  }\n")
	b.WriteString("}\n")

	return b.String()
}
