package vue

import (
	"strings"

	"github.com/barun-bash/human/internal/ir"
)

func generateApp(app *ir.Application) string {
	var b strings.Builder

	b.WriteString("<!-- Generated by Human compiler — do not edit -->\\n")
	b.WriteString("<script setup lang=\"ts\">\\n")
	b.WriteString("</script>\\n\\n")
	b.WriteString("<template>\\n")
	b.WriteString("  <div id=\"app\">\\n")
	b.WriteString("    <router-view></router-view>\\n")
	b.WriteString("  </div>\\n")
	b.WriteString("</template>\\n")

	return b.String()
}
