package vue

import (
	"strings"

	"github.com/barun-bash/human/internal/ir"
)

func generateApp(app *ir.Application) string {
	var b strings.Builder

	systemID := ""
	if app.Theme != nil {
		systemID = app.Theme.DesignSystem
	}

	b.WriteString("<!-- Generated by Human compiler — do not edit -->\n")
	b.WriteString("<script setup lang=\"ts\">\n")

	// Imports based on design system
	switch systemID {
	case "material":
		b.WriteString("import vuetify from './plugins/vuetify';\n")
	case "ant":
		b.WriteString("import Antd from 'ant-design-vue';\n")
		b.WriteString("import 'ant-design-vue/dist/reset.css';\n")
	}

	// Import global CSS if theme is configured
	if app.Theme != nil {
		b.WriteString("import './assets/global.css';\n")
	}

	b.WriteString("</script>\n\n")

	b.WriteString("<template>\n")

	// Wrap in design system root component if needed
	switch systemID {
	case "material":
		b.WriteString("  <v-app>\n")
		b.WriteString("    <router-view></router-view>\n")
		b.WriteString("  </v-app>\n")
	default:
		b.WriteString("  <div id=\"app\">\n")
		b.WriteString("    <router-view></router-view>\n")
		b.WriteString("  </div>\n")
	}

	b.WriteString("</template>\n")

	return b.String()
}
