package vue

import (
	"strings"

	"github.com/barun-bash/human/internal/ir"
)

// generateAuthComposable produces src/composables/useAuth.ts with a Vue 3
// composable that manages authentication state via localStorage token.
func generateAuthComposable(app *ir.Application) string {
	_ = app // reserved for future auth method customization

	var b strings.Builder

	b.WriteString("// Generated by Human compiler — do not edit\n\n")
	b.WriteString("import { ref, computed } from 'vue';\n\n")

	b.WriteString("const isAuthenticated = ref<boolean>(!!localStorage.getItem('token'));\n\n")

	b.WriteString("function login(token: string) {\n")
	b.WriteString("  localStorage.setItem('token', token);\n")
	b.WriteString("  isAuthenticated.value = true;\n")
	b.WriteString("}\n\n")

	b.WriteString("function logout() {\n")
	b.WriteString("  localStorage.removeItem('token');\n")
	b.WriteString("  isAuthenticated.value = false;\n")
	b.WriteString("}\n\n")

	b.WriteString("export function useAuth() {\n")
	b.WriteString("  return { isAuthenticated, login, logout };\n")
	b.WriteString("}\n")

	return b.String()
}

// isPublicPage returns true for pages that should not require authentication.
// These are pages that unauthenticated users need access to.
func isPublicPage(name string) bool {
	lower := strings.ToLower(name)
	return lower == "home" || lower == "login" || lower == "signup" ||
		lower == "sign-up" || lower == "register" || lower == "landing"
}
