package vue

import (
	"fmt"
	"strings"

	"github.com/barun-bash/human/internal/ir"
)

func generateComponent(comp *ir.Component, app *ir.Application) string {
	var b strings.Builder

	b.WriteString("<!-- Generated by Human compiler — do not edit -->\n")
	b.WriteString("<script setup lang=\"ts\">\n")

	hasDataModelImport := false
	for _, prop := range comp.Props {
		if prop.Type != "" && isDataModel(prop.Type, app) {
			hasDataModelImport = true
			break
		}
	}

	if hasDataModelImport {
		models := []string{}
		for _, prop := range comp.Props {
			if prop.Type != "" && isDataModel(prop.Type, app) {
				models = append(models, prop.Type)
			}
		}
		fmt.Fprintf(&b, "import type { %s } from '../types/models';\\n\n", strings.Join(models, ", "))
	}

	if len(comp.Props) > 0 {
		b.WriteString("defineProps<{\n")
		for _, prop := range comp.Props {
			propType := "unknown"
			if prop.Type != "" {
				if isDataModel(prop.Type, app) {
					propType = prop.Type
				} else {
					propType = tsType(prop.Type)
				}
			}
			fmt.Fprintf(&b, "  %s: %s;\n", prop.Name, propType)
		}
		b.WriteString("}>();\n")
	}
	
	if hasClickHandler(comp) {
		b.WriteString("\\ndefineEmits<{ (e: 'click'): void }>();\n")
	}

	b.WriteString("</script>\\n\n")

	b.WriteString("<template>\n")
	if hasClickHandler(comp) {
		fmt.Fprintf(&b, "  <div class=\"%s\" @click=\"$emit('click')\">\n", toKebabCase(comp.Name))
	} else {
		fmt.Fprintf(&b, "  <div class=\"%s\">\n", toKebabCase(comp.Name))
	}

	// Build context for template generation
	propsMap := make(map[string]string)
	for _, p := range comp.Props {
		propsMap[p.Name] = p.Type
	}
	ctx := &pageContext{
		app:   app,
		props: propsMap,
	}

	for _, a := range comp.Content {
		writePageActionVue(&b, a, "    ", ctx)
	}

	b.WriteString("  </div>\n")
	b.WriteString("</template>\n")

	return b.String()
}

func isDataModel(typeName string, app *ir.Application) bool {
	for _, m := range app.Data {
		if m.Name == typeName {
			return true
		}
	}
	return false
}

func hasClickHandler(comp *ir.Component) bool {
	for _, a := range comp.Content {
		lower := strings.ToLower(a.Text)
		if strings.Contains(lower, "on_click") || strings.Contains(lower, "onclick") || strings.Contains(lower, "click") {
			return true
		}
	}
	return false
}
