package vue

import (
	"fmt"
	"strings"

	"github.com/barun-bash/human/internal/ir"
)

func generateRouter(app *ir.Application) string {
	var b strings.Builder

	hasAuth := app.Auth != nil

	b.WriteString("// Generated by Human compiler — do not edit\n\n")
	b.WriteString("import { createRouter, createWebHistory } from 'vue-router';\n")

	if hasAuth {
		b.WriteString("import { useAuth } from './composables/useAuth';\n")
	}

	for _, page := range app.Pages {
		name := page.Name + "Page"
		fmt.Fprintf(&b, "import %s from './pages/%s.vue';\n", name, name)
	}

	b.WriteString("\nconst routes = [\n")
	for _, page := range app.Pages {
		name := page.Name + "Page"
		path := routePath(page.Name)
		if hasAuth && !isPublicPage(page.Name) {
			fmt.Fprintf(&b, "  { path: '%s', name: '%s', component: %s, meta: { requiresAuth: true } },\n", path, name, name)
		} else {
			fmt.Fprintf(&b, "  { path: '%s', name: '%s', component: %s },\n", path, name, name)
		}
	}
	b.WriteString("  { path: '/:pathMatch(.*)*', name: 'NotFound', component: { template: '<div style=\"text-align:center;padding:4rem\"><h1>404</h1><p>Page not found</p></div>' } },\n")
	b.WriteString("];\n\n")

	b.WriteString("export const router = createRouter({\n")
	b.WriteString("  history: createWebHistory(),\n")
	b.WriteString("  routes,\n")
	b.WriteString("});\n")

	if hasAuth {
		b.WriteString("\nrouter.beforeEach((to) => {\n")
		b.WriteString("  if (to.meta.requiresAuth && !localStorage.getItem('token')) {\n")
		b.WriteString("    return { path: '/login' };\n")
		b.WriteString("  }\n")
		b.WriteString("});\n")
	}

	return b.String()
}

func routePath(name string) string {
	if strings.ToLower(name) == "home" {
		return "/"
	}
	return "/" + toKebabCase(name)
}
