package vue

import (
	"fmt"
	"strings"

	"github.com/barun-bash/human/internal/ir"
)

func generateTypes(app *ir.Application) string {
	var b strings.Builder

	b.WriteString("// Generated by Human compiler — do not edit\n\n")

	for i, model := range app.Data {
		if i > 0 {
			b.WriteString("\n")
		}
		writeInterface(&b, model, app)
	}

	return b.String()
}

func writeInterface(b *strings.Builder, model *ir.DataModel, app *ir.Application) {
	fmt.Fprintf(b, "export interface %s {\n", model.Name)

	b.WriteString("  id: string;\n")

	for _, f := range model.Fields {
		optional := ""
		if !f.Required {
			optional = "?"
		}

		var fieldType string
		if f.Type == "enum" && len(f.EnumValues) > 0 {
			fieldType = tsEnumType(f.EnumValues)
		} else {
			fieldType = tsType(f.Type)
		}

		fmt.Fprintf(b, "  %s%s: %s;\n", f.Name, optional, fieldType)
	}

	for _, rel := range model.Relations {
		switch rel.Kind {
		case "belongs_to":
			fmt.Fprintf(b, "  %sId: string;\n", toCamelCase(rel.Target))
			fmt.Fprintf(b, "  %s?: %s;\n", toCamelCase(rel.Target), rel.Target)
		case "has_many", "has_many_through":
			fmt.Fprintf(b, "  %s?: %s[];\n", pluralize(toCamelCase(rel.Target)), rel.Target)
		}
	}

	b.WriteString("}\n")
}
