-- Generated by Human compiler — do not edit
-- Seed data for development

BEGIN;

INSERT INTO users (id, name, email, password, role, avatar)
VALUES ('00000000-0000-0000-0000-000002645995', 'Sample User', 'email@example.com', '$2b$10$sample.hashed.password.for.dev.only', 'employee', 'https://example.com/avatar');

COMMIT;
