// Generated by Human compiler — do not edit

import React from 'react';
import { render, screen, fireEvent } from '@testing-library/react';
import { BrowserRouter } from 'react-router-dom';
import { ForgotPassword } from '../pages/forgot-password';

jest.mock('../api/client');

const renderPage = () => render(
  <BrowserRouter>
    <ForgotPassword />
  </BrowserRouter>
);

describe('ForgotPassword page', () => {
  it('should render without crashing', () => {
    renderPage();
  });

  it('should display Forgot your password?', () => {
    renderPage();
    expect(screen.getByText(/Forgot your password\?/i)).toBeInTheDocument();
  });

  it('should display Enter your email and we\'ll send you a verification code', () => {
    renderPage();
    expect(screen.getByText(/Enter your email and we'll send you a verification code/i)).toBeInTheDocument();
  });

  it('should handle clicking Send Code does SendResetCode', () => {
    renderPage();
    const button = screen.getByText(/Send Code does SendResetCode/i);
    fireEvent.click(button);
  });

  it('should handle clicking Back to Sign In navigates to SignIn', () => {
    renderPage();
    const button = screen.getByText(/Back to Sign In navigates to SignIn/i);
    fireEvent.click(button);
  });

  it('should show loading state', () => {
    renderPage();
    expect(screen.getByText(/loading/i)).toBeInTheDocument();
  });

});
