// Generated by Human compiler — do not edit

import request from 'supertest';
import { app } from '../server';

describe('POST /api/google-login', () => {
  it('should succeed with valid request', async () => {
    const response = await request(app)
      .post('/api/google-login')
      .send({
        google_token: 'test-google_token',
      });

    expect(response.status).toBeLessThan(500);
  });

});
