// Generated by Human compiler — do not edit

import React from 'react';
import { render, screen, fireEvent } from '@testing-library/react';
import { BrowserRouter } from 'react-router-dom';
import { ResetPassword } from '../pages/reset-password';

jest.mock('../api/client');

const renderPage = () => render(
  <BrowserRouter>
    <ResetPassword />
  </BrowserRouter>
);

describe('ResetPassword page', () => {
  it('should render without crashing', () => {
    renderPage();
  });

  it('should display Set a new password', () => {
    renderPage();
    expect(screen.getByText(/Set a new password/i)).toBeInTheDocument();
  });

  it('should handle clicking Reset Password does ResetUserPassword', () => {
    renderPage();
    const button = screen.getByText(/Reset Password does ResetUserPassword/i);
    fireEvent.click(button);
  });

  it('should show loading state', () => {
    renderPage();
    expect(screen.getByText(/loading/i)).toBeInTheDocument();
  });

});
