// Generated by Human compiler — do not edit

import request from 'supertest';
import { app } from '../server';

describe('POST /api/reset-user-password', () => {
  it('should succeed with valid request', async () => {
    const response = await request(app)
      .post('/api/reset-user-password')
      .send({
        reset_token: 'test-reset_token',
        new_password: 'test-new_password',
        confirm_password: 'test-confirm_password',
      });

    expect(response.status).toBeLessThan(500);
  });

  it('should reject new_password shorter than 8 characters', async () => {
    const response = await request(app)
      .post('/api/reset-user-password')
      .send({
        reset_token: 'valid-reset_token',
        new_password: 'x',
        confirm_password: 'valid-confirm_password',
      });

    expect(response.status).toBe(400);
    expect(response.body.error).toBeDefined();
  });

  it('should reject mismatched new_password', async () => {
    const response = await request(app)
      .post('/api/reset-user-password')
      .send({
        reset_token: 'valid-reset_token',
        new_password: 'invalid',
        confirm_password: 'valid-confirm_password',
      });

    expect(response.status).toBe(400);
    expect(response.body.error).toBeDefined();
  });

});
