// Generated by Human compiler — do not edit

import request from 'supertest';
import { app } from '../server';

describe('POST /api/send-reset-code', () => {
  it('should succeed with valid request', async () => {
    const response = await request(app)
      .post('/api/send-reset-code')
      .send({
        email: 'test-email',
      });

    expect(response.status).toBeLessThan(500);
  });

  it('should reject empty email', async () => {
    const response = await request(app)
      .post('/api/send-reset-code')
      .send({
        email: '',
      });

    expect(response.status).toBe(400);
    expect(response.body.error).toBeDefined();
  });

  it('should reject invalid email', async () => {
    const response = await request(app)
      .post('/api/send-reset-code')
      .send({
        email: 'not-an-email',
      });

    expect(response.status).toBe(400);
    expect(response.body.error).toBeDefined();
  });

});
