// Generated by Human compiler — do not edit

import React from 'react';
import { render, screen, fireEvent } from '@testing-library/react';
import { BrowserRouter } from 'react-router-dom';
import { SignIn } from '../pages/sign-in';

jest.mock('../api/client');

const renderPage = () => render(
  <BrowserRouter>
    <SignIn />
  </BrowserRouter>
);

describe('SignIn page', () => {
  it('should render without crashing', () => {
    renderPage();
  });

  it('should display the app name and tagline Track your time, own your day', () => {
    renderPage();
    expect(screen.getByText(/the app name and tagline Track your time, own your day/i)).toBeInTheDocument();
  });

  it('should handle clicking Sign In does Login', () => {
    renderPage();
    const button = screen.getByText(/Sign In does Login/i);
    fireEvent.click(button);
  });

  it('should handle clicking Forgot Password? navigates to ForgotPassword', () => {
    renderPage();
    const button = screen.getByText(/Forgot Password\? navigates to ForgotPassword/i);
    fireEvent.click(button);
  });

  it('should handle clicking Sign Up navigates to SignUp', () => {
    renderPage();
    const button = screen.getByText(/Sign Up navigates to SignUp/i);
    fireEvent.click(button);
  });

  it('should handle clicking Continue with Google does GoogleLogin', () => {
    renderPage();
    const button = screen.getByText(/Continue with Google does GoogleLogin/i);
    fireEvent.click(button);
  });

  it('should handle clicking Continue with Slack does SlackLogin', () => {
    renderPage();
    const button = screen.getByText(/Continue with Slack does SlackLogin/i);
    fireEvent.click(button);
  });

  it('should show loading state', () => {
    renderPage();
    expect(screen.getByText(/loading/i)).toBeInTheDocument();
  });

});
