// Generated by Human compiler — do not edit

import request from 'supertest';
import { app } from '../server';

describe('POST /api/verify-reset-code', () => {
  it('should succeed with valid request', async () => {
    const response = await request(app)
      .post('/api/verify-reset-code')
      .send({
        email: 'test-email',
        code: 'test-code',
      });

    expect(response.status).toBeLessThan(500);
  });

  it('should reject empty code', async () => {
    const response = await request(app)
      .post('/api/verify-reset-code')
      .send({
        email: 'valid-email',
        code: '',
      });

    expect(response.status).toBe(400);
    expect(response.body.error).toBeDefined();
  });

  it('should reject mismatched reset_code', async () => {
    const response = await request(app)
      .post('/api/verify-reset-code')
      .send({
        email: 'valid-email',
        code: 'valid-code',
      });

    expect(response.status).toBe(400);
    expect(response.body.error).toBeDefined();
  });

});
