// Generated by Human compiler — do not edit

import React from 'react';
import { render, screen, fireEvent } from '@testing-library/react';
import { BrowserRouter } from 'react-router-dom';
import { VerifyCode } from '../pages/verify-code';

jest.mock('../api/client');

const renderPage = () => render(
  <BrowserRouter>
    <VerifyCode />
  </BrowserRouter>
);

describe('VerifyCode page', () => {
  it('should render without crashing', () => {
    renderPage();
  });

  it('should display Check your email', () => {
    renderPage();
    expect(screen.getByText(/Check your email/i)).toBeInTheDocument();
  });

  it('should display Enter the 6-digit code we sent to your email', () => {
    renderPage();
    expect(screen.getByText(/Enter the 6-digit code we sent to your email/i)).toBeInTheDocument();
  });

  it('should handle clicking Verify does VerifyResetCode', () => {
    renderPage();
    const button = screen.getByText(/Verify does VerifyResetCode/i);
    fireEvent.click(button);
  });

  it('should handle clicking Resend Code does SendResetCode', () => {
    renderPage();
    const button = screen.getByText(/Resend Code does SendResetCode/i);
    fireEvent.click(button);
  });

  it('should handle clicking Back to Sign In navigates to SignIn', () => {
    renderPage();
    const button = screen.getByText(/Back to Sign In navigates to SignIn/i);
    fireEvent.click(button);
  });

  it('should show loading state', () => {
    renderPage();
    expect(screen.getByText(/loading/i)).toBeInTheDocument();
  });

});
