// Generated by Human compiler — do not edit

import { Router, Request, Response, NextFunction } from 'express';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();
const router = Router();

router.post('/', async (req: Request, res: Response, next: NextFunction) => {
  try {
    const { email } = req.body;

    // Validation
    if (!email || email.trim() === '') {
      return res.status(400).json({ error: 'email is required' });
    }
    if (!email || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
      return res.status(400).json({ error: 'Invalid email address' });
    }

    // fetch the user by email
    const result = await prisma.user.findUnique({ where: { id: req.body.id } });

    // if user exists, send password reset email
    // respond with If an account exists, we'll send reset instructions
    return res.json({ data: result });

  } catch (error) {
    next(error);
  }
});

export { router };
