// Generated by Human compiler — do not edit

import { Router } from 'express';
import { router as loginRouter } from './login';
import { router as forgotPasswordRouter } from './forgot-password';

const router = Router();

router.use('/login', loginRouter);
router.use('/forgot-password', forgotPasswordRouter);

export { router };
