// Generated by Human compiler — do not edit

import { Router, Request, Response, NextFunction } from 'express';
import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';
import { signToken } from '../middleware/auth';

const prisma = new PrismaClient();
const router = Router();

router.post('/', async (req: Request, res: Response, next: NextFunction) => {
  try {
    const { email, password } = req.body;

    // Validation
    if (!email || email.trim() === '') {
      return res.status(400).json({ error: 'email is required' });
    }
    if (!password || password.trim() === '') {
      return res.status(400).json({ error: 'password is required' });
    }
    // TODO: validate that password matches expected pattern

    // fetch the user by email
    const user = await prisma.user.findUnique({ where: { email } });

    // if user does not exist, respond with invalid credentials
    if (!user) {
      return res.status(401).json({ error: 'Invalid credentials' });
    }

    // if password does not match, respond with invalid credentials
    const valid = await bcrypt.compare(password, user.password);
    if (!valid) {
      return res.status(401).json({ error: 'Invalid credentials' });
    }

    // respond with the user and auth token
    const token = signToken(user.id, user.role);
    return res.json({ data: user, token });

  } catch (error) {
    next(error);
  }
});

export { router };
