-- Generated by Human compiler — do not edit
-- Seed data for development

BEGIN;

INSERT INTO users (id, name, email, password, reset_code, reset_code_expires)
VALUES ('00000000-0000-0000-0000-000002645995', 'Sample User', 'email@example.com', '$2b$10$sample.hashed.password.for.dev.only', 'sample_reset_code', '2025-01-15T00:00:00Z');

COMMIT;
