// Generated by Human compiler — do not edit

export interface User {
  id: string;
  name: string;
  email: string;
  password: string;
  reset_code?: string;
  reset_code_expires?: string;
  created: string;
}
