// Generated by Human compiler — do not edit

import { Request, Response, NextFunction } from 'express';

function sleep(ms: number): Promise<void> {
  return new Promise(resolve => setTimeout(resolve, ms));
}

export function errorHandler(err: Error, req: Request, res: Response, _next: NextFunction) {
  console.error('[Error]', err.message);

  // Database connection errors
  if (err.message.includes('connect') || err.message.includes('ECONNREFUSED')) {
    return res.status(503).json({
      error: 'Service temporarily unavailable. Please try again.',
    });
  }

  // Validation errors
  if (err.name === 'ValidationError' || err.message.includes('validation')) {
    return res.status(400).json({
      error: err.message,
    });
  }

  // Default server error
  return res.status(500).json({
    error: 'An unexpected error occurred. Please try again later.',
  });
}

export async function withRetry<T>(
  fn: () => Promise<T>,
  retries: number = 3,
  delayMs: number = 1000,
): Promise<T> {
  let lastError: Error | undefined;
  for (let attempt = 1; attempt <= retries; attempt++) {
    try {
      return await fn();
    } catch (err) {
      lastError = err instanceof Error ? err : new Error(String(err));
      if (attempt < retries) {
        await sleep(delayMs);
      }
    }
  }
  throw lastError;
}
