package quality

import (
	"fmt"
	"strings"
	"time"

	"github.com/barun-bash/human/internal/ir"
)

// renderBuildSummary produces a build-report.md with overall build statistics.
func renderBuildSummary(app *ir.Application, outputDir string, result *Result) string {
	var b strings.Builder

	b.WriteString("# Build Report\n\n")
	b.WriteString("Generated by Human compiler.\n\n")

	// Timestamp
	fmt.Fprintf(&b, "**Built at:** %s\n\n", time.Now().UTC().Format(time.RFC3339))

	// Application info
	b.WriteString("## Application\n\n")
	fmt.Fprintf(&b, "| Property | Value |\n")
	fmt.Fprintf(&b, "|----------|-------|\n")
	fmt.Fprintf(&b, "| Name | %s |\n", app.Name)
	fmt.Fprintf(&b, "| Platform | %s |\n", app.Platform)
	if app.Config != nil {
		if app.Config.Frontend != "" {
			fmt.Fprintf(&b, "| Frontend | %s |\n", app.Config.Frontend)
		}
		if app.Config.Backend != "" {
			fmt.Fprintf(&b, "| Backend | %s |\n", app.Config.Backend)
		}
		if app.Config.Database != "" {
			fmt.Fprintf(&b, "| Database | %s |\n", app.Config.Database)
		}
		if app.Config.Deploy != "" {
			fmt.Fprintf(&b, "| Deploy | %s |\n", app.Config.Deploy)
		}
	}
	b.WriteString("\n")

	// IR counts
	b.WriteString("## IR Summary\n\n")
	b.WriteString("| Element | Count |\n")
	b.WriteString("|---------|-------|\n")
	fmt.Fprintf(&b, "| Data Models | %d |\n", len(app.Data))
	fmt.Fprintf(&b, "| Pages | %d |\n", len(app.Pages))
	fmt.Fprintf(&b, "| Components | %d |\n", len(app.Components))
	fmt.Fprintf(&b, "| API Endpoints | %d |\n", len(app.APIs))
	fmt.Fprintf(&b, "| Policies | %d |\n", len(app.Policies))
	fmt.Fprintf(&b, "| Workflows | %d |\n", len(app.Workflows))
	fmt.Fprintf(&b, "| Integrations | %d |\n", len(app.Integrations))
	b.WriteString("\n")

	// Quality summary
	b.WriteString("## Quality\n\n")

	criticals := 0
	warnings := 0
	for _, f := range result.SecurityFindings {
		switch f.Severity {
		case "critical":
			criticals++
		case "warning":
			warnings++
		}
	}

	totalTests := result.TestCount + result.ComponentTestCount + result.EdgeTestCount + result.IntegrationTestCount
	totalFiles := result.TestFiles + result.ComponentTestFiles + result.EdgeTestFiles
	if result.IntegrationTestCount > 0 {
		totalFiles++
	}

	b.WriteString("| Metric | Count |\n")
	b.WriteString("|--------|-------|\n")
	fmt.Fprintf(&b, "| API Tests | %d |\n", result.TestCount)
	fmt.Fprintf(&b, "| Component Tests | %d |\n", result.ComponentTestCount)
	fmt.Fprintf(&b, "| Edge Case Tests | %d |\n", result.EdgeTestCount)
	fmt.Fprintf(&b, "| Integration Tests | %d |\n", result.IntegrationTestCount)
	fmt.Fprintf(&b, "| **Total Tests** | **%d** |\n", totalTests)
	fmt.Fprintf(&b, "| Test Files | %d |\n", totalFiles)
	fmt.Fprintf(&b, "| Security Critical | %d |\n", criticals)
	fmt.Fprintf(&b, "| Security Warnings | %d |\n", warnings)
	fmt.Fprintf(&b, "| Lint Warnings | %d |\n", len(result.LintWarnings))
	b.WriteString("\n")

	// Coverage section
	if result.Coverage != nil {
		b.WriteString(renderCoverageSection(result.Coverage))
	}

	// Dependencies section
	b.WriteString(renderDependencySection(result.VulnerabilityReport))

	// Duplication section
	b.WriteString(renderDuplicationSection(result.DuplicationFindings))

	// Performance section
	b.WriteString(renderPerformanceSection(result.PerformanceFindings))

	// Traceability section
	if app.Config != nil {
		entries := buildTraceEntries(app, app.Config)
		b.WriteString(renderTraceabilitySection(entries))
	}

	// Output directory
	fmt.Fprintf(&b, "**Output:** `%s`\n", outputDir)

	return b.String()
}
