// Generated by Human compiler — do not edit

const API_BASE_URL = import.meta.env.VITE_API_URL || '';

export interface ApiResponse<T> {
  data: T;
  error?: string;
}

async function request<T>(
  method: string,
  path: string,
  body?: Record<string, unknown>,
): Promise<ApiResponse<T>> {
  const token = localStorage.getItem('token');
  const headers: Record<string, string> = {
    'Content-Type': 'application/json',
  };
  if (token) {
    headers['Authorization'] = `Bearer ${token}`;
  }
  const res = await fetch(`${API_BASE_URL}${path}`, {
    method,
    headers,
    body: body ? JSON.stringify(body) : undefined,
  });
  return res.json();
}

export async function createAccount(params: { name: string; email: string; password: string; confirm_password: string }) {
  return request<unknown>('POST', '/api/account', params as unknown as Record<string, unknown>);
}

export async function login(params: { email: string; password: string }) {
  return request<unknown>('POST', '/api/login', params as unknown as Record<string, unknown>);
}

export async function googleLogin(params: { google_token: string }) {
  return request<unknown>('POST', '/api/google-login', params as unknown as Record<string, unknown>);
}

export async function slackLogin(params: { slack_token: string }) {
  return request<unknown>('POST', '/api/slack-login', params as unknown as Record<string, unknown>);
}

export async function sendResetCode(params: { email: string }) {
  return request<unknown>('POST', '/api/send-reset-code', params as unknown as Record<string, unknown>);
}

export async function verifyResetCode(params: { email: string; code: string }) {
  return request<unknown>('POST', '/api/verify-reset-code', params as unknown as Record<string, unknown>);
}

export async function resetUserPassword(params: { reset_token: string; new_password: string; confirm_password: string }) {
  return request<unknown>('POST', '/api/reset-user-password', params as unknown as Record<string, unknown>);
}
