package angular

import (
	"strings"
)

// generateAuthService produces src/app/services/auth.service.ts with an Angular
// injectable service that manages authentication state via localStorage token
// and Angular signals.
func generateAuthService() string {
	var b strings.Builder

	b.WriteString("// Generated by Human compiler — do not edit\n\n")
	b.WriteString("import { Injectable, signal } from '@angular/core';\n\n")

	b.WriteString("@Injectable({ providedIn: 'root' })\n")
	b.WriteString("export class AuthService {\n")
	b.WriteString("  isAuthenticated = signal(!!localStorage.getItem('token'));\n\n")

	b.WriteString("  login(token: string): void {\n")
	b.WriteString("    localStorage.setItem('token', token);\n")
	b.WriteString("    this.isAuthenticated.set(true);\n")
	b.WriteString("  }\n\n")

	b.WriteString("  logout(): void {\n")
	b.WriteString("    localStorage.removeItem('token');\n")
	b.WriteString("    this.isAuthenticated.set(false);\n")
	b.WriteString("  }\n")
	b.WriteString("}\n")

	return b.String()
}

// generateAuthGuard produces src/app/guards/auth.guard.ts with a functional
// route guard that checks authentication state via AuthService.
func generateAuthGuard() string {
	var b strings.Builder

	b.WriteString("// Generated by Human compiler — do not edit\n\n")
	b.WriteString("import { inject } from '@angular/core';\n")
	b.WriteString("import { CanActivateFn, Router } from '@angular/router';\n")
	b.WriteString("import { AuthService } from '../services/auth.service';\n\n")

	b.WriteString("export const authGuard: CanActivateFn = () => {\n")
	b.WriteString("  const authService = inject(AuthService);\n")
	b.WriteString("  const router = inject(Router);\n\n")

	b.WriteString("  if (authService.isAuthenticated()) {\n")
	b.WriteString("    return true;\n")
	b.WriteString("  }\n\n")

	b.WriteString("  return router.createUrlTree(['/login']);\n")
	b.WriteString("};\n")

	return b.String()
}

// isPublicPage returns true for pages that should not require authentication.
// These are pages that unauthenticated users need access to.
func isPublicPage(name string) bool {
	lower := strings.ToLower(name)
	return lower == "home" || lower == "login" || lower == "signup" ||
		lower == "sign-up" || lower == "register" || lower == "landing"
}
