package angular

import (
	"fmt"
	"strings"

	"github.com/barun-bash/human/internal/ir"
)

func generateTypes(app *ir.Application) string {
	var b strings.Builder
	b.WriteString("// Generated by Human compiler — do not edit\n\n")

	for i, model := range app.Data {
		if i > 0 {
			b.WriteString("\n")
		}
		fmt.Fprintf(&b, "export interface %s {\n", model.Name)
		b.WriteString("  id: string;\n")

		for _, f := range model.Fields {
			optional := ""
			if !f.Required {
				optional = "?"
			}
			fieldType := tsType(f.Type)
			if f.Type == "enum" && len(f.EnumValues) > 0 {
				fieldType = tsEnumType(f.EnumValues)
			}
			fmt.Fprintf(&b, "  %s%s: %s;\n", f.Name, optional, fieldType)
		}

		for _, rel := range model.Relations {
			switch rel.Kind {
			case "belongs_to":
				fmt.Fprintf(&b, "  %sId: string;\n", toCamelCase(rel.Target))
				fmt.Fprintf(&b, "  %s?: %s;\n", toCamelCase(rel.Target), rel.Target)
			case "has_many", "has_many_through":
				fmt.Fprintf(&b, "  %s?: %s[];\n", toCamelCase(rel.Target)+"s", rel.Target)
			}
		}
		b.WriteString("}\n")
	}

	return b.String()
}

func generateApiService(app *ir.Application) string {
	var b strings.Builder
	b.WriteString(`// Generated by Human compiler — do not edit

import { Injectable, inject } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Observable } from 'rxjs';

export interface ApiResponse<T> {
  data: T;
  error?: string;
}

@Injectable({ providedIn: 'root' })
export class ApiService {
  private http = inject(HttpClient);
  private baseUrl = ''; // Set via environment

  private getHeaders(): HttpHeaders {
    let headers = new HttpHeaders({ 'Content-Type': 'application/json' });
    const token = localStorage.getItem('token');
    if (token) {
      headers = headers.set('Authorization', ` + "`Bearer ${token}`" + `);
    }
    return headers;
  }
`)

	for _, ep := range app.APIs {
		b.WriteString("\n")
		funcName := toCamelCase(ep.Name)
		method := httpMethod(ep.Name)
		path := apiPath(ep.Name)

		if len(ep.Params) > 0 {
			paramFields := make([]string, len(ep.Params))
			for i, p := range ep.Params {
				paramName := toCamelCase(p.Name)
				paramFields[i] = fmt.Sprintf("%s: string", paramName)
			}
			paramType := fmt.Sprintf("{ %s }", strings.Join(paramFields, "; "))
			fmt.Fprintf(&b, "  %s(params: %s): Observable<ApiResponse<unknown>> {\n", funcName, paramType)
			
			if method == "GET" {
				fmt.Fprintf(&b, "    return this.http.get<ApiResponse<unknown>>(`${this.baseUrl}%s`, { headers: this.getHeaders() });\n", path)
			} else {
				methodLower := strings.ToLower(method)
				fmt.Fprintf(&b, "    return this.http.%s<ApiResponse<unknown>>(`${this.baseUrl}%s`, params, { headers: this.getHeaders() });\n", methodLower, path)
			}
		} else {
			fmt.Fprintf(&b, "  %s(): Observable<ApiResponse<unknown>> {\n", funcName)
			methodLower := strings.ToLower(method)
			if method == "GET" || method == "DELETE" {
				fmt.Fprintf(&b, "    return this.http.%s<ApiResponse<unknown>>(`${this.baseUrl}%s`, { headers: this.getHeaders() });\n", methodLower, path)
			} else {
				fmt.Fprintf(&b, "    return this.http.%s<ApiResponse<unknown>>(`${this.baseUrl}%s`, {}, { headers: this.getHeaders() });\n", methodLower, path)
			}
		}
		b.WriteString("  }\n")
	}

	b.WriteString("}\n")
	return b.String()
}
